### ISSUE TITLE
Unable to retrieve consumers groups list.

### ISSUE THREAD

**Issue by pavansai8** [linkedin/Burrow#100]
Unable to retrieve consumers groups list. Throwing below error while sending HTTP request.

error": false
"message": "consumer list returned"
"consumers": [0]
"request": {
"url": "/v2/kafka/DevCluster/consumer"
"host": "nj09mhf5527.mhf.mhc"
"cluster": "DevCluster"
"group": ""
"topic": ""

But we have already few consumer groups present on our kafka cluster.

console-consumer-26402
samplegroup
KafkaManagerOffsetCache
console-consumer-78572
console-consumer-6043
Can someone help me

**Comment by toddpalino** [comment]
Please post your configuration, as well as the exact output from the request. What you've posted is not a response from Burrow, as the consumers key is a list of strings. It can't have an integer 0 as a single entry.

**Comment by Dezarin** [comment]
I'm running into the same issue, so I'm going to piggy back off this.

In Kafka Manager I can see my dev stack has the following consumers:

<img width="1106" alt="consumers" src="https://cloud.githubusercontent.com/assets/1859017/17522359/f0f31b88-5e13-11e6-9c8f-dc00abf2877a.png">

My config file settings are:
```
[general]
logdir=log
logconfig=config/logging.cfg
pidfile=burrow.pid
client-id=burrow-lagchecker

[zookeeper]
hostname=dev02-zookeeper01
hostname=dev02-zookeeper02
hostname=dev02-zookeeper03
port=2181
timeout=6
lock-path=/burrow/notifier

[kafka "dev02"]
broker=dev02-kafka01
broker=dev02-kafka02
broker=dev02-kafka03
broker-port=9092
zookeeper=dev02-zookeeper01
zookeeper=dev02-zookeeper02
zookeeper=dev02-zookeeper03
zookeeper-port=2181
zookeeper-path=/
zookeeper-offsets=false
offsets-topic=__consumer_offsets

[tickers]
broker-offsets=60

[lagcheck]
intervals=10
expire-group=604800
min-distance=1
zookeeper-interval=60
zk-group-refresh=300

[httpserver]
server=on
port=8000
```

Curl output against consumer:
```
curl localhost:8000/v2/kafka/dev02/consumer | json_pp
{
   "message" : "consumer list returned",
   "request" : {
      "cluster" : "dev02",
      "url" : "/v2/kafka/dev02/consumer",
      "host" : "devstack01",
      "group" : "",
      "topic" : ""
   },
   "consumers" : [],
   "error" : false
}
```

Debug logging didn't yield any extra results:
```
2016-08-09 15:34:54 [INFO] Starting Zookeeper client
2016-08-09 15:34:54 [INFO] Starting Offsets Storage module
2016-08-09 15:34:54 [INFO] Starting HTTP server
2016-08-09 15:34:54 [INFO] Starting Zookeeper client for cluster dev02
2016-08-09 15:34:54 [INFO] Starting Kafka client for cluster dev02
2016-08-09 15:34:54 [INFO] Starting consumers for 50 partitions of __consumer_offsets in cluster dev02
2016-08-09 15:35:05 [INFO] Acquired Zookeeper notifier lock
```

Any ideas?  I'm stumped on this one.

**Comment by Dezarin** [comment]
It looks like I can now query consumer groups.  I left it running, and came back to it awhile later and they were there.

**Comment by jsvisa** [comment]
Does the topic was consumed after Burrow started?

**Comment by pavansai8** [comment]
Hi,

Burrow is not inactive consumer groups. When I restart burrow and query for the consumer groups it is throwing as '0'.
And I configured kafka in such a way it commits offsets to both kafka and zookeeper. Can some one help me.

**Comment by pavansai8** [comment]
offsets.storage=kafka
dual.commit.enabled=true
 is the configuration I used for dual commit.

**Comment by jsvisa** [comment]
> Burrow is not inactive consumer groups. When I restart burrow and query for the consumer groups it is throwing as '0'. 

Could you give me more details?

> And I configured kafka in such a way it commits offsets to both kafka and zookeeper. Can some one help me.

Kafka 0.9 or any later, supporting offset commit api, see from here [Offset Management - Apache Kafka - Apache Software Foundation](https://cwiki.apache.org/confluence/display/KAFKA/Offset+Management), if your consumer not commit offset to Kafka, Burrow can't handle it. A simple way to see if the client support offset commiting or not, run the command in Kafka's side:

```bash
$ $KAFKA_PATH/bin/kafka-run-class.sh kafka.tools.GetOffsetShell --topic __consumer_offsets --time -1 --broker-list 127.0.0.1:9092
```

If it output '0', seems no consumer's offset is commited to Kafka

**Comment by pavansai8** [comment]
I mean burrow is not showing inactive consumer groups.
If my burrow stopped running and If I again started it then it is not showing consumers which are present in the kafka. It is showing '0'.
After If I again create a new consumer then it is showing it. What about the rest of the inactive consumer list group?

**Comment by jsvisa** [comment]
No, it can't fetch the inactive ones.

**Comment by pavansai8** [comment]
But monitoring inactive consumers is also a feature in burrow right? Don't mind if I'm wrong. I have just started working on burrow.

**Comment by jsvisa** [comment]
Yes, but after Burrow was restarted, it is consuming the offsets from Kafka topic `__consumer_offset` from the newest, so it can't monitor all the consumers which are inactive after Burrow is restated. 

You can deploy Burrow as a cluster instead of a single one, to avoid this case.

**Comment by pavansai8** [comment]
Thanks I make sense now. I will try to install it as cluster. Is there any installation document for it.

**Comment by jsvisa** [comment]
Sorry, is similar as deploy one instance, all you need to consider is set the same  `lock-path` in all instances.

```
lock-path=/burrow/notifier
```

**Comment by pavansai8** [comment]
Yeah I already have this value in my burrow.cfg. And this installation I moved to three servers where my kafka is running.

[general]
logdir=/home/pbhaskaruni
logconfig=/home/pbhaskaruni/work/go/src/github.com/linkedin/burrow/config/logging.cfg
pidfile=burrow.pid
client-id=burrow-lagchecker
group-blacklist=^(console-consumer-|python-kafka-consumer-).*$

[zookeeper]
hostname=nj09mhf5527.mhf.mhc
hostname=nj09mhf5528.mhf.mhc
hostname=nj09mhf5529.mhf.mhc
port=2181
timeout=6
lock-path=/burrow/notifier

[kafka "DevCluster"]
broker=nj09mhf5527.mhf.mhc
broker=nj09mhf5528.mhf.mhc
broker=nj09mhf5529.mhf.mhc
#broker=kafka04.example.com
#broker=kafka05.example.com
broker-port=9092
zookeeper=nj09mhf5527.mhf.mhc
zookeeper=nj09mhf5528.mhf.mhc
zookeeper=nj09mhf5529.mhf.mhc
zookeeper-port=2181
zookeeper-path=/
offsets-topic=__consumer_offsets

**Comment by jsvisa** [comment]
Sounds good 👍

**Comment by nitingupta89** [comment]
@Dezarin I see your kafka-manager screenshot above. I am also using kafka-manager. when i see consumers list it only shows ZK type consumers whereas i am using `kafka` as consumer offset manager. Could you please help me with kafka-manager issue?

**Comment by Dezarin** [comment]
@nitingupta89 I think that depends on whether your client library is storing offsets in zookeeper or Kafka.  Originally, our golang code was using the legacy library which stores offsets in zookeeper.  Once we switched over to the [sarama-cluster](https://github.com/bsm/sarama-cluster) library, offsets began to be stored into kafka, which is why you see both types listed in my kafka-manager screenshot.

**Comment by sszp** [comment]
I have the same issue, the consumer list is empty:

```
curl -s http://localhost:9345/v2/kafka/local/consumer | jq
{
  "error": false,
  "message": "consumer list returned",
  "consumers": [],
  "request": {
    "url": "/v2/kafka/local/consumer",
    "host": "37597841cb23",
    "cluster": "local",
    "group": "",
    "topic": ""
  }
}
```

Although, Kafka reports the consumers with its command:
```
./kafka-consumer-groups.sh  --bootstrap-server localhost:9092 --list --new-consumer
```

The burrow config is the following:
```
[general]
logconfig=/etc/burrow/logging.cfg

[zookeeper]
hostname=172.18.0.3
port=2181
timeout=6
lock-path=/burrow/notifier

[kafka "local"]
broker=172.18.0.4
zookeeper=172.18.0.3
zookeeper-path=/

[tickers]
broker-offsets=10

[lagcheck]
intervals=10
expire-group=604800

[httpserver]
server=on
```

I am using Kafka v0.10.0.0

**Comment by csueiras** [comment]
I am also experiencing this issue, I'm using Kafka 0.10 and my configuration is basically the same as the person above. I've been trying to debug the issue inside of burrow myself and it just seems like it just doesn't ever get a message from the offsets topic (I added some more logging to processConsumerOffsetsMessage in kafka_client.go). I have however verified that the offsets topic is not empty.

**Comment by toddpalino** [comment]
While the offsets topic is not empty, is it getting new offsets? Burrow does not currently consume the offsets topic from the beginning, just from when it starts.
