### ISSUE TITLE
lag most time is 0

### ISSUE THREAD

**Issue by xyfree** [linkedin/Burrow#101]
When I use burrow, the Lag is 0 in most time, but the state is OK.
After I open trace log.I found that, the broker's offset is smaller than consumer offset in most time.  
I  read the codes ,The time to get the broker's offset is not the time to get comsumer's offset ; In this conditions ,how to ensure the lag is right?
Need I only to  focus the result of  STAT?
Thanks !

**Comment by toddpalino** [comment]
This is probably a result of the consumer committing offsets faster than the broker offsets are updated in Burrow, and the consumer is caught up all the time. You can increase the frequency of broker offset fetches by changing the `broker-offsets` value in the `[tickers]` section of the config. The default is 60 seconds.
