### ISSUE TITLE
cannot find package "github.com/linkedin/Burrow/notifier" 

### ISSUE THREAD

**Issue by petergdoyle** [linkedin/Burrow#108]
Step 6 : RUN cd $GOPATH/src/github.com/linkedin/burrow && gpm install && go install
 ---> Running in 2de8e9b8ac0b
>> Getting package github.com/samuel/go-zookeeper/zk
>> Getting package github.com/Shopify/sarama
>> Getting package github.com/cihub/seelog
>> Getting package gopkg.in/gcfg.v1
>> Getting package github.com/pborman/uuid
>> Setting github.com/Shopify/sarama to version 4ba9bba6adb6697bcec3841e1ecdfecf5227c3b9
>> Setting github.com/samuel/go-zookeeper/zk to version ad552be7b78b762b4a8040ffc5518bdaf5b7225d
>> Setting github.com/cihub/seelog to version 92dc4b8b540607b8187cc2f95cac200211dcd745
>> Setting github.com/pborman/uuid to version ca53cad383cad2479bbba7f7a1a05797ec1386e4
>> Setting gopkg.in/gcfg.v1 to version 0ef1a8547f99b94fac9af5377dd72febba18f37c
>> Building package github.com/samuel/go-zookeeper/zk
>> Building package github.com/Shopify/sarama
>> Building package github.com/cihub/seelog
>> Building package gopkg.in/gcfg.v1
>> Building package github.com/pborman/uuid
>> All Done
notify_center.go:15:2: cannot find package "github.com/linkedin/Burrow/notifier" in any of:
	/usr/local/go/src/github.com/linkedin/Burrow/notifier (from $GOROOT)
	/go/src/github.com/linkedin/Burrow/notifier (from $GOPATH)
debug.go:15:2: cannot find package "github.com/linkedin/Burrow/protocol" in any of:
	/usr/local/go/src/github.com/linkedin/Burrow/protocol (from $GOROOT)
	/go/src/github.com/linkedin/Burrow/protocol (from $GOPATH)
The command '/bin/sh -c cd $GOPATH/src/github.com/linkedin/burrow && gpm install && go install' returned a non-zero code: 1

**Comment by jsvisa** [comment]
@petergdoyle  Fixed in [fix docker build => burrow to Burrow by matsu-chara · Pull Request #105 · linkedin/Burrow](https://github.com/linkedin/Burrow/pull/105)

**Comment by petergdoyle** [comment]
yes manually made changes to the Dockerfile for now. Thanks!
