### ISSUE TITLE
cannot find package "github.com/golang/snappy/snappy"

### ISSUE THREAD

**Issue by karthikus** [linkedin/Burrow#11]
I am trying to install Burrow and gpm install gives me the following error

>> Getting package github.com/samuel/go-zookeeper/zk
>> Getting package github.com/Shopify/sarama
>> Getting package github.com/cihub/seelog
>> Getting package code.google.com/p/gcfg
>> Getting package github.com/pborman/uuid
>> Setting github.com/samuel/go-zookeeper/zk to version ad552be7b78b762b4a8040ffc5518bdaf5b7225d
>> Setting github.com/Shopify/sarama to version 2ca3f4f9705b8391a9a1fe3e6ead0d57313108d9
>> Setting github.com/cihub/seelog to version 92dc4b8b540607b8187cc2f95cac200211dcd745
>> Setting code.google.com/p/gcfg to version c2d3050044d05357eaf6c3547249ba57c5e235cb
>> Setting github.com/pborman/uuid to version ca53cad383cad2479bbba7f7a1a05797ec1386e4
>> Building package github.com/samuel/go-zookeeper/zk
>> Building package github.com/Shopify/sarama
../../Shopify/sarama/snappy.go:7:2: cannot find package "github.com/golang/snappy/snappy" in any of:
	/usr/lib/go/src/github.com/golang/snappy/snappy (from $GOROOT)
	/home/ceph/go/src/github.com/golang/snappy/snappy (from $GOPATH)

**Comment by toddpalino** [comment]
This was reported under pull request #10. The owner of the snappy library has decided to move their code and has deleted the old version.

**Comment by toddpalino** [comment]
The latest Godeps file in the project will resolve this.
