### ISSUE TITLE
burrow process crashed without any infomation

### ISSUE THREAD

**Issue by powerLambda** [linkedin/Burrow#112]
I use the Dockerfile to build burrow image, the process crashed after sometimes, and I'm not able to start it again because of the burrow.pid is not deleted in "main.go, defer removePidFile".

It seems that "defer" is not guaranteed to be executed 100%,  any idea about this issue?

1471231004131214854 [Critical] Cannot write PID file: open /var/tmp/burrow/burrow.pid: file exists
shawguo@shawguo-intg-server:/var/lib/docker$ docker start -ai a02fab4f91e1
1471231017000196692 [Critical] Cannot write PID file: open /var/tmp/burrow/burrow.pid: file exists

**Comment by powerLambda** [comment]
The root cause is burrow process crashed without any information.  I use the main branch(0815).

I'm trying to catch any useful information but I'm not quit familiar with golang, any suggestion is appreciated. I can reproduce it and I want to print more information about crash stack.

**Comment by powerLambda** [comment]
@toddpalino

**Comment by deric** [comment]
I'm having similar issue, it would be useful to have possibility to enable debug mode.

**Comment by cgosiak** [comment]
I know that I have encountered this issue when I force stop Burrow. I am making the assumption that Burrow inadvertently shut down; which would cause Burrow (like when I force stop it) to not gracefully shutdown and clean up any remnants of data that it depends on. 

My suggestion is to: Look at the burrow. config file you used to start the process. In the [general] section you will see a "logdir" and a "pidfile". I would just delete that file, and you should be able to start burrow again. 

As far as debugging burrow, you will find some really helpful files in the log directory that should be able to give you some additional output.

**Comment by CVTJNII** [comment]
This might be a combination of #57 and #152.  By default the app intercepts all stdout/stderr logs and sends them to /var/tmp/burrow/burrow.out.  If you're starting with the compose config included then the logs should be in $(pwd)/tmp/ but if you're running it by hand then they're going to the bit bucket.  I've opened #152 to change container logging to default to stdout/stderr.

**Comment by toddpalino** [comment]
Resolved by #152
