### ISSUE TITLE
Burrow is not showing lag and max lag values as null always

### ISSUE THREAD

**Issue by pavansai8** [linkedin/Burrow#113]
Burrow is showing lag and max lag as null always. Can someone help me on this. I have stopped my consumer and sent number of messages from producer side still the lag and max lag are showing as null. 
I'm using Advanced Rest client to send http request.
Below is the request and response.

http://nj09mhf5527.mhf.mhc:8000/v2/kafka/DevCluster/consumer/testgroup90/lag

{
"error": false
"message": "consumer group status returned"
"status": {
"cluster": "DevCluster"
"group": "testgroup90"
"status": "ERR"
"complete": true
"partitions": [1]
0:  {
"topic": "topic03"
"partition": 0
"status": "STOP"
"start": {
"offset": 145
"timestamp": 1471419404000
"lag": 0
}-
"end": {
"offset": 145
"timestamp": 1471419404000
"lag": 0
}-
## }-

"partition_count": 1
"maxlag": null
"totallag": 0
}-
"request": {
"url": "/v2/kafka/DevCluster/consumer/testgroup90/lag"
"host": "nj09mhf5527.mhf.mhc"
"cluster": "DevCluster"
"group": "testgroup90"
"topic": ""
}-
}

**Comment by pavansai8** [comment]
Hi Guys,

I installed the burrow-stats UI for my burrow. There I can see the consumer lag but my burrow is not showing that value. Always it is saying "lag":0 .
I'm using Advanced Rest client to sent http requests.
Using Get, application/json type.

**Comment by toddpalino** [comment]
Your partition is in the stopped state, so lag is not calculated. This is the issue I have described in #127 which is going to require a lot of work to change.

Closing this as a dupe, but you can track that one as we'll update it once someone is able to put time into this.
