### ISSUE TITLE
How to use the Http notifier in burrow?

### ISSUE THREAD

**Issue by pavansai8** [linkedin/Burrow#116]
I have configured in this way. But nothing is happening

[httpnotifier]
url=http://nj09mhf5528.mhf.mhc:9000/v1/alert
interval=60
extra=app=burrow
extra=tier=STG
template-post=/home/pbhaskaruni/work/go/src/github.com/linkedin/burrow/config/default-http-post.tmpl
template-delete=/home/pbhaskaruni/work/go/src/github.com/linkedin/burrow/config/default-http-delete.tmpl
timeout=5
keepalive=30

**Comment by toddpalino** [comment]
"Nothing is happening" is very vague. There are no errors being reported at startup on processing the templates? There are no ongoing log messages about not being able to contact the endpoint? Are there any consumers that are actually bad (i.e. that should be having things sent out?)? Have you sniffed the traffic to that host to see if any connections are being attempted from Burrow?
