### ISSUE TITLE
What does Slack threshold  means ?

### ISSUE THREAD

**Issue by haimari** [linkedin/Burrow#117]
Is this documented anywhere ?
If not, what does it mean ?

[slacknotifier]
enable=true
url=https://hooks.slack.com/services/xxxxxxxx/xxxxxxxxxxxxxxxxx
group=NJ,group1
group=VA,group1
**threshold=1**
channel="#general"
username=burrow
interval=3600
timeout=5
keepalive=30

**Comment by ms7s** [comment]
I was trying the slack notifier a moment ago and found it in the code:
https://github.com/linkedin/Burrow/blob/ff0c18868e364866fa74148b3f1b743a867d90c6/protocol/protocol.go#L37

If the value of the status is smaller than `threshold`, that status is ignored when sending to Slack.

**Comment by waltari2001** [comment]
That's really confusing. I do NOT want constant OK notifications sent to Slack, only the ones >= WARN. What would be the right settings for that?

**Comment by ms7s** [comment]
@waltari2001 I believe you need to set threshold to `2` in this case.
