### ISSUE TITLE
gpm install not completing

### ISSUE THREAD

**Issue by anandsk123** [linkedin/Burrow#118]
gpm install
>> Getting package github.com/samuel/go-zookeeper/zk
>> Getting package github.com/Shopify/sarama
>> Getting package github.com/cihub/seelog
>> Getting package gopkg.in/gcfg.v1
>> Getting package github.com/pborman/uuid

Hanging after the above output, is there a debug flag for the above command?

**Comment by toddpalino** [comment]
This is a question for gpm, not for us. This looks like a temporary error when getting packages from external sources.
