### ISSUE TITLE
Got email from burrow, but it's empty

### ISSUE THREAD

**Issue by edvorkin** [linkedin/Burrow#119]
I am testing burrow as a docker container. Managed to get error email but it's empty:
I see only subject, but not content. 
Any ideas?

Error that triggered email:
$ curl http://localhost:8000/v2/kafka/development/consumer/test/status
{"error":false,"message":"consumer group status returned","status":{"cluster":"development","group":"test","status":"ERR","complete":true,"partitions":[{"topic":"fast-messages","partition":0,"status":"STOP","start":{"offset":3294911,"timestamp":1471571136000,"lag":0},"end":{"offset":3294911,"timestamp":1471571176000,"lag":0}},{"topic":"summary-markers","partition":0,"status":"STOP","start":{"offset":3313,"timestamp":1471571136000,"lag":0},"end":{"offset":3313,"timestamp":1471571176000,"lag":0}}],"partition_count":2,"maxlag":null,"totallag":0},"request":{"url":"/v2/kafka/development/consumer/test/status","host":"d74aafb4aedf","cluster":"development","group":"test","topic":""}}

My setting:
$ cat /etc/burrow/burrow.cfg
[general]
logconfig=/etc/burrow/logging.cfg
pidfile=burrow.pid
client-id=burrow-lagchecker
group-blacklist=^(console-consumer-|python-kafka-consumer-).*$

[zookeeper]
hostname=zookeeper.service.consul
port=2181
timeout=6
lock-path=/burrow/notifier

[kafka "development"]
broker=kafka.service.consul
broker-port=9092
zookeeper-path=/
offsets-topic=__consumer_offsets
zookeeper-offsets=true
zookeeper=zookeeper.service.consul
zookeeper-port=2181
zookeeper-path=/
zookeeper-offsets=true

[tickers]
broker-offsets=60

[lagcheck]
intervals=10
expire-group=604800

[httpserver]
server=on
port=8000

[smtp]
server=dc1mailrelay.ga.adp.com
port=25
auth-type=""
from=burrow-kafka-noreply@adp.com
template=/etc/burrow/default-email.tmpl

[emailnotifier "eugene.dvorkin@my.com"]
group=development,kafka-node-group
group=development,DDLTimeMachine
group=development,DDLEntityChanges
group=development,teletraan
group=development,ddlReactor
group=development,ohcm-metadata
group=development,LogiNextStage
group=development,mini-apps
group=development,LogiDispatchStage
group=development,ForTriggeringWorkflows
group=development,ohcm-search-orchestrator
interval=60

[notify]
interval=10
[vagrant@devbox] /vagrant

and my email template:
$ cat /etc/burrow/default-email.tmpl
From: {{.From}}
To: {{.To}}
Subject: [Burrow] Kafka Consumer Lag Alert for {{.Cluster}}

The Kafka consumer groups you are monitoring are currently showing problems. The following groups are in a problem state (groups not listed are OK):

{{range .Results}}{{if or (ne 0 .Status) (ne 5 .Status)}}Cluster:  {{.Cluster}}
Group:    {{.Group}}
Status:   {{if eq 1 .Status}}WARNING{{else if eq 2 .Status}}ERROR{{end}}
Complete: {{.Complete}}
Errors:   {{len .Partitions}} partitions have problems
{{range .Partitions}}          {{if eq 1 .Status}} WARN{{else if eq 2 .Status}}  ERR{{else if eq 3 .Status}} STOP{{else if eq 4 .Status}}STALL{{end}} {{.Topic}}:{{.Partition}} ({{.Start.Timestamp}}, {{.Start.Offset}}, {{.Start.Lag}}) -> ({{.End.Timestamp}}, {{.End.Offset}}, {{.End.Lag}})
{{end}}{{end}}

---

{{end}}

**Comment by toddpalino** [comment]
The fact that you got a subject line says that your template is being processed correctly. This sounds like it might be a problem with your mail system or client. Can you provide the raw email message that you received?
