### ISSUE TITLE
Error when I run go get

### ISSUE THREAD

**Issue by doug2525** [linkedin/Burrow#121]
go get github.com/linkedin/burrow

package gopkg.in/gcfg.v1: unrecognized import path "gopkg.in/gcfg.v1" (https fetch: Get https://gopkg.in/gcfg.v1?go-get=1: x509: certificate signed by unknown authority)

**Comment by toddpalino** [comment]
This is a problem with the SSL certificate for gopkg.in, and is unrelated to Burrow itself. It looks OK now in my browser, so it may have been a temporary error, or an issue with your CA root certificates bundle
