### ISSUE TITLE
Email notify support gmail?

### ISSUE THREAD

**Issue by keyboardfann** [linkedin/Burrow#122]
Dear Sir,
   The Email notify auth support no auth , plaintext , and crammd5 . Does Burrow email notify function support gmail ?  

Fann

**Comment by toddpalino** [comment]
Please see the following link for Google support:
https://support.google.com/a/answer/176600?hl=en

You should be using plaintext authentication with gmail, and Burrow will work properly.

**Comment by keyboardfann** [comment]
Dear @toddpalino,
    I follow your link and set up it , but still can't get notify mail , is any thing wrong or any log can help to troubleshooting?
   Thank you and  wait the response.

burrow.cfg
`[general]
#logdir=log
#logconfig=config/logging.cfg
pidfile=burrow.pid
client-id=burrow-lagchecker
group-blacklist=^(console-consumer-|python-kafka-consumer-).*$

[zookeeper]
hostname=localhost
port=2181
timeout=6
lock-path=/burrow/notifier

[kafka "local"]
broker=localhost
broker-port=9092
zookeeper=localhost
zookeeper-port=2181
zookeeper-path=/kafka-cluster
offsets-topic=__consumer_offsets
 
[tickers]
broker-offsets=60

[lagcheck]
intervals=10
expire-group=604800
min-distance=1
zookeeper-interval=60
zk-group-refresh=300

[httpserver]
server=on
port=8000

[smtp]
server=aspmx.l.google.com
port=25
auth-type=
username=keyboardfann
password=xxxxxxx
from=keyboardfann@gmail.com
template=./default-email.tmpl

[emailnotifier "keyboardfann@gmail.com"]
group=local,securing-kafka-group
interval=60

[notify]
interval=10
`

burrow.out
`1472541445407579535 [Info] Starting Zookeeper client
2016/08/30 15:17:25 Connected to [::1]:2181
1472541445407951044 [Info] Starting Offsets Storage module
1472541445441277228 [Info] Starting HTTP server
2016/08/30 15:17:25 Authenticated: id=96504282876542983, timeout=6000
1472541445516303271 [Info] Starting Zookeeper client for cluster local
2016/08/30 15:17:25 Connected to [::1]:2181
1472541445557855299 [Info] Starting Kafka client for cluster local
1472541445664837741 [Info] Starting consumers for 50 partitions of __consumer_offsets in cluster local
2016/08/30 15:17:25 Authenticated: id=96504282876542984, timeout=6000
1472541470480237689 [Info] Start email notify
1472541470583011701 [Info] Acquired Zookeeper notify lock
1472541782435539611 [Debug] Discarding group metadata message with key version 2
1472541789814717806 [Trace] Commit offset: cluster=local topic=boya.txn.detail partition=0 group=securing-kafka-group timestamp=1472541789795 offset=1745698 lag=254302
1472541789814748148 [Debug] Dropped offset (noadvance): cluster=local topic=boya.txn.detail partition=0 group=securing-kafka-group timestamp=1472541789793 offset=1745698 tsdiff=-2 lag=254302
1472541794809509527 [Trace] Commit offset: cluster=local topic=boya.txn.detail partition=0 group=securing-kafka-group timestamp=1472541794807 offset=1746216 lag=253784
1472541794812779102 [Debug] Dropped offset (mindistance): cluster=local topic=boya.txn.detail partition=0 group=securing-kafka-group timestamp=1472541794809 offset=1746216 tsdiff=2 lag=253784
1472541794812779102 [Debug] Dropped offset (mindistance): cluster=local topic=boya.txn.detail partition=0 group=securing-kafka-group timestamp=1472541794809 offset=1746216 tsdiff=2 lag=253784
1472541799812043007 [Trace] Commit offset: cluster=local topic=boya.txn.detail partition=0 group=securing-kafka-group timestamp=1472541799810 offset=1746734 lag=253266
1472541799817599261 [Debug] Dropped offset (mindistance): cluster=local topic=boya.txn.detail partition=0 group=securing-kafka-group timestamp=1472541799812 offset=1746734 tsdiff=2 lag=253266
1472541805883045978 [Trace] Commit offset: cluster=local topic=boya.txn.detail partition=0 group=securing-kafka-group timestamp=1472541805881 offset=1747511 lag=252489
1472541805889180475 [Debug] Dropped offset (mindistance): cluster=local topic=boya.txn.detail partition=0 group=securing-kafka-group timestamp=1472541805884 offset=1747511 tsdiff=3 lag=252489
1472541805889180475 [Debug] Dropped offset (mindistance): cluster=local topic=boya.txn.detail partition=0 group=securing-kafka-group timestamp=1472541805884 offset=1747511 tsdiff=3 lag=252489
1472541811922561733 [Trace] Commit offset: cluster=local topic=boya.txn.detail partition=0 group=securing-kafka-group timestamp=1472541811920 offset=1748029 lag=251971
1472541811927828519 [Debug] Dropped offset (mindistance): cluster=local topic=boya.txn.detail partition=0 group=securing-kafka-group timestamp=1472541811925 offset=1748029 tsdiff=5 lag=251971
1472541811927828519 [Debug] Dropped offset (mindistance): cluster=local topic=boya.txn.detail partition=0 group=securing-kafka-group timestamp=1472541811925 offset=1748029 tsdiff=5 lag=251971
1472541818884056427 [Trace] Commit offset: cluster=local topic=boya.txn.detail partition=0 group=securing-kafka-group timestamp=1472541818882 offset=1748806 lag=251194
1472541818889514969 [Debug] Dropped offset (mindistance): cluster=local topic=boya.txn.detail partition=0 group=securing-kafka-group timestamp=1472541818884 offset=1748806 tsdiff=2 lag=251194
1472541818889514969 [Debug] Dropped offset (mindistance): cluster=local topic=boya.txn.detail partition=0 group=securing-kafka-group timestamp=1472541818884 offset=1748806 tsdiff=2 lag=251194
1472541825874513358 [Trace] Commit offset: cluster=local topic=boya.txn.detail partition=0 group=securing-kafka-group timestamp=1472541825872 offset=1749583 lag=250417
1472541825879859784 [Debug] Dropped offset (mindistance): cluster=local topic=boya.txn.detail partition=0 group=securing-kafka-group timestamp=1472541825875 offset=1749583 tsdiff=3 lag=250417
1472541825879859784 [Debug] Dropped offset (mindistance): cluster=local topic=boya.txn.detail partition=0 group=securing-kafka-group timestamp=1472541825875 offset=1749583 tsdiff=3 lag=250417
1472541831866667875 [Trace] Commit offset: cluster=local topic=boya.txn.detail partition=0 group=securing-kafka-group timestamp=1472541831864 offset=1750360 lag=249640
1472541831872481195 [Debug] Dropped offset (mindistance): cluster=local topic=boya.txn.detail partition=0 group=securing-kafka-group timestamp=1472541831867 offset=1750360 tsdiff=3 lag=249640.........................................
`

**Comment by toddpalino** [comment]
You have not specified `auth-type` as `plain`. Therefore, Burrow is continuing to perform no authentication.

**Comment by keyboardfann** [comment]
Dear @toddpalino ,
      I set the auth-type to plain, but still don't see the mail. Should something wrong ? 

burrow.cfg
[smtp]
server=aspmx.l.google.com
port=25
auth-type="plain"
username=keyboardfann
password=xxxxxx
from=keyboardfann@gmail.com
template=./default-email.tmpl


burrow.out
[root@burrow bin]# tailf burrow.out
1472627416407485794 [Info] Starting Offsets Storage module
2016/08/31 15:10:16 Authenticated: id=96508836887134300, timeout=6000
1472627416665677736 [Info] Starting HTTP server
1472627416923877779 [Info] Starting Zookeeper client for cluster local
2016/08/31 15:10:17 Connected to 127.0.0.1:2181
1472627417098737553 [Info] Starting Kafka client for cluster local
2016/08/31 15:10:17 Authenticated: id=96508836887134301, timeout=6000
1472627417103746180 [Info] Starting consumers for 50 partitions of __consumer_offsets in cluster local
1472627441945527013 [Info] Start email notify
1472627441990427586 [Info] Acquired Zookeeper notify lock
1472627515768577556 [Debug] Discarding group metadata message with key version 2
1472627516223486693 [Debug] Discarding group metadata message with key version 2
1472627516223486693 [Debug] Discarding group metadata message with key version 2
1472627516558135939 [Trace] Commit offset: cluster=local topic=boya.txn.detail partition=0 group=securing-kafka-group timestamp=1472627516216 offset=0 lag=0
1472627522265300098 [Debug] Discarding group metadata message with key version 2
1472627527119928966 [Trace] Commit offset: cluster=local topic=boya.txn.summary partition=0 group=securing-kafka-group timestamp=1472627527117 offset=3000325 lag=0
1472627527269220340 [Debug] Dropped offset (mindistance): cluster=local topic=boya.txn.summary partition=0 group=securing-kafka-group timestamp=1472627527267 offset=3000325 tsdiff=150 lag=-589664
1472627532119046473 [Trace] Commit offset: cluster=local topic=boya.txn.summary partition=0 group=securing-kafka-group timestamp=1472627532115 offset=3000325 lag=0
1472627532270774522 [Debug] Dropped offset (mindistance): cluster=local topic=boya.txn.summary partition=0 group=securing-kafka-group timestamp=1472627532268 offset=3000325 tsdiff=153 lag=-589664
1472627537118781659 [Trace] Commit offset: cluster=local topic=boya.txn.summary partition=0 group=securing-kafka-group timestamp=1472627537115 offset=3000325 lag=0
1472627537270785261 [Debug] Dropped offset (mindistance): cluster=local topic=boya.txn.summary partition=0 group=securing-kafka-group timestamp=1472627537268 offset=3000325 tsdiff=153 lag=0
1472627542117977090 [Trace] Commit offset: cluster=local topic=boya.txn.summary partition=0 group=securing-kafka-group timestamp=1472627542115 offset=3000325 lag=0
1472627542270308227 [Debug] Dropped offset (mindistance): cluster=local topic=boya.txn.summary partition=0 group=securing-kafka-group timestamp=1472627542268 offset=3000325 tsdiff=153 lag=0
1472627542270308227 [Debug] Dropped offset (mindistance): cluster=local topic=boya.txn.summary partition=0 group=securing-kafka-group timestamp=1472627542268 offset=3000325 tsdiff=153 lag=0
1472627547119892769 [Trace] Commit offset: cluster=local topic=boya.txn.summary partition=0 group=securing-kafka-group timestamp=1472627547116 offset=3000325 lag=0
1472627547270596696 [Debug] Dropped offset (mindistance): cluster=local topic=boya.txn.summary partition=0 group=securing-kafka-group timestamp=1472627547268 offset=3000325 tsdiff=152 lag=0
1472627551402664210 [Trace] Commit offset: cluster=local topic=boya.txn.summary partition=0 group=securing-kafka-group timestamp=1472627551399 offset=3000325 lag=0
1472627551408535679 [Debug] Discarding group metadata message with key version 2
1472627551408535679 [Debug] Discarding group metadata message with key version 2
1472627662107715522 [Debug] Discarding group metadata message with key version 2
1472627666946533575 [Trace] Commit offset: cluster=local topic=boya.txn.summary partition=0 group=securing-kafka-group timestamp=1472627666944 offset=3003013 lag=2098255
1472627667331892650 [Debug] Dropped offset (mindistance): cluster=local topic=boya.txn.summary partition=0 group=securing-kafka-group timestamp=1472627667068 offset=3003013 tsdiff=124 lag=2098255
1472627674919729297 [Trace] Commit offset: cluster=local topic=boya.txn.summary partition=0 group=securing-kafka-group timestamp=1472627674918 offset=3004805 lag=2096463
1472627674921868544 [Debug] Dropped offset (mindistance): cluster=local topic=boya.txn.summary partition=0 group=securing-kafka-group timestamp=1472627674919 offset=3004805 tsdiff=1 lag=2096463
1472627680054295781 [Trace] Commit offset: cluster=local topic=boya.txn.summary partition=0 group=securing-kafka-group timestamp=1472627680052 offset=3008389 lag=2092879
1472627680058344870 [Debug] Dropped offset (mindistance): cluster=local topic=boya.txn.summary partition=0 group=securing-kafka-group timestamp=1472627680054 offset=3008389 tsdiff=2 lag=2092879
1472627685133548931 [Trace] Commit offset: cluster=local topic=boya.txn.summary partition=0 group=securing-kafka-group timestamp=1472627685131 offset=3011973 lag=2089295
1472627685135665095 [Debug] Dropped offset (mindistance): cluster=local topic=boya.txn.summary partition=0 group=securing-kafka-group timestamp=1472627685133 offset=3011973 tsdiff=2 lag=2089295
1472627690968550783 [Trace] Commit offset: cluster=local topic=boya.txn.summary partition=0 group=securing-kafka-group timestamp=1472627690967 offset=3015557 lag=2085711
1472627690971370732 [Debug] Dropped offset (mindistance): cluster=local topic=boya.txn.summary partition=0 group=securing-kafka-group timestamp=1472627690968 offset=3015557 tsdiff=1 lag=2085711
1472627696631931880 [Trace] Commit offset: cluster=local topic=boya.txn.summary partition=0 group=securing-kafka-group timestamp=1472627696630 offset=3018245 lag=2083023
1472627696635425790 [Debug] Dropped offset (mindistance): cluster=local topic=boya.txn.summary partition=0 group=securing-kafka-group timestamp=1472627696632 offset=3018245 tsdiff=2 lag=2083023
1472627702664362074 [Trace] Commit offset: cluster=local topic=boya.txn.summary partition=0 group=securing-kafka-group timestamp=1472627702662 offset=3021829 lag=2079439
1472627702676127659 [Debug] Dropped offset (mindistance): cluster=local topic=boya.txn.summary partition=0 group=securing-kafka-group timestamp=1472627702675 offset=3021829 tsdiff=13 lag=2079439
1472627708515509825 [Trace] Commit offset: cluster=local topic=boya.txn.summary partition=0 group=securing-kafka-group timestamp=1472627708513 offset=3025413 lag=2075855
1472627708523764410 [Debug] Dropped offset (mindistance): cluster=local topic=boya.txn.summary partition=0 group=securing-kafka-group timestamp=1472627708515 offset=3025413 tsdiff=2 lag=2075855
