### ISSUE TITLE
Unexplained Error Status

### ISSUE THREAD

**Issue by 326TimesBetter** [linkedin/Burrow#123]
We have been running burrow and publishing its logs into kibana, where we are using a tool called elastalert to alert off of them. However, we are getting what appear to me to be a number of false positives that I do not understand. Here are two examples:

![image](https://cloud.githubusercontent.com/assets/16246896/18009589/ed61520e-6b7a-11e6-8abf-48e8f51f54fe.png)

The first row is an example of a log that seems to have had a few logs come in over the time window, and has consumed them (because end log lag is zero).

The second row is an example of a log which has had no logs come in over the time window, but remains caught up at end_log_lag zero.

Yet both of these  appear to have a status of "ERR".  By the first rule in your "Consumer Lag Evaluation Section":`If any lag within the window is zero, the status is considered to be OK.
`, shouldn't these rows be marked status: ok ??

Here are the full log lines produced by burrow:

    2016/08/26 14:34:48 ;source_timestamp=2016-08-26T14:34:48Z;cluster=local;consumer_group=cd-changeevent-consumer;error=false;status=ERR;complete=true;lag_type=Partition;topic=directory-users-processed;partition=0;partition_status=STOP;start_log_offset=124848;start_log_timestamp=1469311346327;start_log_lag=0;end_log_offset=124857;end_log_timestamp=1469311386135;end_log_lag=0;

    2016/08/26 14:34:48 ;source_timestamp=2016-08-26T14:34:48Z;cluster=local;consumer_group=cd-changeevent-consumer;error=false;status=ERR;complete=true;lag_type=Partition;topic=directory-orgunits-change-feed;partition=0;partition_status=OK;start_log_offset=23;start_log_timestamp=1472219388000;start_log_lag=0;end_log_offset=23;end_log_timestamp=1472222088000;end_log_lag=0;

Why might this happen??

Thank you!!

**Comment by 326TimesBetter** [comment]
If a consumer evaluates to ERR on a PARTICULAR topic, say, for instance, one that it consumed from a long time ago, but has since been decomissioned, will that error status stick to the consumer group, even if it is consuming from other topics correctly??

**Comment by toddpalino** [comment]
So those consumers are marked as ERR because they are stopped for at least one partition. That means that they have not committed an offset at all for an extended period of time. The lag for a consumer's partition is calculated on offset commit, so it's entirely possible that the current broker offset is ahead of the last committed offset, and therefore there is lag. This is a problem with the current method of calculating lag.

And yes, if there is a problem with a single partition, then the consumer group is in a bad state.

**Comment by 326TimesBetter** [comment]
Hmm well in the case that we have decomissioned a topic that we once consumed from, is there a way to reset our consumer group such that burrow no longer looks at those topics?? It will always be marked stopped on partitions in those topics, because we no longer use them :/

**Comment by toddpalino** [comment]
Yes, you can use the API to delete the consumer group from Burrow. If the consumer is active, it will immediately be recreated and start populating lag information again with only the topics that it is currently consuming.
