### ISSUE TITLE
Calculate lag at request time, not commit time

### ISSUE THREAD

**Issue by toddpalino** [linkedin/Burrow#127]
The original design of Burrow focused on consumer group status indicators, not lag. As such, the lag values that are stored are stored with the offset commit tuple (timestamp, offset, lag), and they are calculated at the time of the offset commit. Now that it's obvious that the lag numbers that are available in Burrow are useful along with the status, this is causing confusion because a stopped consumer can show zero lag (as the lag is not calculated).

There are performance, as well as accuracy, concerns if we were to switch all the lag calculations to be at broker offset update time instead. As such, I don't think it's the right choice to make that change.

One easy way to solve this is to provide a new value in the PartitionStatus struct for current lag. This could be calculated at request time (when the group status is evaluated), and would also be used for the total lag calculation. The documentation for max lag can also be changed to clearly state that it is the lag for the currently active partition which is the furthest behind.

**Comment by davispw** [comment]
If #140 might indeed be due to timing of refreshing broker offsets, wondering if this could extend to calculating STOPPED status as well.

**Comment by petergaultney** [comment]
This seems necessary to me. The lag number is a crucial part of many monitoring setups, and simply not calculating it because a consumer has not committed an offset is dangerously misleading. 

@toddpalino, would you be willing to go ahead and add this since you already know the codebase? I am happy to try to do so myself, but I'm less likely to get it right the first time.

**Comment by felipejfc** [comment]
up

**Comment by toddpalino** [comment]
Addressing this in the 1.0 rewrite. I have seen the error of my ways :)

**Comment by toddpalino** [comment]
Resolved by 1.0 rewrite
