### ISSUE TITLE
Consumer Lag Evaluation Issue

### ISSUE THREAD

**Issue by 326TimesBetter** [linkedin/Burrow#128]
I'm sorry I'm still trying to understand some of the consumer lag evaluation rules, as we are seemingly still getting some burrow results of status: ERR and partition_status: STOP when our consumers are functioning.

Rule # 4 says: `If the difference between the time now and the time of the most recent offset is greater than the difference between the most recent offset and the oldest offset in the window, the consumer is in an ERROR state and the partition is marked as STOPPED. However, if the consumer offset and the current broker offset for the partition are equal, the partition is not considered to be in error.`

If I am reading this correctly, it is possible to trigger rule number 4 and receive "status: ERR" and "partition_status: STOP", and it doesn't NECESSARILY mean that your consumer is in error (in the case where broker_offset=consumer_offset)?? Perhaps it is still functioning, and just hasn't seen any new messages committed for a while?? Is my interpretation correct?

Is there a way I can make that comparison (consumer_offset vs broker_offset) so that I can rule out these cases??

**Comment by toddpalino** [comment]
As stated in that doc, if the current committed offset and the broker offset are the same, then the partition won't be marked as stopped. This means that if there are no messages coming in, the consumer won't be in a bad state. The last line is intended to say that Burrow will not mark the partition as STOPPED in this case.
