### ISSUE TITLE
Some partitions not reporting lag

### ISSUE THREAD

**Issue by rkling01** [linkedin/Burrow#129]
Hi,

I'm seeing a situation where when I run a "lag" api check on a particular consumer group one or more partitions aren't coming back in the response.   I've been investigating for awhile trying to come up with a pattern.  We do have a mix of 0.8 and 0.9 consumers in our clusters.  

For example, I've got a 5 partition topic and partitions 1,2,3,4 do return but the 0 partition does not.  Running the kafka-consumer-offset-checker.sh does report back all the partitions in this particular situation.

In another example a 5 partition topic reported back 3 partitions that didn't have lag and the kafka-consumer-offset-checker.sh showed all 5 and the two partitions that weren't reporting in the lag api call showed lag numbers using kafka-consumer-offset-checker.sh . 

Just trying to understand the behavior I'm seeing and wondering if there are any limitations or situations where I might see these types of results.

Thanks!

**Comment by sanear** [comment]
+1
I am seeing the same behavior, but with a simpler setup - only 0.8 consumers committing to zookeeper. Kafka consumer offset checker reports 3 partitions each lagging by 34, but I get this response from Burrow:

    {"error":false,"message":"consumer group status returned","status":
        {"cluster":"datastreams","group":"find_delivery","status":"OK","complete":false,"partitions":
        [],"partition_count":3,"maxlag":null,"totallag":0},
    "request":
        {"url":"/v2/kafka/datastreams/consumer/find_delivery/lag","host":"ip-10-201-2-14","cluster":"datastreams","group":"find_delivery","topic":""}
    }

**Comment by toddpalino** [comment]
@sanear - The problem you're running into is indicated by `"complete": false,` in the response. There aren't enough offset commits for the status to be calculated. In the default Burrow config, 10 offset commits are required for all partitions consumed by a group in order to have a complete picture of the group status. When `complete` is set to false, you can't trust what's coming back yet.

**Comment by toddpalino** [comment]
@rkling01 - Can you provide the output from some status calls to Burrow so we can see if the issue is the same?

**Comment by rkling01** [comment]
@toddpalino sorry for the delay.  I believe the issue may have indeed been similar to the above where a full cycle of offsets hadn't been collected yet.   Will close this one.  Thanks!
