### ISSUE TITLE
No support for deleting topics

### ISSUE THREAD

**Issue by toddpalino** [linkedin/Burrow#13]
The support for deleted topics is marginal at best. The Kafka client should refresh metadata periodically and if it finds a topic has been deleted, all traces of it should be removed (both from broker offsets and any consumers that have been consuming it)

**Comment by jsvisa** [comment]
@toddpalino I'll start with this PR.

**Comment by toddpalino** [comment]
This is a major driver behind the 1.0 rewrite.

**Comment by toddpalino** [comment]
Resolved by 1.0 rewrite
