### ISSUE TITLE
Email is not sending

### ISSUE THREAD

**Issue by panda87** [linkedin/Burrow#130]
Hi

Im using burrow for long time and couple of days ago I wanted to make a few changes in the burrow.cfg file and also see how the slack notifications works.

Im working with docker containers and I once I made the change I built new version, probably with the latest merges, fortunately the Slack notifier working as expected but the emails stopped from sending. Im using the same configuration but changed from "email" to "emailnotifier".

Attach below my configurations,

```
[general]
logdir=log
logconfig=config/logging.cfg
pidfile=burrow.pid
client-id=burrow-lagchecker
group-whitelist=test

[zookeeper]
hostname=qa.zookeeper.service.xxx.internal
port=2181
timeout=6
lock-path=/burrow/notifier

[kafka "qa"]
broker=qa.kafka.service.xxx.internal
broker-port=9092
zookeeper=qa.zookeeper.service.xxx.internal
zookeeper-port=2181
zookeeper-path=/
offsets-topic=__consumer_offsets
zookeeper-offsets=true

[tickers]
broker-offsets=60

[lagcheck]
intervals=10
expire-group=604800
min-distance=1
zookeeper-interval=60
zk-group-refresh=300

[httpserver]
server=on
port=8000

[smtp]
server=email-smtp.us-west-2.amazonaws.com
port=587
auth-type=plain
username=XXX
password=XXX
from=burrow-noreply@xxx.com
template=config/default-email.tmpl

[emailnotifier "david@xxx.com"]
group=qa,test
interval=60

[notify]
interval=60

[slacknotifier]
enable=true
url=https://hooks.slack.com/services/XXX/XXXX
group=qa,test
threshold=2
channel="#kafka-lag"
username=burrower
interval=5
timeout=5
keepalive=30
```

Does someone can take a look and let me know where Im wrong?

Thanks in advance
D.

**Comment by edvorkin** [comment]
I have the same issue apparently. Old version used to work with "email". Is there a way to test email notification functionality? Any build in test scripts?

**Comment by chornyi** [comment]
I can confirm this. Rolling back to `0.1.1` helped.

**Comment by joellundell** [comment]
I faced the same issue and from looking at the code in notify_center.go it seems like enable=true has to be set for each notifier for emails to work. Adding that worked for me. I updated the wiki with that information. A better solution might be to default enable to true and change wiki to describe a way of disabling an email notifier instead.

```
func NewEmailNotifier(app *ApplicationContext) ([]*notifier.EmailNotifier, error) {
	log.Info("Start email notify")
	emailers := []*notifier.EmailNotifier{}
	for to, cfg := range app.Config.Emailnotifier {
		if cfg.Enable {
			emailer := &notifier.EmailNotifier{
				Threshold:    cfg.Threshold,
				TemplateFile: app.Config.Smtp.Template,
				Server:       app.Config.Smtp.Server,
				Port:         app.Config.Smtp.Port,
				Username:     app.Config.Smtp.Username,
				Password:     app.Config.Smtp.Password,
				AuthType:     app.Config.Smtp.AuthType,
				Interval:     cfg.Interval,
				From:         app.Config.Smtp.From,
				To:           to,
				Groups:       cfg.Groups,
			}
			emailers = append(emailers, emailer)
		}
	}

	return emailers, nil
}
```
