### ISSUE TITLE
Lag Not Being Reported

### ISSUE THREAD

**Issue by cgosiak** [linkedin/Burrow#131]
I am hoping this is my simple misunderstanding; but Burrow does not seem to be reporting lag for almost any of my topics. I am attempting to test out the Alerting system I have built, so I have created a tool to create excess lag on a Kafka topic to try and catch it with Burrow. However, it seems that Burrow is not catching these excess spikes in lag at all; and seems to consistently report an "OK" status.

I have 4 producers writing to a single topic, and am pausing the consumer frequently to consistently increase lag. Using the console tools included with Kafka I can see the lag growing.

Also, my window is: 
- 10 Intervals
- 60sec min-distance
This would lead me to believe that after 10 mins of lag growing; the alert should take place?
Does a consumer need to be consistently committing offsets in this time frame? Or would Burrow still catch lag growing if there are no active consumers; but there is a producer still sending messages?

If I am misunderstanding how Burrow monitors the actual lag; could someone please explain it to me?

**Comment by panda87** [comment]
Are you using email notifier?

**Comment by cgosiak** [comment]
No, I am using the HTTP Notifier; with the following setup in the config.

[tickers]
broker-offsets=60

[lagcheck]
intervals=10
min-distance=60
expire-group=604800

[httpserver]
server=on
port=44444

[notify]
interval=60

[httpnotifier]
url=https://my.website.here/api/alerts
interval=60

**Comment by toddpalino** [comment]
I believe your understanding of `min-distance` is incorrect. This governs the minimum amount of time allowed between offset commits. So in your config, if your consumer commits offsets every 10 seconds, only every 6th commit will be recorded by Burrow. I don't think this is what you want. In general, I would leave `min-distance` set to 1, which reduces a little bit of churn and problems with ZK offset commits.

Your consumer must commit 10 offsets for all partitions in order for status checking to be working in Burrow. It will only show accurate lag for active consumers. Once a consumer is reporting, if you stop it it will show up in the STOPPED state after some amount of time.

**Comment by cgosiak** [comment]
Looks good to me! Thank you for the further explanation.
