### ISSUE TITLE
crash - panic: runtime error: index out of range

### ISSUE THREAD

**Issue by iamnoah** [linkedin/Burrow#137]
Burrow is dying when run against a Kafka 0.10 cluster:

```
2016-09-06 19:28:47 [INFO] Starting Kafka client for cluster dev
2016-09-06 19:28:48 [INFO] Starting consumers for 50 partitions of __consumer_offsets in cluster dev
panic: runtime error: index out of range

goroutine 32263 [running]:
panic(0x7e5aa0, 0xc4200140c0)
       	/usr/local/go/src/runtime/panic.go:500 +0x1a1
main.(*OffsetStorage).addBrokerOffset(0xc4200fe040, 0xc420d808c0)
       	/go/src/github.com/linkedin/Burrow/offsets_store.go:176 +0x2ae
created by main.NewOffsetStorage.func1
       	/go/src/github.com/linkedin/Burrow/offsets_store.go:123 +0x11d
```

Some topics were recently deleted and recreated with fewer partitions, but otherwise it's a pretty typical cluster.

**Comment by iamnoah** [comment]
FWIW, after ~20 hours I was able to restart Burrow without an error. I'm going to guess consumer offsets for no longer existent partitions were to blame.

**Comment by toddpalino** [comment]
Yeah, there's an issue open for Burrow not supporting deleted topics properly. Unfortunately, that's what you hit.
