### ISSUE TITLE
Error: Partition for a topic for a consumer group is not an integer

### ISSUE THREAD

**Issue by nishant221** [linkedin/Burrow#138]
Consumers are storing offsets for a topic for various partition where the partitions are in the form of <BrokerId>-<Partition_number> . Since "-" is present hence error is generated while converting it to integer.

Error is of the form -:

Partition (14578-0) for topic testtopic for group consgrp in cluster testcluster is not an integer

**Comment by toddpalino** [comment]
Partitions in Kafka do not have dashes - they are integers. This sounds like an error in the consumer committing offsets.
