### ISSUE TITLE
Partition incorrectly reported as STOPPED

### ISSUE THREAD

**Issue by jojijohn** [linkedin/Burrow#140]
I am using burrow to monitor consumers which manually commit the offsets. 
Here are some of the configs:
[tickers]
broker-offsets=60

[lagcheck]
intervals=300
expire-group=604800

I am running into this issue where burrow is reporting a partition to be stopped. Based on the docs, the only scenario burrow would report a consumer to be in STOPPED status is when:
_If the difference between the time now and the time of the most recent offset is greater than the difference between the most recent offset and the oldest offset in the window, the consumer is in an ERROR state and the partition is marked as STOPPED. However, if the consumer offset and the current broker offset for the partition are equal, the partition is not considered to be in error._
<img width="374" alt="lag" src="https://cloud.githubusercontent.com/assets/8701433/18622860/6125e17e-7e03-11e6-9f05-5ced36e3af99.png">

The oldest offset time was 18 Sep 2016 10:24:36 GMT
The most recent offset time was 18 Sep 2016 10:52:06 GMT
The time difference between the most recent and the oldest offsets being 28 minutes.
The error was reported at 18 Sep 2016 11:21:00 GMT
The time difference between time now and the most recent offsets being 29 minutes.
The first condition of the rule was definitely violated based on these numbers, however the broker offset and the consumer offset was the same when the error was reported (294068).

<img width="1147" alt="broker_offset_recent" src="https://cloud.githubusercontent.com/assets/8701433/18622887/ed42cf14-7e03-11e6-834c-90570c293f95.png">

I am not sure why burrow would report an error in this case since the consumer and broker offsets are the same.

**Comment by davispw** [comment]
Is there a timing issue with refreshing broker offsets?  I'm seeing this intermittently on low-throughput topics.  Wondering if there is a brief race condition after a new message is published between 1) Burrow happens to refresh broker offsets and 2) Burrow gets updated consumer offset from __consumer_offsets topic.  By the time I go check the offsets myself, all is up to date.

**Comment by toddpalino** [comment]
Closing this out as there are a number of fixes related to this behavior that have gone in since then. I'll also be updating the way lag is calculated in the rewrite to make it easier to use.
