### ISSUE TITLE
De-duping of error messages

### ISSUE THREAD

**Issue by jojijohn** [linkedin/Burrow#141]
Is there any mechanism in burrow to prevent the same error message from being posted twice to my HTTP alerting endpoint. I see that there is an id associated with each alert, but not sure how to use it for de-duping the messages

2016-09-19 11:25:45 [DEBUG] Sent POST for group my-group in cluster my-kafka-cluster at severity ERR (Id 69cc01e5-80f0-4281-8522-4efa330853c5)

**Comment by toddpalino** [comment]
The ID is how you should deduplicate the messages. Burrow will send out a message as often as you configure it to check status (the `interval` config in the `httpnotifier` section). The same ID should be provided for one "incident" - that is, if the consumer group is good, then it is bad for 10 minutes, then it is good again, then it is bad again for 10 minutes, you will see only 2 IDs - one for the first 10 minute bad period, and a different one for the second 10 minute bad period.

You should use that ID in the external system you're reporting to to be able to determine unique incidents.
