### ISSUE TITLE
Email notifier interval settings is not honored

### ISSUE THREAD

**Issue by joellundell** [linkedin/Burrow#142]
Hi,

I can't get the interval working for email notifiers. I've set the interval to 300 seconds but it still sends out an email every 10 seconds. Could something else affect that setting? I've tried playing around with the broker-offsets but that didn't affect it. These are the settings I've been using minus the identifying information.

Thank you so much for any help I could get!

```
[general]
logconfig=./logging.cfg

[zookeeper]
hostname=some host
port=2181
timeout=6
lock-path=/burrow/notifier

[kafka "some cluster"]
broker=some broker
broker-port=9092
zookeeper=some zookeeper
zookeeper-port=2181
zookeeper-path=/some path
zookeeper-offsets=true
offsets-topic=__consumer_offsets

[tickers]
broker-offsets=300

[lagcheck]
intervals=10
expire-group=604800
min-distance=1
zookeeper-interval=60
zk-group-refresh=300

[httpserver]
server=on
port=8990

[smtp]
server=some server
port=587
auth-type=plain
username=some user
password="some password"
from=burrow@somedomain.com
template=./email.tmpl

[emailnotifier "some email"]
group=clusterFoo,consumerBar
interval=300
enable=true
```

**Comment by joellundell** [comment]
Found it. 

Need to add a section like this that controls notification interval on a global level I would assume:
```
[notify]
interval=300
```
Removing the interval from the emailnotifier causes burrow to not start so not sure if you want to close the issue or not.

**Comment by daodennis** [comment]
@joellundell do you remember what the interval is used for in the `emailnotifier` stanza by chance?

**Comment by joellundell** [comment]
@daodennis it's been a while since I touched this and I've changed company since but if memory serves me right it's ignored. It only looks at the interval under the notify section per my comment above.
