### ISSUE TITLE
No topics or consumers but logs mention them

### ISSUE THREAD

**Issue by nickwales** [linkedin/Burrow#143]
I've got burrow up and working in our local datacenter but with similar configuration in EC2 it won't find any topics or consumers. The debug log has 'Dropped offset (no topic)' whenever it looks up zookeeper or kafka offsets:

*we're using consul DNS to look up the kafka and zookeeper clusters. This must be working because the zookeeper filesystem has entries in /burrow/notifier. Also I've hand checked multiple times.

Configuration file:

```
[general]
logdir=/var/log/
logconfig=/etc/burrow/logging.cfg
pidfile=burrow.pid
client-id=burrow-lagchecker
group-blacklist=^(console-consumer-|python-kafka-consumer-).*$

[zookeeper]
port=2181
timeout=6
lock-path=/burrow/notifier
hostname=zookeeper.service.consul

[kafka "us-east-1-vpc-4f6cdb28"]
broker-port=9092
zookeeper-port=2181
zookeeper-path=/
offsets-topic=__consumer_offsets
zookeeper-offsets=true
broker=kafka.service.consul
zookeeper=zookeeper.service.consul

[tickers]
broker-offsets=60

[lagcheck]
intervals=10
expire-group=604800

[httpserver]
server=on
port=8000
```

The logs mention topics and consumers that exist regularly but are all dropped. I'm happily consuming data from this kafka cluster with other libraries. 

```
2016-09-26T19:54:27Z [DEBUG] Dropped offset (no topic): cluster=us-east-1-vpc-4f6cdb28 topic=esot-instance-events partition=0 group=instance-archival-agent-us-east-1-vpc-4f6cdb28-production timestamp=1474919667534 offset=275450
2016-09-26T19:54:32Z [DEBUG] Get ZK offsets for group config_consumer_us-east-1-vpc-fcb4089b in cluster us-east-1-vpc-4f6cdb28
2016-09-26T19:54:32Z [DEBUG] Dropped offset (no topic): cluster=us-east-1-vpc-4f6cdb28 topic=esot-instance-events partition=0 group=config_consumer_us-east-1-vpc-fcb4089b timestamp=1469106167887 offset=234370
```

The kafka version is 0.10.0

**Comment by toddpalino** [comment]
The topic list is retrieved from the Kafka cluster via the client that is instantiated. The offsets appear to be coming from ZK, so that is done using a separate Zookeeper client. My guess is that the Zookeeper at zookeeper.service.consul:2181 does not match the Kafka cluster at kafka.service.consul:9092.

Can you confirm whether or not the topic `esot-instance-events` exists in the cluster pointed to by kafka.service.consul:9092 ?

**Comment by nickwales** [comment]
There are mixed offset storage systems currently, some kafka some ZK. The first in the above example is kafka the second ZK. 

I can confirm that the esot-instance-events is in the cluster:

```
kafka-topics --zookeeper zookeeper.service.consul:2181 --describe | grep esot-instance-events
Topic:esot-instance-events	PartitionCount:1	ReplicationFactor:3	Configs:min.insync.replicas=2,cleanup.policy=compact,segment.ms=300000
	Topic: esot-instance-events	Partition: 0	Leader: 1009	Replicas: 1009,1015,1016	Isr: 1009,1015,1016
```

**Comment by fracklen** [comment]
I have the same problem. I can see that consumer offsets are stored in ZK just fine. 

Sidenote:
Shouldn't Burrow use the Kafka client to query for both producer and consumer offsets? Whatever backend Kafka uses to store the offsets should not be a concern of tools as Burrow?

**Comment by k1ng87** [comment]
Same issue here....I see offsets in the log file but when I hit the API, I get no consumer groups or topics back...

**Comment by k1ng87** [comment]
Did this get fixed? Or a solution to this? I'm getting the same issue...

**Comment by k1ng87** [comment]
So I think its coming from this...

https://github.com/linkedin/Burrow/blob/d2c71bc6447ae8e94ee1b1674473774463d8f5ff/offsets_store.go#L211

Sounds like it logs that message if it can't pull the log end offset for that topic but its getting the commit offset from `___coonsumer_offsets`

Is this an ACL issue maybe?

I've set read and describe to all topics from any user from the burrow IP address though...

**Comment by rs857c** [comment]
hi K1ng87, which kafka version were using for this ? can you pls help to know where to use the "cert" created for super user in this to validate?

**Comment by rs857c** [comment]
Interesting this issue got fixed by adding zookeeper-offsets=true property
https://github.com/linkedin/Burrow/issues/80
