### ISSUE TITLE
Not able to find any consumer group. Kafka version 0.10.0

### ISSUE THREAD

**Issue by Navneet23** [linkedin/Burrow#144]
I am getting the following response when I hit  /v2/kafka/local/consumer:

{
  "error": false,
  "message": "consumer list returned",
  "consumers": [],
  "request": {
    "url": "/v2/kafka/local/consumer",
    "host": "EN-NavneetJ",
    "cluster": "local",
    "group": "",
    "topic": ""
  }
}
My config file is below:
![image](https://cloud.githubusercontent.com/assets/11739873/18944103/18c146b2-8641-11e6-97be-f9c6699ce30b.png)

when I run  bin/kafka-consumer-groups.sh --list --zookeeper localhost:2181
I get the following consumer groups..

console-consumer-98785
console-consumer-1054
console-consumer-70637
console-consumer-69177
console-consumer-16166
console-consumer-62362
console-consumer-24827
console-consumer-12034
console-consumer-72951

Why am I not able to get this list in burrow.

Also I am not able to get lag or other details for these consumer groups on burrow.

Can I get some help?

**Comment by toddpalino** [comment]
Check in Zookeeper (under the `/consumers/console-consumer-98785` path, for example). Burrow will skip any groups in Zookeeper that do not have an `offsets` znode. Burrow does not list all consumer groups, only the consumer groups that are committing offsets.

**Comment by tanbansa** [comment]
Does it mean, burrow supports only "old consumers" not "new consumer" of kafka?

**Comment by DavidLiuXh** [comment]
The default value of the zookeeper-offsets  is false.

**Comment by toddpalino** [comment]
OK, so this is probably just because either those console consumers are not committing offsets, or they are committing offsets to Zookeeper and you're not reading that. Burrow does not list all consumer groups. It lists all groups that commit offsets.

**Comment by JarenGlover** [comment]
>OK, so this is probably just because either those console consumers are not committing offsets, or they are committing offsets to Zookeeper and you're not reading that. Burrow does not list all consumer groups. It lists all groups that commit offsets.

@toddpalino is it fair to say that the Kafka tool `kafka-console-consumer.sh` doesn't commit offsets to zookeeper? Therefore that is why Burrow doesn't recognize it? 

> The default value of the zookeeper-offsets is false.

@DavidLiuXh are you referring to the setting under `kafka` setting of the burrow.cfg? if so, not sure what that means in this context. 

thanks.

**Comment by toddpalino** [comment]
Another note, you've omitted the `[general]` section from the config file you posted. I'm not sure if this is because you're not specifying it, or if you omitted it from what you posted for other reasons, but normally there is a group blacklist config that includes console consumers.

And yes, David is referring to under the `kafka` section of the config. If you do not explicitly set `zookeeper-offsets` to true, Burrow will not check Zookeeper committed offsets.
