### ISSUE TITLE
Consumer group in warning state with no problems

### ISSUE THREAD

**Issue by dtjm** [linkedin/Burrow#145]
My email notifications are firing saying my consumer groups are in WARNING status, but also says 0 partitions have problems:

```
The Kafka consumer groups you are monitoring are currently showing problems. The following groups are in a problem state (groups not listed are OK):

Cluster:  cluster1
Group:    consumer1
Status:   WARNING
Complete: false
Errors:   0 partitions have problems


----------------------------------------------------------------------
Cluster:  cluster1
Group:    consumer2
Status:   WARNING
Complete: false
Errors:   0 partitions have problems
```

Is this intended behavior? I would expect them to be in a OK state at this point.  How do I debug this?

**Comment by tanuj83** [comment]
I also facing same issue, and once checking /v2/kafka/cluster/consumer/group1/status/ it shows OK always.  

consumer auto commit is 5 sec 
Kafka Consumer 0.9
Kafka Broker 0.9
and here is the config

`
[general]
logdir=log
logconfig=config/logging.cfg
pidfile=burrow.pid
client-id=burrow-lagchecker
group-blacklist=^(console-consumer-|python-kafka-consumer-).*$

[zookeeper]
hostname=server11.example.com
hostname=server12.example.com
hostname=server13.example.com
port=2181
timeout=120
lock-path=/burrow/notifier

[kafka "cluster1"]
broker=server1.example.com
broker=server2.example.com
broker=server3.example.com
broker=server4.example.com
broker-port=9092
zookeeper=server2.example.com
zookeeper=server3.example.com
zookeeper=server4.example.com
zookeeper-port=2181
zookeeper-path=/
offsets-topic=__consumer_offsets



[tickers]
broker-offsets=60

[lagcheck]
intervals=10
expire-group=604800
min-distance=1
zookeeper-interval=60
zk-group-refresh=300

[httpserver]
server=on
port=443



[smtp]
server=localhost
port=25
from=myid@example.com
template=config/default-email.tmpl

[emailnotifier "myid@example.com"]
group=cluster1,topic1
interval=3600
enable=true

[notify]
interval=600`

**Comment by tanuj83** [comment]
Tried to increase the interval and change zookeeper-interval but burrow keeps sending warning alarms.
My consumer goes negative count 1-2 times out of 15 refresh (checked on kafka-manager) but why it is keep sending warning, not considering it OK when it is -ve 

How can we avoid such case?

**Comment by pliljenberg** [comment]
I think it's a configuration issue (and missing documentation about the configuation).
You've not set any value for ``threshold`` for the email-notifier thus making the value ``0``.
The following [code](https://github.com/linkedin/Burrow/blob/b6c9dad4c0237c166d80a41a208d628e4e2635ed/notifier/email_notifier.go#L81-L83) is used to check if the notification should be sent or not:

```
func (emailer *EmailNotifier) Ignore(msg Message) bool {
	return int(msg.Status) < emailer.Threshold
}
```

Since `emailer.Threshold=0` every notification will be sent regardless of the [status](https://github.com/linkedin/Burrow/blob/9097d701ce1f5b09a4087c950b1a03c667aca7ab/protocol/protocol.go#L36-L44) of the message.
```
const (
	StatusNotFound StatusConstant = 0
	StatusOK       StatusConstant = 1
	StatusWarning  StatusConstant = 2
	StatusError    StatusConstant = 3
	StatusStop     StatusConstant = 4
	StatusStall    StatusConstant = 5
	StatusRewind   StatusConstant = 6
)
```

Change your configuration to:
```
[emailnotifier "myid@example.com"]
group=cluster1,topic1
interval=3600
enable=true
threshold=2
```

And only messages with Warning or above will be sent.
[Documentation](https://github.com/linkedin/Burrow/wiki/Email-Notifier#email-notifier-configuration) should be updated accordingly, not sure if I have permission to edit the page in question...

**Comment by tanuj83** [comment]
Thank you @pliljenberg 
Looks like [default-email.tmpl](https://github.com/linkedin/Burrow/blob/master/config/default-email.tmpl) also needs to be updated.

 {{if eq 1 .Status}} WARN{{else if eq 2 .Status}}  ERR{{else if eq 3 .Status}} STOP{{else if eq 4 .Status}}STALL{{end}}

**Comment by tanuj83** [comment]
@pliljenberg The threshold works good but if using multiple cluster/group to send mail then it sends mail only if all groups have issue.

if one group has Error while Other group is OK, then no mail will be sent

 [emailnotifier "abc@example.com"]
group=kafka1,consumer1
group=kafka2,consumer2
interval=1
enable=true
threshold=2

in this case alert comes only **if none of them is OK status**

**Comment by toddpalino** [comment]
So this particular issue is the threshold setting mentioned, but the issue with emails only sending if all groups match is probably the same as #165. This seems to be an issue with the new notifier system for both slack and email that will need some work to resolve.

I'm going to close this issue and maintain the other one.
