### ISSUE TITLE
Add ability to read consumer offsets for all time

### ISSUE THREAD

**Issue by mikekap** [linkedin/Burrow#146]
Currently burrow only discovers consumer offsets if the consumer writes offsets AFTER burrow starts. This isn't very reliable when message volume is low. It would be nice if there was an option to read the consumer offsets topic from the very beginning to make sure that all consumers are accounted for.

This is effectively changing https://github.com/linkedin/Burrow/blob/master/kafka_client.go#L123 to use `OffsetOldest` based on a flag.

**Comment by toddpalino** [comment]
+1 to this. Should be a relatively small PR

**Comment by DavidLiuXh** [comment]
I use sarama.OffsetOldest instead of  sarama.OffsetNewest in the client.masterConsumer.ConsumePartition , But found a large number of threads, resulting in burrow hang.

**Comment by toddpalino** [comment]
Resolved by 1.0 rewrite
