### ISSUE TITLE
Burrow orphans pidfile on logger config error

### ISSUE THREAD

**Issue by CVTJNII** [linkedin/Burrow#153]
If there is an error in the logger config, Burrow orphans it's pidfile preventing a restart:

```
Started Burrow at November 7, 2016 at 7:20pm (UTC)
Reading configuration from /etc/burrow/burrow.cfg
1478546422126907737 [Critical] Cannot start logger: root xml tag must be 'seelog'
Reading configuration from /etc/burrow/burrow.cfg
1478546422375687686 [Critical] Cannot write PID file: open /var/tmp/burrow/burrow.pid: file exists
```

While not a major problem as this issue will not resolve without intervention, I would still expect Burrow to clean up its pidfile in this scenario.

**Comment by bencoughlan** [comment]
any updates on this?

**Comment by bencoughlan** [comment]
This is a docker bug - it requires priv's. 

docker run --rm -m 300M --name burrow --privileged -v /etc/burrow:/etc/burrow:rw -v /var/tmp/burrow:/var/tmp/burrow:rw -u root:root -p 80:80 -p 8080:8080 magnetme/burrow

That should work :)
