### ISSUE TITLE
Issue Evaluating Rule #3

### ISSUE THREAD

**Issue by tunderhill** [linkedin/Burrow#155]
Hi,

I'm currently testing Burrow and I'm struggling to understand how rule 3 gets triggered. As I understand it the lag needs to increase for _**every**_ interval in the current window while the consumer moves forward by committing offsets. 

Let's assume my producer is producing faster than my consumer is consuming and therefore lag is increasing.

If my consumer commits offsets, let's say, every 5 seconds, but the parameter "broker-offsets" is greater than 5 seconds then I don't don't see how it can be triggered as the true lag will be stale for some intervals and therefore the rule will be skipped. 

In my testing the only way I can get a consumer group to go into a WARN status is by ensuring that broker offsets are refreshed more frequently then the consumers commits, is this correct ? If so, is there a performance impact on setting a low value for broker-offsets ? 

Thanks,

Tom

**Comment by petergaultney** [comment]
I think I'm encountering this issue as well. I have a consumer that basically commits every single time it reads a message, but often lags behind a faster producer. This results in an inverse sawtooth wave of offset lag - the lag slowly decreases while the consumer is committing but Burrow hasn't refreshed the high water mark from Kafka, and then suddenly increases massively, resulting in an overall increase over time, but never triggering the WARN state in Burrow. 

It's not really reasonable to require consumers to "hold off on committing" just to make Burrow recognize that they're falling behind. 

I'm going to poke around the source code to see if I can figure out any way to fix this, but it would be great if someone familiar with the codebase were willing to jump in and beat me to it. :)

**Comment by petergaultney** [comment]
Alright, Tom, I think I have an answer for us both. 

If we set the configuration option
```
[tickers]
broker-offsets=5
```

then Burrow will update its high water mark every 5 seconds from Kafka, as you know.

The only other thing that seems to be necessary is forcing Burrow to ignore consumer updates that happen at a faster frequency. This can be done with

```
[lagcheck]
min-distance 10
```

(or, I assume, any value higher than 5). 

Once your configuration is set up this way, WARN seems to work. 

I guess I'm not seeing how Burrow accepting configuration `min-distance < broker-offsets` isn't basically a bug - it seems basically guaranteed to soft-disable the WARN state unless your consumers just so happen to commit less often than `broker-offsets`.  So my two cents would be: Burrow should regard this adverse configuration as a bug, and either throw a detailed error on startup (probably preferable), or automatically adjust one of the parameters to appropriately avoid the WARN state.

**Comment by tunderhill** [comment]
Thanks @petergaultney, that makes perfect sense. I'll do some more testing around this.

**Comment by toddpalino** [comment]
I'm going to change how min-distance works a little in the rewrite. I think it makes more sense to accept every offset commit that comes in, but if it violates min-distance it should just update the latest offset stored, not create a new one. I believe this is the source of a number of strange behaviors.

**Comment by toddpalino** [comment]
Resolved by 1.0 rewrite
