### ISSUE TITLE
Cannot use different ports by brokers

### ISSUE THREAD

**Issue by yewton** [linkedin/Burrow#16]
Hi,

I'm playing with a local Kafka cluster on docker.
Brokers are running in the dedicated containers and I use them via published ports on the docker host,
like `192.168.59.101:9091, 192.168.59.101:9092, 192.168.59.101:9093`, by setting `advertised.host.name` and `advertised.port`.

On the other hand, Burrow seems not to allow different ports by brokers.
I hope Burrow will support this feature!

Thanks.

**Comment by toddpalino** [comment]
This should be pretty easy to add in. I'll try and get to this shortly.

**Comment by yewton** [comment]
Good to hear that! I'm looking forward to it.

**Comment by toddpalino** [comment]
I've resolved this with the latest commit. You can now use the host:port format for hostnames. The port config options (like port in the zookeeper section, and zookeeper-port and broker-port in the cluster sections) are now optional, defaulting to 2181 for Zookeeper and 9092 for Kafka. If you have a host that does not have a ":port" at the end, it gets that port number tacked on.
