### ISSUE TITLE
go get github.com/linkedin/Burrow issue

### ISSUE THREAD

**Issue by plutoid** [linkedin/Burrow#162]
hi,

I don't know what kind of this versions dependency issue, kindly help here. 

/opt/go/src/github.com/linkedin/Burrow# go get github.com/linkedin/Burrow
# github.com/golang/snappy
../../golang/snappy/decode_amd64.s:10 6a: No such file or directory: textflag.h
# github.com/klauspost/crc32
../../klauspost/crc32/crc32_amd64p32.go:14: haveSSE42 redeclared in this block
        previous declaration at ../../klauspost/crc32/crc32_amd64.go:21
../../klauspost/crc32/crc32_amd64p32.go:19: castagnoliSSE42 redeclared in this block
        previous declaration at ../../klauspost/crc32/crc32_amd64.go:27
../../klauspost/crc32/crc32_amd64p32.go:21: sse42 redeclared in this block
        previous declaration at ../../klauspost/crc32/crc32_amd64.go:43
../../klauspost/crc32/crc32_amd64p32.go:23: archAvailableCastagnoli redeclared in this block
        previous declaration at ../../klauspost/crc32/crc32_amd64.go:54
../../klauspost/crc32/crc32_amd64p32.go:27: archInitCastagnoli redeclared in this block
        previous declaration at ../../klauspost/crc32/crc32_amd64.go:58
../../klauspost/crc32/crc32_amd64p32.go:34: archUpdateCastagnoli redeclared in this block
        previous declaration at ../../klauspost/crc32/crc32_amd64.go:90
../../klauspost/crc32/crc32_amd64p32.go:41: archAvailableIEEE redeclared in this block
        previous declaration at ../../klauspost/crc32/crc32_amd64.go:201
../../klauspost/crc32/crc32_amd64p32.go:42: archInitIEEE redeclared in this block
        previous declaration at ../../klauspost/crc32/crc32_amd64.go:207
../../klauspost/crc32/crc32_amd64p32.go:43: archUpdateIEEE redeclared in this block
        previous declaration at ../../klauspost/crc32/crc32_amd64.go:215

Regards,

Howard

**Comment by toddpalino** [comment]
I'm unable to duplicate this. Running "go get github.com/linkedin/Burrow" works just fine for me.

**Comment by plutoid** [comment]
seems that I didn't recoganize the basic facts the Burrow binary file would be created in $GOPATH/bin direcotry, no issue now.

**Comment by andreiplaton** [comment]
@plutoid  can you please tell me how you fixed this one? i keep getting same  error.
