### ISSUE TITLE
Monitoring lag of samza job

### ISSUE THREAD

**Issue by endeepak** [linkedin/Burrow#163]
Samza jobs are not listed in consumers when using below config

```
[kafka "kafka-qa"]
broker=x.x.x.x
broker-port=9092
zookeeper=y.y.y.y
zookeeper-port=2181
zookeeper-path=/
zookeeper-offsets=false
offsets-topic=__consumer_offsets
```

Also tried enabling zookeeper-offsets and got same result
```
zookeeper-offsets=true
```
and after reading on samza [checkpointing](https://samza.apache.org/learn/documentation/0.8/container/checkpointing.html), tried this

```
offsets-topic=__samza_checkpoint_ver_1_for_XXXXX_1
```

This results in error
```
/var/log/burrow/burrow.out:1481726580754223260 [Info] Starting consumers for 1 partitions of __samza_checkpoint_ver_1_for_XXXXX_1 in cluster kafka-qa
/var/log/burrow/burrow.out:1481726590952572606 [Warn] Failed to decode __samza_checkpoint_ver_1_for_XXXXX_1:0 offset 228586: keyver 31522
/var/log/burrow/burrow.out:1481726650958237768 [Warn] Failed to decode __samza_checkpoint_ver_1_for_XXXXX_1:0 offset 228587: keyver 31522
```

I did not find any documentation for checking lag of samza jobs using Burrow. Is there a way to do this?

**Comment by endeepak** [comment]
Looks like samza job offsets are stored differently and burrow doesn't support these. Found this mail archive which talks about this topic https://www.mail-archive.com/search?l=dev@samza.apache.org&q=subject:%22Monitoring+consumer+lag%22&o=newest&f=1

**Comment by toddpalino** [comment]
Yes, Samza uses a similar method to Kafka committed offsets, but a different format. Additionally, because it uses a different checkpoint topic for every job, it's very difficult to work that style into Burrow as things currently are. My hope is that in the future, Samza will migrate to using the standard offset requests in Kafka.
