### ISSUE TITLE
Its a query regarding burrow config rather issue

### ISSUE THREAD

**Issue by ersushantsood** [linkedin/Burrow#166]
Hi Team , I want to verify if burrow can read consumer offsets from zookeeper instead of kafka topic.

**Comment by endeepak** [comment]
Yes 

Wiki reference : https://github.com/linkedin/Burrow/wiki/What-is-Burrow
You need to set `zookeeper-offsets=true` Refer to https://github.com/linkedin/Burrow/wiki/Configuration#kafka
