### ISSUE TITLE
maxLag doesn't show maximum of all lags

### ISSUE THREAD

**Issue by sballal1** [linkedin/Burrow#170]
"maxlag" block always seems to have highest numbered partition, irrespective of whether it is a maximum lag or not.
Is this supposed to be like this? I was expecting it to be pointing to partition with maximum "end lag".

Example :
{"topic":"logs","partition":33,"status":"OK","start":{"offset":25686208,"timestamp":1484730645749,"lag":0},"end":{"offset":25695127,"timestamp":1484736045717,"lag":0}},{"topic":"logs","partition":34,"status":"OK","start":{"offset":25997264,"timestamp":1484730645767,"lag":75177},"end":{"offset":26024174,"timestamp":1484736045718,"lag":57184}},{"topic":"logs","partition":35,"status":"OK","start":{"offset":25997294,"timestamp":1484730645767,"lag":75105},"end":{"offset":26024148,"timestamp":1484736045719,"lag":57169}},

{"topic":"logs","partition":47,"status":"OK","start":{"offset":25998819,"timestamp":1484730645704,"lag":73583},"end":{"offset":26025871,"timestamp":1484736045718,"lag":55450}}],"maxlag":{"topic":"logs","partition":47,"status":"OK","start":{"offset":25998819,"timestamp":1484730645704,"lag":73583},"end":{"offset":26025871,"timestamp":1484736045718,"lag":55450}}}}

**Comment by toddpalino** [comment]
I'll evaluate this in the rewrite and see if it's still a bug.

**Comment by toddpalino** [comment]
Resolved by 1.0 rewrite
