### ISSUE TITLE
kafka 0.10.X and Spark directstream shows empty consumer list

### ISSUE THREAD

**Issue by mkargar** [linkedin/Burrow#172]
We are using Spark direct streaming to consume messages from Kafka and  /v2/kafka/local/consumer always returns empty list even when Spark is connected and fetching data!

**Comment by toddpalino** [comment]
I'm not familiar with how Spark consumes, specifically whether or not they use consumer groups and commit offsets to Kafka using the standard offset requests. For example, Samza uses the low-level consumer and does not use consumer groups, tracking its offsets separately.

It sounds like Spark does something similar. In which case Burrow will have no way of knowing about those consumers. It can only track consumer groups that are using the standard Kafka methods of committing offsets (either ZK or using Offset requests within the Kafka protocol).

**Comment by toddpalino** [comment]
Once the 1.0 rewrite is complete, it will be possible for someone to write a Spark consumer module if they would like.
