### ISSUE TITLE
librdkafka consumer group miss

### ISSUE THREAD

**Issue by xjj210130** [linkedin/Burrow#174]
hi all:
   i use librdkafka to consumer message, and use keep-alive.. First i use only one thread to consume message.
The code like the foloowing:
class Consumer
{
public:
void init();
 void fun();
private:
RdKafka::KafkaConsumer* m_pConsumer;

};

void  Consumer::init()
{
m_pGlobalConf->set("group.id",  "test", errstr)
	m_pGlobalConf->set("enable.auto.commit", "true", errstr);
	 m_pGlobalConf->set("heartbeat.interval.ms", "1000", errstr);
 m_pConsumer= RdKafka::KafkaConsumer::create(m_pGlobalConf, errstr);
}

void  Consumer::fun()
{
while(bFlag)
	{
		if(NULL != m_pConsumer)
		{
			RdKafka::Message *msg = m_pConsumer->consume(1000);
  }

}

Now, i user the follow cmd:
./kafka-consumer-groups.sh --new-consumer  --bootstrap-server xx:9092 --list default
  
it can show the group : test

but after one day, the group :test is missing.

librdkafka version is  0x00090301
Is some one know why? thanks .

**Comment by xjj210130** [comment]
meanwhile , i use zk cmd like the following:
ls /consumers/console-consumer-97837/offsets

This is also  no consume group exist.

**Comment by toddpalino** [comment]
This sounds like more of a question librdkafka and Kafka in general, and not Burrow. However, what I will say is that if you have a new consumer (which you say you do), it will not register in Zookeeper.
