### ISSUE TITLE
Ever increasing disk usage

### ISSUE THREAD

**Issue by rogierslag** [linkedin/Burrow#176]
We are running Burrow inside of Docker on our Kafka cluster. Unfortunately the container keeps using more and more disk space (well over 100GB after a few days). After a container restart this is gone, so for now this is our remedy to keep burrow running.

Is there a specific reason Burrow needs to keep so many files or does not clean them properly?

**Comment by toddpalino** [comment]
Burrow does not use disk at all, except for logging. Do you have specific examples of what you believe is Burrow using disk space?

**Comment by rogierslag** [comment]
Hmm the default implementation in https://github.com/linkedin/Burrow/blob/master/docker-config/logging.cfg sets a log level of debug. However inside the dockercontainer this is not really useful, since the logs are only visible to the user if the directory is mapped to the host OS

I'll prepare a small PR

**Comment by rogierslag** [comment]
```
rogierslag@kafka1:~$ docker logs -f burrow
Reading configuration from /etc/burrow/burrow.cfg
```

```
rogierslag@kafka1:~$ docker ps -s
CONTAINER ID        IMAGE                    COMMAND                  CREATED             STATUS              PORTS                                                NAMES               SIZE
7b381b4b63e3        magnetme/burrow:latest   "/go/bin/burrow --con"   7 hours ago         Up 7 hours          10.0.0.40:8000->8000/tcp, 127.0.0.1:8000->8000/tcp   burrow              4.201 GB (virtual 4.485 GB)
```
