### ISSUE TITLE
Unable to install Burrow

### ISSUE THREAD

**Issue by alamzeeshan** [linkedin/Burrow#183]
`go get github.com/linkedin/Burrow` is not working

`$ go get -v github.com/linkedin/Burrow`

```
Fetching https://gopkg.in/gcfg.v1?go-get=1
https fetch failed: Get https://gopkg.in/gcfg.v1?go-get=1: proxyconnect tcp: dial tcp :0: getsockopt: connection refused
package gopkg.in/gcfg.v1: unrecognized import path "gopkg.in/gcfg.v1" (https fetch: Get https://gopkg.in/gcfg.v1?go-get=1: proxyconnect tcp: dial tcp :0: getsockopt: connection refused)
```

**go version go1.8 linux/amd64
gpm version >> gpm v1.4.0**

**Comment by toddpalino** [comment]
This is a networking problem on your side, not an issue with Burrow

`host:~ tpalino$ go get -v github.com/linkedin/Burrow
github.com/linkedin/Burrow (download)
github.com/Shopify/sarama (download)
github.com/davecgh/go-spew (download)
github.com/eapache/go-resiliency (download)
github.com/eapache/go-xerial-snappy (download)
github.com/golang/snappy (download)
github.com/eapache/queue (download)
github.com/klauspost/crc32 (download)
github.com/pierrec/lz4 (download)
github.com/pierrec/xxHash (download)
github.com/rcrowley/go-metrics (download)
github.com/cihub/seelog (download)
github.com/pborman/uuid (download)
github.com/samuel/go-zookeeper (download)
Fetching https://gopkg.in/gcfg.v1?go-get=1
Parsing meta tags from https://gopkg.in/gcfg.v1?go-get=1 (status code 200)
get "gopkg.in/gcfg.v1": found meta tag main.metaImport{Prefix:"gopkg.in/gcfg.v1", VCS:"git", RepoRoot:"https://gopkg.in/gcfg.v1"} at https://gopkg.in/gcfg.v1?go-get=1
gopkg.in/gcfg.v1 (download)
Fetching https://gopkg.in/warnings.v0?go-get=1
Parsing meta tags from https://gopkg.in/warnings.v0?go-get=1 (status code 200)
get "gopkg.in/warnings.v0": found meta tag main.metaImport{Prefix:"gopkg.in/warnings.v0", VCS:"git", RepoRoot:"https://gopkg.in/warnings.v0"} at https://gopkg.in/warnings.v0?go-get=1
gopkg.in/warnings.v0 (download)
github.com/davecgh/go-spew/spew
github.com/eapache/go-resiliency/breaker
github.com/golang/snappy
github.com/eapache/queue
github.com/klauspost/crc32
github.com/pierrec/xxHash/xxHash32
github.com/pierrec/lz4
github.com/rcrowley/go-metrics
github.com/eapache/go-xerial-snappy
github.com/cihub/seelog/archive/gzip
github.com/cihub/seelog/archive
github.com/cihub/seelog/archive/tar
github.com/cihub/seelog/archive/zip
github.com/linkedin/Burrow/protocol
github.com/cihub/seelog
github.com/pborman/uuid
github.com/samuel/go-zookeeper/zk
gopkg.in/gcfg.v1/token
gopkg.in/gcfg.v1/scanner
gopkg.in/gcfg.v1/types
gopkg.in/warnings.v0
gopkg.in/gcfg.v1
github.com/Shopify/sarama
github.com/linkedin/Burrow/notifier
github.com/linkedin/Burrow
`
