### ISSUE TITLE
Consumer List Empty

### ISSUE THREAD

**Issue by anandsk123** [linkedin/Burrow#187]
Hi, 

I have tried everything and hence asking for some help here:
http://server_name:8000/v2/kafka/cluster_name
never shows any consumers in the list. Please let me know what I am doing wrong.

This api is working:
http://server_name:8000/v2/kafka/cluster_name/topic

Thanks, 
Anand

**Comment by k1ng87** [comment]
Looks like many folks are getting this issue including myself...hopefully a solution is discovered soon....

**Comment by rs857c** [comment]
I am also getting empty list, kindly let me know what is need to validate this
{"error":false,"message":"consumer list returned","consumers":[],"request":{"url":"/v2/kafka/local/consumer","host":"zltcmtc3njmsrt02","cluster":"local","group":"","topic":""}}

**Comment by toddpalino** [comment]
Burrow will only show consumers in the list if they are committing offsets (and are not blacklisted in the config)
