### ISSUE TITLE
Slack Notifications Are Not being Sent

### ISSUE THREAD

**Issue by abhiCR7** [linkedin/Burrow#197]
Slack notifications is priority so for now i've only configured slack notifications. I set the threshold to 0 so i get all the alerts,  but i'm not receiving any notifications. 

My config is as follows

[general]
logdir=log
logconfig=/config/logging.cfg
pidfile=burrow.pid
client-id=burrow-lagchecker
#group-blacklist=^(console-consumer-|python-kafka-consumer-).*$
#group-whitelist=^(my-important-consumer).*$

[zookeeper]
hostname=x.x.x.x
hostname=x.x.x.x
hostname=x.x.x.x
port=2181
timeout=6
lock-path=/notifier

[kafka "staging"]
broker=10.0.1.22
broker=10.0.1.23
broker=10.0.1.26
broker-port=9092
zookeeper=10.0.1.28
zookeeper=10.0.1.25
zookeeper=10.0.1.27
zookeeper-port=2181
zookeeper-path=/kafka-cluster
zookeeper-offsets=true
offsets-topic=__consumer_offsets

[tickers]
broker-offsets=10

[lagcheck]
intervals=10
expire-group=604800

[httpserver]
server=on
port=8000

[notify]
interval=2

[slacknotifier]
enable=true
url=https://hooks.slack.com/services/xxx/xxx
group=staging,critical-consumer-group
group=staging,user-activity-group
threshold=0
channel="#sensu-alerts-stage"
username=burrower
interval=5
timeout=5
keepalive=30`

is there anything we need to set so that alerts(messages) start flowing?

**Comment by adomenech73** [comment]
I'm exactly in the same situation.

Initially I configured email notifications through local postfix but never received one.
Added Slack notifications configuration to discard, and also didn't work

Nothing on emails logs even if I can see the errors on the Dashboard. Notifications is the core feature of Burrow as I understand. 

¿Is there any way to debug or trace notifications through logs? 

This is my conf I'm probably  missing something:

```
[general]
pidfile=burrow.pid
client-id=burrow-lagchecker
group-blacklist=^(console-consumer-|python-kafka-consumer-).*$
logdir=/var/log/burrow

[zookeeper]
hostname=zoo0
port=2181
timeout=6
lock-path=/burrow/notifier

[kafka "local"]
broker=kafka0
broker-port=9092
zookeeper=zoo0
zookeeper-port=2181
zookeeper-path=/kafka-cluster
offsets-topic=__consumer_offsets

[httpserver]
server=on
port=8000

[smtp]
server=localhost
port=25
from=stg-burrow-noreply@fictional.com
template=/opt/gopath/src/github.com/linkedin/burrow/config/default-email.tmpl

[emailnotifier "alert@fictional.com"]
group=local,consumer1
group=local,consumer2
group=local,consumer3
group=local,consumer4
group=local,consumer5
interval=600
enable=true

[notify]
interval=10

[slacknotifier]
enable=true
url=https://hooks.slack.com/services/XXXXXXX/YYYYYYYYY
group=local,consumer1
group=local,consumer2
group=local,consumer3
group=local,consumer4
group=local,consumer5
threshold=2
channel="@my_channel"
username=burrow
interval=3600
timeout=5
keepalive=30
```

**Comment by adomenech73** [comment]
I'm not so familiar with Go, but I added some log.Info("blahblahblah") in NewEmailNotifier and NewSlackNotifier functions. The thing is that I can see the first outputs as the function has been called but any posterior output (for example during the "for" loop of NewEmailNotifier) never goes out. 
¿Is this normal?

**Comment by toddpalino** [comment]
Both Slack and email notifications had some issues in the 0.x implementation, especially with multiple groups specified. The new implementation is a notification per-group (it doesn't try and gather multiple notifications together). It should work much better now. Please give the 1.0 release a try, and open a new issue if it persists.
