### ISSUE TITLE
Question: how does burrow line up the time buckets for the max log offset and the data in consumer offsets

### ISSUE THREAD

**Issue by k1ng87** [linkedin/Burrow#199]
I'm trying to understand how burrow lines up the time that the end offset of the log is polled at with the `commit_time` in the `__consumer_offsets` topic. 

let say the polled the log end offset for TopicA partition 2 at `4/6/17 7:00:08.120` and got a value back of `659256972`

Now lets say the offset for that topic in that partition in `__consumer_offsets` was `659257652` with a commit time of `4/6/17 7:00:08.922`....so the lag would be `659256972 - 659257652 = -680` during the time bucket (1s) `4/6/17 7:00:08`...correct?

This is happening because the logoffset was polled earlier then when the consumer offset was committed to `__consumer_offset` for the time bucket of `4/6/17 7:00:08`. 

How does burrow handle something like this?

**Comment by toddpalino** [comment]
Burrow doesn't try to align them. The end offsets are polled on a fixed interval (configurable). The lag is calculated when the consumer's offset commit is read using whatever the latest end offset in memory is. If the calculated lag is negative, Burrow records it as zero.
