### ISSUE TITLE
Topic Offsets Get Stuck

### ISSUE THREAD

**Issue by iamnoah** [linkedin/Burrow#20]
Sorry, I have no idea why this happens, but we are running Burrow and after some amount of time, the  offsets in the Cluster Topic Detail stop updating. The offsets in the Consumer Topic Detail appear to be up to date, but they are now greater than the offsets in the topic detail, so if we use the two numbers to calculate lag, we get a negative number.

Restarting Burrow seems to fix the problem, but it occurs multiple times per day. Is there anything we can do/try?

**Comment by toddpalino** [comment]
I've not seen anything like this happen internally. The broker offsets are pulled using a periodic batch of OffsetRequest messages to the brokers to get information, and it's a fairly simple operation. As long as Burrow's Kafka client is up and running (which it has to be if you are seeing consumer offsets), there should be no issue with this.

When this happens, is there any detail in Burrow's log? Also, is there anything else going on with the cluster that might be out of the ordinary, such as an offline broker?

**Comment by iamnoah** [comment]
Since I filed this, we've made configuration changes to improve the health of the cluster and I've not seen the issue again.
