### ISSUE TITLE
Burrow failed at startup if kafka is not found

### ISSUE THREAD

**Issue by smasue** [linkedin/Burrow#201]
When restarting my VMs I can't really assure that burrow will be restarted after kafka. If burrow is restarted before kafka, then it tries to connect to kafka a few times and finally fails. 
In my case it would have taken just a minute to wait for kafka and make it work.

log:
Failed to connect to [my.kafka.host]:2181: dial tcp: i/o timeout
Failed to connect to [my.kafka.host]:2181: dial tcp: ...
Failed to connect to [my.kafka.host]:2181: dial tcp: ...
Failed to connect to [my.kafka.host]:2181: dial tcp: ...
[Critical] Cannot start Kafka client for cluster kafka: kafka: client has run out of available brokers to talk to (Is your cluster reachable?)
Failed to connect to [my.kafka.host]:2181: dial tcp: ...
Failed to connect to [my.kafka.host]:2181: dial tcp: ...
Burrow failed at ..... (UTC)

**Comment by bencoughlan** [comment]
ever get an update on this? Is anyone looking at this?

**Comment by toddpalino** [comment]
This is expected behavior - if there's no Kafka cluster to talk to, Burrow can't do anything. Currently, Burrow will not retry failed connections, but it would be possible to add this if someone wants to work on it and submit a PR.

**Comment by smasue** [comment]
I found a work around using systemd and the retry option.
It does the job for me.

**Comment by akamalov** [comment]
@smasue, can you please share your systemd service file?? I am getting exactly the same message, while my Kafka cluster is up and operational..

**Comment by smasue** [comment]
@akamalov I used the options:
Restart=on-failure
RestartSec=60s
