### ISSUE TITLE
Enable CORS?

### ISSUE THREAD

**Issue by k1ng87** [linkedin/Burrow#203]
How can I enable CORS on this? I'm trying to leverage the BurrowUI project on top of this but I get the pesky `No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access.` error....

**Comment by toddpalino** [comment]
There's currently no internal support for CORS. We'll look to add this.

**Comment by toddpalino** [comment]
Resolved by 1.0 rewrite
