### ISSUE TITLE
Still showing increasing lag after killing all producers...

### ISSUE THREAD

**Issue by k1ng87** [linkedin/Burrow#206]
I got weird thing happening in Burrow. Looking at a specific topic, I've killed all the producers but I'm still seeing an increasing lag. How is that possible if there are no producers producing to the topic? To produce the graphs, I'm using Burrower to send the data to influxdb...

<img width="677" alt="screen shot 2017-04-14 at 8 04 11 am" src="https://cloud.githubusercontent.com/assets/11411569/25042847/4a450b4a-20e9-11e7-95bd-b10842f4d11a.png">

**Comment by toddpalino** [comment]
In order to diagnose this, we would need to see the raw data coming out of HTTP queries to burrow for the consumer group. There may be an issue downstream from Burrow that you're running into.

**Comment by toddpalino** [comment]
I'm going to close this out. If you're still seeing this, please pull the detailed consumer information using the API endpoint /v3/kafka/(cluster)/consumer/(groupname). This will dump all the offset commit information that Burrow has stored for the group. Then open a new issue and we can review that to see what Burrow is picking up on.
