### ISSUE TITLE
how can I use burrow to monitor kafka with ssl？

### ISSUE THREAD

**Issue by wobuxiangtong** [linkedin/Burrow#207]
Cannot start Kafka client for cluster local: kafka: client has run out of available brokers to talk to (Is your cluster reachable?)

**Comment by bencoughlan** [comment]
did you get any help with this? 

I'm getting the same issue.

**Comment by njrbalu** [comment]
Having same issue any update?

Found that there is tls support. But not able to configure it correctly.

**Comment by toddpalino** [comment]
What is your current configuration, and what errors are you getting when trying to use TLS?

**Comment by santiagomoneta** [comment]
Not clear how to setup SSL using a keystone and truststore file.. any help?

**Comment by ANINDITYA5** [comment]
Can we monitor Kafka Broker SSL Client Certificate with the help of an exporter? I just need to check whether we can create a Prometheus metric based on the expiry date.
