### ISSUE TITLE
packaging of the application fails

### ISSUE THREAD

**Issue by aadu-coder** [linkedin/Burrow#208]
While trying to package this application, getting below error:
 _!     Deprecated, old ./Godeps file found!
 !     Please upgrade godeps (go get -u github.com/tools/godep) and
 !     re-save your dependencies: godep save -r ./..._
parse error: Invalid numeric literal at line 1, column 34

**Comment by aadu-coder** [comment]
does somebody have a rpm file for centos6 ?

**Comment by toddpalino** [comment]
This appears to be related to the environment you're trying to build in. You may have an old version of gpm. Please make sure to follow the readme directions.

As a note, we're moving from gpm to dep in the 1.0 rewrite.
