### ISSUE TITLE
Docker build failes while fetching go package gcfg.v1

### ISSUE THREAD

**Issue by balistof** [linkedin/Burrow#209]
>> Getting package github.com/samuel/go-zookeeper/zk
>> Getting package github.com/Shopify/sarama
>> Getting package github.com/cihub/seelog
>> Getting package gopkg.in/gcfg.v1
>> Getting package github.com/pborman/uuid
package gopkg.in/gcfg.v1: unrecognized import path "gopkg.in/gcfg.v1" (https fetch: Get https://gopkg.in/gcfg.v1?go-get=1: x509: certificate is not authorized to sign other certificates)
>> Setting github.com/samuel/go-zookeeper/zk to version ad552be7b78b762b4a8040ffc5518bdaf5b7225d
>> Setting github.com/Shopify/sarama to version 4ba9bba6adb6697bcec3841e1ecdfecf5227c3b9
>> Setting github.com/cihub/seelog to version 92dc4b8b540607b8187cc2f95cac200211dcd745
>> Setting gopkg.in/gcfg.v1 to version 0ef1a8547f99b94fac9af5377dd72febba18f37c
/usr/local/bin/gpm: line 73: cd: /go/src/gopkg.in/gcfg.v1/: No such file or directory
>> Setting github.com/pborman/uuid to version ca53cad383cad2479bbba7f7a1a05797ec1386e4
>> Building package github.com/samuel/go-zookeeper/zk
>> Building package github.com/Shopify/sarama
>> Building package github.com/cihub/seelog
>> Building package gopkg.in/gcfg.v1
can't load package: package gopkg.in/gcfg.v1: cannot find package "gopkg.in/gcfg.v1" in any of:
        /usr/local/go/src/gopkg.in/gcfg.v1 (from $GOROOT)
        /go/src/gopkg.in/gcfg.v1 (from $GOPATH)

Any ideas?

**Comment by toddpalino** [comment]
This is a problem with the fetch to gopkg.in, and not Burrow itself. It looks like there may have been a temporary error in their server.
