### ISSUE TITLE
Outdated version of go-zookeeper

### ISSUE THREAD

**Issue by roiravhon** [linkedin/Burrow#216]
https://github.com/linkedin/Burrow/blob/master/Godeps#L1
Is using a commit from 2014.

Since, there were couple of changes, and this in particular - https://github.com/samuel/go-zookeeper/pull/102

Using burrow in our environment now produces an exception as described in the PR, and after the upgrade, it's working. Any particular reason for this version?

Thanks,
Roi

**Comment by toddpalino** [comment]
I just try to keep the dependencies locked to working versions, so as not to introduce surprising changes. Sarama, in particular, had a habit of completely breaking the interface with every commit.

If you submit a PR for the dependency change, we can test it out and make sure everything's working properly.

**Comment by toddpalino** [comment]
This is updated in the rewrite

**Comment by toddpalino** [comment]
Resolved by 1.0 rewrite
