### ISSUE TITLE
Not able to understand result for /v2/kafka/local/consumer/group1/lag

### ISSUE THREAD

**Issue by abhimanyunagrath** [linkedin/Burrow#221]
{
  "error": false,
  "message": "consumer group status returned",
  "status": {
    "cluster": "local",
    "group": "group1",
    "status": "OK",
    "complete": false,
    "partitions": [
      {
        "topic": "topic1",
        "partition": 1,
        "status": "OK",
        "start": {
          "offset": 144,
          "timestamp": 1494566913489,
          "lag": 0,
          "max_offset": 144
        },
        "end": {
          "offset": 144,
          "timestamp": 1494566999000,
          "lag": 0,
          "max_offset": 144
        }
      }
    ],
    "partition_count": 17,
    "maxlag": null,
    "totallag": 0
  },
  "request": {
    "url": "/v2/kafka/local/consumer/group1/lag",
    "host": "<burrow IP>",
    "cluster": "local",
    "group": "group1",
    "topic": ""
  }
}

Hi on hitting the API /v2/kafka/local/consumer/group1/lag I am not able to view all the topics details present in that group and getting complete: false in the above JSON. What does this mean?

**Comment by toddpalino** [comment]
When complete is false, this means that Burrow does not yet have complete data on the consumer group. For example, if your group consumes 1 topic with 10 partitions, and Burrow is configured for 10 intervals, then it will need to see 10 offset commits for each of the 10 partitions before the data is complete.

**Comment by marcosArruda** [comment]
@toddpalino thanks for the light. In my use case, I have a group consuming 2 topics:
- topic1: 10 partitions
- topic2: 1000 partitions. 

My question is. Can I know when does the complete flag will be true?
Maybe thats the reason why my notifiers are not triggering...

my current .../status json:
{
   "error":false,
   "message":"consumer group status returned",
   "status":{
      "cluster":"production",
      "group":"my_group",
      "status":"ERR",
      "complete":false,
      "partitions":[
         {
            "topic":"topic2",
            "partition":13,
            "status":"STOP",
            "start":{
               "offset":6687,
               "timestamp":1510696246000,
               "lag":0,
               "max_offset":6687
            },
            "end":{
               "offset":6687,
               "timestamp":1510696336000,
               "lag":0,
               "max_offset":6687
            }
         },
         {
            "topic":"topic2",
            "partition":56,
            "status":"STOP",
            "start":{
               "offset":6460,
               "timestamp":1510696196000,
               "lag":0,
               "max_offset":6460
            },
            "end":{
               "offset":6460,
               "timestamp":1510696286000,
               "lag":0,
               "max_offset":6460
            }
         },
         {
            "topic":"topic2",
            "partition":58,
            "status":"STOP",
            "start":{
               "offset":6719,
               "timestamp":1510696246000,
               "lag":0,
               "max_offset":6719
            },
            "end":{
               "offset":6719,
               "timestamp":1510696336000,
               "lag":0,
               "max_offset":6719
            }
         },
         {
            "topic":"topic2",
            "partition":88,
            "status":"STOP",
            "start":{
               "offset":6618,
               "timestamp":1510696246000,
               "lag":0,
               "max_offset":6618
            },
            "end":{
               "offset":6618,
               "timestamp":1510696336000,
               "lag":0,
               "max_offset":6618
            }
         },
         {
            "topic":"topic2",
            "partition":96,
            "status":"STOP",
            "start":{
               "offset":6500,
               "timestamp":1510696256000,
               "lag":0,
               "max_offset":6500
            },
            "end":{
               "offset":6500,
               "timestamp":1510696346000,
               "lag":0,
               "max_offset":6500
            }
         },
         {
            "topic":"topic2",
            "partition":964,
            "status":"STOP",
            "start":{
               "offset":6585,
               "timestamp":1510695958144,
               "lag":0,
               "max_offset":6585
            },
            "end":{
               "offset":6585,
               "timestamp":1510696046000,
               "lag":0,
               "max_offset":6585
            }
         }
      ],
      "partition_count":1010,
      "maxlag":{
         "topic":"topic1",
         "partition":3,
         "status":"OK",
         "start":{
            "offset":388629,
            "timestamp":1510695056644,
            "lag":383681,
            "max_offset":388629
         },
         "end":{
            "offset":389261,
            "timestamp":1510696482129,
            "lag":383318,
            "max_offset":389261
         }
      },
      "totallag":3623877
   },
   "request":{
      "url":"/v2/kafka/production/consumer/my_group/status",
      "host":"618827cd6dfe",
      "cluster":"production",
      "group":"my_group",
      "topic":""
   }
}

**Comment by toddpalino** [comment]
Yeah, it'll never be true until there are full offsets for every partition.

I've just pushed the 1.0 release candidate. In this version, complete is now a float between 0.0 and 1.0 that shows the percentage complete for the entire group, and for each partition. That way, it should be a little more obvious. It also doesn't wait until it's 100% to start reporting.
