### ISSUE TITLE
Kafka client upgrade to 0.10

### ISSUE THREAD

**Issue by sbrnunes** [linkedin/Burrow#225]
Hi,

In the Kafka 0.10 upgrade guide it is mentioned that there's a risk of CPU spikes if consumers are still using Kafka 0.9 (or older versions), because of the on-the-fly translation (see: https://kafka.apache.org/documentation/#upgrade).

Is anyone working on upgrading the Kafka client dependency used by Burrow?

Support for the latest Kafka was already added to: https://github.com/Shopify/sarama

**Comment by toddpalino** [comment]
Coming soon with the 1.0 rewrite

**Comment by toddpalino** [comment]
Resolved by 1.0 rewrite
