### ISSUE TITLE
Support to connect to secure kafka (SASL_PLAINTEXT)

### ISSUE THREAD

**Issue by rja1** [linkedin/Burrow#228]
Can support to connect to secure kafka (SASL_PLAINTEXT) be added to this project?

I currently don't see any configuration options that would allow this.  

Thanks,

Rob

**Comment by toddpalino** [comment]
There is support for TLS, as well as using a client certificate, but there's currently no support for SASL. It shouldn't be too difficult to add, however, as the underlying Kafka client does support this.

**Comment by toddpalino** [comment]
Resolved by 1.0 rewrite
