### ISSUE TITLE
Rule 4 fails with high commit frequency

### ISSUE THREAD

**Issue by TNorden** [linkedin/Burrow#24]
I have a few consumers I am monitoring with Burrow that commit frequently under normal load.  At some points the commit frequency is faster than the lag check runs.  I end up with a very small window where the difference between the first and last is ~200 ms.

I added some logging and here is an example, format is {`offset` `timestamp` `lag`}.
```
{74218 1442857809487 0} {74219 1442857809498 0} {74220 1442857809510 0} {74221 1442857809521 0} {74222 1442857809657 0} {74223 1442857809670 0} {74224 1442857809681 0} {74225 1442857809692 0} {74226 1442857809705 0} {74227 1442857809716 0}
```

`1442857809716 - 1442857809487 = 229 ms`

In this case if the lag check is run more than 229 ms after the last offset is committed then the check fails.

Seems like the `broker-offsets` should be the minimum time between offsets within the window.

**Comment by TNorden** [comment]
I did some more digging into this and the current implementation expects that he consumer is committing offsets on some fixed period.  I added a config value so that the `offsets_store` can also enforce the period when the consumer is committing too frequently.

**Comment by toddpalino** [comment]
Thank you for the PR to fix this. We generally use regular commit intervals, so this issue hadn't occurred anywhere. After reviewing the logic, the PR looks great. The config value defaults to zero, so this will not come into play unless you set the config.
