### ISSUE TITLE
Support for multiple storms consumers not showing lag details for other consumers

### ISSUE THREAD

**Issue by abhishekpandey003** [linkedin/Burrow#240]
Support for multiple storms consumers #158 is able to detect lag for other consumers configured under multiple "zookeeper-path", but the Consumer Group Status (/v2/kafka/(cluster)/consumer/(group)/lag) does not show lag details for other zookeeper paths. 

[storm "local"]
..
zookeeper-path=/storm-cluster1
zookeeper-path=/storm-cluster2

Here, if the other storm consumer /storm-cluster2 is lagging but the Consumer Group Status always shows the lag details for first consumer /storm-cluster1, even though the first consumer is not lagging. The alert emails are also generated but with the offsets of first consumer.

**Comment by toddpalino** [comment]
This sounds like an issue of group name collisions between two different storm clusters reading from the same Kafka cluster. In the existing code, there's not a good way to resolve it - consumers are associated with the Kafka cluster, so you're going to get unpredictable results when there are two with the same name in the same cluster.

In in burrow-1.0 rewrite, I'll think on this and see if we can come up with a reasonable way to resolve it.

**Comment by toddpalino** [comment]
So looking at this again, I'm going to close it out. Given the way Burrow works (even in 1.0), the consumer groups are assigned to a cluster, so there's an expectation that the group name is unique for the Kafka cluster. This means that if you have 2 storm clusters that each have a group with an identical name, you'll have problems. This is expected, and not something that will be supported at this time.
