### ISSUE TITLE
formatting of partition error time stamp for email template

### ISSUE THREAD

**Issue by plutoid** [linkedin/Burrow#241]
hi,

partition error info from email template:
````
    STALL customer_event_merged:0 (1499430249488, 23360888, 0) -> (1499432126000, 23360888, 0)
````

part of my email template:
````
....
{{range .Partitions}}          {{if eq 1 .Status}} WARN{{else if eq 2 .Status}}  ERR{{else if eq 3 .Status}} STOP{{else if eq 4 .Status}}STALL{{end}} {{.Topic}}:{{.Partition}} ({{.Start.Timestamp}}, {{.Start.Offset}}, {{.Start.Lag}}) -> ({{.End.Timestamp}}, {{.End.Offset}}, {{.End.Lag}})
....
````

here below, it couldn't be read by human easily :)
````
.Start.Timestamp == 1499430249488
````

for the time stamp of partition error info in email template, seems I need a method to transfer it, once I tried to use ".Start.Timestamp.Format "Jan 02, 2006 15:04:05 UTC" ", but it's useless, any suggestion for me? thanks a lot!

Regards, Howard

**Comment by toddpalino** [comment]
Resolved by 1.0 rewrite
