### ISSUE TITLE
访问报错

### ISSUE THREAD

**Issue by navyaijm2017** [linkedin/Burrow#246]
你好，按着文档部署启动服务后，访问报错，这个是啥原因呢。
访问：http://10.10.30.71:8000/v2/kafka
报错信息：
{"error":false,"message":"cluster list returned","clusters":["local"],"request":{"url":"/v2/kafka","host":"ip-10-10-30-71","cluster":"","group":"","topic":""}}

我的配置文件：
[general]
logdir=log
logconfig=config/logging.cfg
pidfile=burrow.pid
client-id=burrow-lagchecker
#group-blacklist=^(console-consumer-|python-kafka-consumer-).*$
#group-whitelist=^(my-important-consumer).*$

[zookeeper]
hostname=10.10.30.69
hostname=10.10.30.70
hostname=10.10.30.71
port=2181
timeout=6
lock-path=/burrow/notifier

[kafka "local"]
broker=10.10.30.69
broker=10.10.30.70
broker=10.10.30.71
broker-port=9092
zookeeper=10.10.30.69
zookeeper=10.10.30.70
zookeeper=10.10.30.71
zookeeper-port=2181
zookeeper-path=/
offsets-topic=__consumer_offsets

#[storm "local"]
#zookeeper=10.10.30.69
#zookeeper=10.10.30.70
#zookeeper=10.10.30.71
#zookeeper-port=2181
#zookeeper-path=/

[tickers]
broker-offsets=60

[lagcheck]
intervals=10
expire-group=604800

[httpserver]
server=on
port=8000
; Alternatively, use listen (cannot be specified when port is)
; listen=host:port
; listen=host2:port2

[smtp]
server=mailserver.example.com
port=25
from=burrow-noreply@example.com
template=config/default-email.tmpl

[emailnotifier "bofh@example.com"]
group=local,critical-consumer-group
group=local,other-consumer-group
interval=60

[notify]
interval=10

[httpnotifier]
url=http://notification.server.example.com:9000/v1/alert
interval=60
extra=app=burrow
extra=tier=STG
template-post=config/default-http-post.tmpl
template-delete=config/default-http-delete.tmpl
timeout=5
keepalive=30

[slacknotifier]
enable=true
url=https://hooks.slack.com/services/xxxx/xxxxxxxxxx
group=local,critical-consumer-group
group=local,other-consumer-group
threshold=0
channel="#general"
username=burrower
interval=5
timeout=5
keepalive=30

**Comment by toddpalino** [comment]
I'm sorry, unfortunately I'll need an English translation to be able to help you.

**Comment by allenxiang** [comment]
@navyaijm2017 I don't see anything wrong with the output you posted.  It clearly says `"error":false`.

**Comment by DavidLiuXh** [comment]
@navyaijm2017 没有报错,你请求的url是返回cluster list, 在你的配置文件里你配置了[kafka "local"]

**Comment by toddpalino** [comment]
Since there doesn't appear to be an error here, I'm closing this out.
