### ISSUE TITLE
Burrow fail to start

### ISSUE THREAD

**Issue by ishitat** [linkedin/Burrow#247]
This is my log 

Started Burrow at August 9, 2017 at 9:53am (EDT)
2017/08/09 09:53:59 Connected to 192.168.0.100:2181
2017/08/09 09:53:59 Connected to 192.168.0.100:2181
2017/08/09 09:53:59 Authenticated: id=98453868362596353, timeout=6000
2017/08/09 09:53:59 Re-submitting `0` credentials after reconnect
2017/08/09 09:53:59 Authenticated: id=98453868362596354, timeout=6000
2017/08/09 09:53:59 Re-submitting `0` credentials after reconnect
2017/08/09 09:54:00 Recv loop terminated: err=EOF
2017/08/09 09:54:00 Send loop terminated: err=<nil>
2017/08/09 09:54:00 Recv loop terminated: err=EOF
2017/08/09 09:54:00 Send loop terminated: err=<nil>
Burrow failed at August 9, 2017 at 9:54am (EDT)

This is my config file:

[general]
logdir=/home/user/work/src/github.com/linkedin/Burrow/log
logconfig=/home/user/work/src/github.com/linkedin/Burrow/config/logging.cfg
pidfile=burrow.pid
client-id=burrow-lagchecker
group-blacklist=^(console-consumer-|python-kafka-consumer-).*$
#group-whitelist=^(my-important-consumer).*$

[zookeeper]
hostname=192.168.0.100
#hostname=zkhost02.example.com
#hostname=zkhost03.example.com
port=2181
timeout=6
lock-path=/burrow/notifier

[kafka "local"]
broker=192.168.0.100
#broker=kafka02.example.com
#broker=kafka03.example.com
#broker=kafka04.example.com
#broker=kafka05.example.com
broker-port=10251
zookeeper=192.168.0.100
#zookeeper=zkhost02.example.com
#zookeeper=zkhost03.example.com
zookeeper-port=2181
zookeeper-path=/kafka-cluster
offsets-topic=__consumer_offsets

[storm "local"]
zookeeper=192.168.0.100
#zookeeper=zkhost02.example.com
#zookeeper=zkhost03.example.com
zookeeper-port=2181
zookeeper-path=/kafka-cluster/stormconsumers

[tickers]
broker-offsets=60

[lagcheck]
intervals=10
expire-group=604800

[httpserver]
server=on
port=8000
; Alternatively, use listen (cannot be specified when port is)
; listen=host:port
; listen=host2:port2

[smtp]
server=mailserver.example.com
port=25
from=burrow-noreply@example.com
template=/home/user/work/src/github.com/linkedin/Burrow/config/default-email.tmpl

[emailnotifier "bofh@example.com"]
group=local,critical-consumer-group
group=local,other-consumer-group
interval=60

[notify]
interval=10

[httpnotifier]
url=http://notification.server.example.com:9000/v1/alert
interval=60
extra=app=burrow
extra=tier=STG
template-post=/home/user/work/src/github.com/linkedin/Burrow/config/default-http-post.tmpl
template-delete=/home/user/work/src/github.com/linkedin/Burrow/config/default-http-delete.tmpl
timeout=5
keepalive=30

**Comment by toddpalino** [comment]
The other log (the .log file) is really the one that is needed here to see what the problems are.

**Comment by bluebob** [comment]
I'd be very tempted to try with a minimal configuration and rely on the defaults and then add stuff back in, then - as toddpalino says - carefully check logdir/burrow.out. My "minimal config" looks like this:
`[general]
client-id=burrow36

[zookeeper]
hostname=vm0006.localdomain
hostname=vm0007.localdomain
port=2181

[kafka "DEVEL"]
broker=vm0081.localdomain
broker=vm0082.localdomain
broker=vm0038.localdomain
broker=vm0039.localdomain
broker-port=9092
zookeeper=vm0006.localdomain
zookeeper=vm0007.localdomain
zookeeper-port=2181
zookeeper-path=/
zookeeper-offsets=true

[httpserver]
server=on
port=8000`

**Comment by jiminoc** [comment]
change broker-port=10251 to 9092

**Comment by toddpalino** [comment]
Yeah, 10251 is almost certainly wrong. Unless you're me. :)
