### ISSUE TITLE
New topic information isn't picked up until restart

### ISSUE THREAD

**Issue by jiminoc** [linkedin/Burrow#250]
Burrow does not seem to pick up changes to partitions in a topic until it's restarted. 

Steps:

1. clone latest burrow from github (go get)
2. Start burrow up with default configs (changed broker/zk hosts)
3. http://localhost:8000/v2/kafka/local/topic to show my test topic "test.jim1" does not appear
4. create a topic in kafka called "test.jim1" with 1 partition
5. change meta refresh interval to 30 seconds to force faster refresh of client.Topics call
6. webpage shows 1 partition
7. add partition to topic
8. describe topics on kafka shows 2 partitions, after several metadata refreshes burrow still shows 1 partition
9. on burrow restart, both partitions are now reflected.

Is this a regression or? 
Figured I'd ask before digging into the code. 

*updated, new topics works after the meta refresh internal, documenting partition refresh still doesn't

**Comment by jiminoc** [comment]
found it, PR coming

**Comment by toddpalino** [comment]
Resolved by #251

**Comment by DavidLiuXh** [comment]
Also need to do the same thing for addConsumerOffset function
`if int(offset.Partition) >= len(consumerTopicMap) {
		// The partition count must have increased. Append enough extra partitions to our slice
		for i := len(consumerTopicMap); i < partitionCount; i++ {
			consumerTopicMap = append(consumerTopicMap, nil)
		}
	}
`
