### ISSUE TITLE
Burrow 1.0 Rewrite

### ISSUE THREAD

**Issue by toddpalino** [linkedin/Burrow#252]
This is a marker issue so that everyone is aware that I'm in the middle of refactoring the structure of Burrow for a major release. Some of the things that are going into this:

- Making the app easier to wrap inside another app if desired
- Adding support for topic deletion
- Updating dependencies and switching to structured logging
- Cleaning up the modules for ingesting cluster and consumer data, storage, and evaluation
- Make it much easier to extend burrow, including adding new notifiers, storage systems, consumer types, and even clusters.
- Adding tests and reducing the complexity of the code to make this easier
- Making burrow able to run in parallel and share load, rather than running active-standby
- Getting more people at LinkedIn involved in the project

I'm also going to review the issues currently here and flag ones that I'll be working on. I'll be doing the same with the PRs. Unfortunately, this will invalidate all the existing PRs, as the code will be so different that they just won't apply. I'll do my best to pull in the contributions that address issues and features as I do this.

Currently, the work is happening under my fork at https://github.com/toddpalino/Burrow/tree/burrow-1.0. The basic structure of the application is in place, and I'll be working over the next week to move the module code in place

**Comment by jiminoc** [comment]
awesome Todd! Looking forward to this re-write and helping out to test it. Especially the "Making burrow able to run in parallel and share load" part. 

Are you planning on sticking with Sarama or to the Confluent Go Wrapper around librdkafka?

**Comment by JarenGlover** [comment]
@toddpalino wow. great news! Thanks for all your hard work

**Comment by toddpalino** [comment]
@jiminoc, we'll be sticking with Sarama for now. I'm not a huge fan of wrapper libraries, and Shopify has been doing a good job. Plus we've got more in-house experience with it now, and people willing to help make it better when needed.

However, if someone wants to write a consumer module that uses a different client underneath, that will be entirely possible and much easier to do once this gets done.

**Comment by jiminoc** [comment]
makes sense and works for me!

I've always wondered since you can only run 1 burrow right now and you guys have massive installs of Kafka. What kind of hardware are you running burrow on and have you hit any scaling limits with the single node approach? Also, how many burrows are you guys running in production? 1 per cluster or do you have 1 mono-burrow to monitor all the things?

**Comment by jiminoc** [comment]
btw, something that burned us in the past is having burrow start at the latest offset. Imagine the situation (which happens) where you have an outage, things go into an ERR state, burrow gets restarted and comes back up. It will lose all of the consumers in ERR state it was tracking because they won't be submitting offsets back. Starting from earliest, while potentially taking longer on bootup, will give better accuracy in tracking status.

**Comment by toddpalino** [comment]
@jiminoc - we run 2 burrows per "datacenter", with the built-in active/passive model (where one of them is not notifying). Each one of those pairs cover anywhere from 7 to 20 Kafka clusters right now with varying load levels. We're not using huge hardware for this - our slice sizing for Burrow right now is 6GB of memory and 4 CPUs (and most of them go nowhere near that limit)

I don't like the active/passive model for reasons other than scaling, of course. However, in a system like this it's really hard to operate as a true cluster without having a shared data storage system. Since the current model is just an in-memory map (and I'm going to keep that in the initial 1.0 model), there's no real way around it even if you do run active-active. When a burrow in the cluster fails, another one has to re-learn the consumers from there.

I hear you on the start from latest. I already made a change locally in the last couple months to bootstrap the offsets topic instead, and it really doesn't take that long. That'll be a configuration in the new consumer model, with the default being to bootstrap.

**Comment by toddpalino** [comment]
Checkin on the 1.0 progress:

https://github.com/toddpalino/Burrow/tree/burrow-1.0 currently contains the app basics, as well as initial code for the storage and evaluation modules. There's a couple features (like group whitelists) missing from the storage module right now that I'm about to add. But other than that, both the storage and the evaluator modules work, and work together. The next steps will be adding the modules to get both broker and consumer offsets from Kafka (and Zookeeper).

One thing I'm very happy about is that the evaluator now has tests, including a section for passing a set of offsets for a partition and testing all the evaluation routines separately. This means that it's trivial to add a case and test that it evaluates in exactly the way it's expected to. This, combined with the fact that the evaluator logic is a LOT easier to comprehend, will make it much easier to bugfix and prove the correctness of the system.

**Comment by daodennis** [comment]
Hi @toddpalino - when can we expect a 1.0 RC for testing?
- Dennis

**Comment by sam-obeid** [comment]
👋 happy to help testing the rewrite too.

**Comment by toddpalino** [comment]
Work continues apace. Had to slow down a little the past week due to oncall concerns, but the cluster, consumer, and notifiers are all done. The remaining module to write is the HTTP server, and then moving up to the top level to make sure the logic that stitches it all together still works.

@daodennis @sam-obeid - I'm hoping to have something that's testable in about another week. At that point I'll move it over to a branch on this repository (instead of my personal one).

**Comment by toddpalino** [comment]
Getting closer to something for testing. I've started running the new code in a local environment today and so far I've got it consuming from Kafka again, storing, and evaluating. The HTTP interface also works (which is how I know, as I'm not running any notifiers yet).

I'm in the process of fixing a few bugs here and there, and tweaking some of the operation to clean up what I'm seeing. I expected to be pushing a branch for others to start testing by the end of the week.

**Comment by toddpalino** [comment]
OK, the RC branch is there now:
https://github.com/linkedin/Burrow/tree/burrow-1.0-RC

I've been running this version against a cluster internally, and it looks good. I haven't started testing the notifiers yet, however. There is a bit of change to configs, so ask if you need help generating a config file (it's now using Viper, so it's flexible with regards to format).

**Comment by toddpalino** [comment]
The RC branch is looking good. I've been fixing a number of issues as I run it in my test environment. I think we're just about ready to take this out of testing and get a little more experience on it internally. Once we've got it successfully running in our test environment for a week or so, I can work on promoting the RC to a full release.

I'll be working on documentation over the next week, including full documentation of the new config format. The application is still lacking metrics, but that can be added on later if needed.

**Comment by toddpalino** [comment]
First pass godocs are up. Next step is to document the configuration on the wiki, as well as clean up a copy of the HTTP and notifier docs there.

**Comment by toddpalino** [comment]
Alright, the RC is promoted to master now, so I'm closing this out. There are going to be a number of bugs that come up, I'm sure, so I'm not cutting the release just yet.
