### ISSUE TITLE
dependency on pidfile

### ISSUE THREAD

**Issue by daodennis** [linkedin/Burrow#254]
Hi,

When running from systemd/supervisor and burrow doesn't exit cleanly it has to be wrapped into a script to manage its pidfile. This manual intervention is a bit vexing.

My suggestion is to provide a flag to allow for the pidfile to be disabled and let a process manager work out the management of the pidfile.

If there another way to prevent two copies of burrow running at the same time though without the dependance on the pidfile that would obviate the need for the flag though of course, like a zookeeper lock?

However, since burrow also tries to open a socket to listen on it likely won't start anyway if it's in the same network namespace.

**Comment by toddpalino** [comment]
In the 1.0 rewrite, the PID file is now checked as to whether or not the content is valid - if it exists, but the PID specified is not running, it will overwrite the file and start up.

**Comment by toddpalino** [comment]
Resolved by 1.0 rewrite
