### ISSUE TITLE
Burrow container cannot start 

### ISSUE THREAD

**Issue by wyborowiec** [linkedin/Burrow#255]
After using docker-compose procedure:

docker-compose build
docker-compose down; docker-compose up

I cannot access http server on port 8000.  I see that burrow container keeps restarting with following error:

```
burrow_1     | Reading configuration from /etc/burrow/burrow.cfg
burrow_1     | 2017/10/24 08:18:18 Failed to parse gcfg data: open /etc/burrow/burrow.cfg: no such file or directory
```

/etc/burrow/burrow.cfg file exists in the container
docker version: 1.13.0

**Comment by toddpalino** [comment]
Well, the error you're getting is pretty obvious. Either burrow can't see the file at that path, or it doesn't have permissions to read it.

Note that the master branch has just switched over to 1.0 and the config (and the opts) are significantly different. The Docker setup will need a rewrite to support that properly.

**Comment by joway** [comment]
I had created a new image , https://github.com/joway/docker-burrow , you can change the .toml if you want more customized config and rebuild it

**Comment by toddpalino** [comment]
Dockerfile has been updated
