### ISSUE TITLE
Burrow reporting wrong lag stats for a deleted and recreated topic

### ISSUE THREAD

**Issue by balajivenki** [linkedin/Burrow#256]
We had a topic with wrong partition size for a while and so we dropped the topic and recreated with the right number of partitions and few other config change. After the new topic creation lag reported from /consumer/<consumer-group>/lag is way off and incorrect that what we see from kafka-consumer-groups call and sum the total lag for all partitions.

Is this a known issue? Is there a workaround for it?

PS: For the topics that is not deleted and recreated we do not see this problem.

**Comment by toddpalino** [comment]
In general, the current Burrow (0.X) does not support deleted topics at all. It just has no way to know about them and do the right thing.

The 1.0 rewrite fixes this. When a topic is detected as missing from the cluster (checked as often as the full metadata refresh is done, which is configurable), it's explicitly deleted from the cluster and all group data. This means that when it's recreated, it's like it never existed in the first place.

**Comment by toddpalino** [comment]
Resolved by 1.0 rewrite
