### ISSUE TITLE
Burrow 1.0 RC slack notifier with webhook

### ISSUE THREAD

**Issue by daodennis** [linkedin/Burrow#273]
Hi,

in #260 the slack config seems to have moved away from using the webhook url to using the `chat.postMessage` Slack API, but it was more convenient to continue using the webhook url for slack? Seems like https://github.com/linkedin/Burrow/blob/burrow-1.0-RC/core/internal/notifier/slack.go does no allow for this at the moment.

**Comment by daodennis** [comment]
Also, are there reference templates for slack notifier? I can pull them out of the tests or the pre1.0 branch too.

**Comment by toddpalino** [comment]
When I was reimplementing it, it seemed like the preferred way from Slack was to use chat.postMessage. As I don't directly use this notifier, I'm not sure of the difference between the two.

As far as templates, you can refer to the others when creating them. The template is used in Slack  to create the actual message that is sent (the text field). So it's pretty much free-form.

**Comment by niels-s** [comment]
I just stumbled on this issue, after I created this PR #275 which kinda addresses this issue. 
@toddpalino could you have a look?

**Comment by toddpalino** [comment]
Why not just use the http notifier in this case? I never really saw the utility in the slack notifier anyways, as it's just a specialization of the http notifier. We can just remove it entirely and add a doc (and even a sample template) that shows how to send to slack.

**Comment by toddpalino** [comment]
Closed by #278
