### ISSUE TITLE
Reference email template for Burrow 1.0RC?

### ISSUE THREAD

**Issue by daodennis** [linkedin/Burrow#276]
Hi,

What does a reference email template look like for Burrow 1.0RC?

Trying to convert from:
From:
https://github.com/linkedin/Burrow/blob/master/notifier/email_notifier.go#L97 
To:
https://github.com/linkedin/Burrow/blob/burrow-1.0-RC/core/internal/notifier/coordinator.go#L528 and was thinking there might already be one in use in testing at LinkedIn?

**Comment by toddpalino** [comment]
The template should be essentially the same as the existing default template for email, except you should remove the "From:" and "To:" header lines.

We don't use email internally right now, and it's one of the things I haven't explicitly tested in integration yet.

**Comment by daodennis** [comment]
I tried that but I received this error (do you want me to just start a new bug here?)
```

{"level":"error","ts":1510785307.6549482,"msg":"failed to assemble","type":"module","coordinator":"notifier","class":"email","name":"companyname-v2","cluster":"confluent","group":"console-consumer-40905","id":"36a817ea-1062-4910-8045-645009b6bc41","status":"ERR","error":"template: email.tmpl:15:8: executing \"email.tmpl\" at <.Results>: can't evaluate field Results in type struct { Cluster string; Group string; Id string; Start time.Time; Extras map[string]string; Result protocol.ConsumerGroupStatus }"}
```
Which is this line:
https://github.com/linkedin/Burrow/blob/master/config/default-email.tmpl#L7

**Comment by toddpalino** [comment]
Oh, I see what it is. This is probably because the older notifier was sending multiple groups per-email (which had all sorts of other problems with trying to wait for results). Try this:

```
Subject: [Burrow] Kafka Consumer Lag Alert

The Kafka consumer groups you are monitoring are currently showing problems. The following groups are in a problem state (groups not listed are OK):

{{if or (ne 0 .Result.Status) (ne 5 .Result.Status)}}Cluster:  {{Result..Cluster}}
Group:    {{.Group}}
Status:   {{if eq 1 .Result.Status}}OK{{else if eq 1 .Result.Status}}WARNING{{else if eq 2 .Result.Status}}ERROR{{end}}
Complete: {{.Result.Complete}}
Errors:   {{len .Result.Partitions}} partitions have problems
{{range .Result.Partitions}}          {{if eq 1 .Status}}   OK{{if eq 2 .Status}} WARN{{else if eq 2 .Status}}  ERR{{else if eq 3 .Status}} STOP{{else if eq 4 .Status}}STALL{{end}} {{.Topic}}:{{.Partition}} ({{.Start.Timestamp}}, {{.Start.Offset}}, {{.Start.Lag}}) -> ({{.End.Timestamp}}, {{.End.Offset}}, {{.End.Lag}})
{{end}}{{end}}
```
