### ISSUE TITLE
Add to Dockerhub?

### ISSUE THREAD

**Issue by veqryn** [linkedin/Burrow#277]
Would you consider adding this project as a docker image under https://hub.docker.com/u/linkedin/ ?

**Comment by toddpalino** [comment]
I'll check into what I need to do to use the linkedin Docker repo. My guess is it will take some time to find the right person. In the meantime, the 1.0.0 release will start pushing to https://hub.docker.com/r/toddpalino/burrow/

**Comment by keeganwitt** [comment]
Why was this closed?  Shouldn't the image be published under https://hub.docker.com/u/linkedin/burrow/ or https://hub.docker.com/_/burrow/?

**Comment by davispw** [comment]
Reopen this issue?

**Comment by keeganwitt** [comment]
@toddpalino I'm willing to see about adding this to the official library (I've got two other projects I've already done that for) and I can maintain or we can jointly maintain the image.  The Docker Library folks will require LinkedIn's explicit "yes it's OK for Keegan to do this", which we can document here.  So -- you good with that?

**Comment by chrisevett** [comment]
Any updates on this?

**Comment by mfilotto** [comment]
I also would like to use an official image for burrow

**Comment by keeganwitt** [comment]
I've created a Dockerfile that uses vanilla Alpine as the base, but I can't proceed with requesting Docker Library team add it to the official repos unless I get LinkedIn/Microsoft explicit consent.  @toddpalino could you find out if your folks are OK with this?

**Comment by mfilotto** [comment]
This issue is closed but I can find the official linkedin docker image in Docker Hub ?

**Comment by wlisac** [comment]
Would be great to have an official image available. +1

**Comment by v00d00** [comment]
Another comment to say that it would be awesome if official images where published somewhere

**Comment by woj-i** [comment]
Would be great to have an official image available. +1

**Comment by ma82** [comment]
Would be great to have an official image available. +1

**Comment by chrnola** [comment]
+1 an official image would be nice.

Glad to see there's now an image on [GitHub Packages](https://github.com/linkedin/Burrow/packages/104930), but the need for authenticated pulls is an obstacle for many I'm sure.

**Comment by keeganwitt** [comment]
I emailed Todd about my offer to maintain the image.

**Comment by keeganwitt** [comment]
I never heard back.

I'm willing to keep a personal registry on DockerHub updated, if that'd be helpful for folks (though at some point we might run into pull limits with Docker's new terms of service). Nearly all the images on DockerHub are years old except https://hub.docker.com/r/tgbyte/burrow which I couldn't find a source repo for.  Even the repo from @toddpalino hasn't been updated.  Let me know if adding a new repo is something folks would like. I know using a personal repo isn't ideal (it'd make me a little nervous too), but other than telling people to build their own images, I don't know what else I can do to help.

**Comment by chrnola** [comment]
The authentication issue may be mitigated now with the recent launch of the [GitHub Container Registry](https://github.blog/2020-09-01-introducing-github-container-registry/).

**Comment by keeganwitt** [comment]
Ah, good point.  I don't believe Burrow has migrated to the container registry yet, but it sounds like that'd solve that problem once they do.

Assuming that's able to be done soonish, I don't see a need to make a personal registry, unless someone can think of an issue I haven't thought of.
