### ISSUE TITLE
burrow install and bin path issue

### ISSUE THREAD

**Issue by arunsingh** [linkedin/Burrow#280]
For installing burrow utility I have to install golang, I followed this link given to install golang https://github.com/linkedin/Burrow && followed this for path environment setting export GOPATH=/gopath >> http://www.idata.co.il/2017/01/monitoring-kafka-consumer-lag-with-burrow/ --> this path setting is having some issue. Kindly help me suggest and resolve this path env issue --> Below is the error,when I tried to do $#go install after $# gpm install, Still not sure is it path setting issue or some other issue unable to give terminology for it.

# go install
# github.com/golang/snappy
../../golang/snappy/decode_amd64.s:10 6a: No such file or directory: textflag.h
# github.com/pierrec/lz4
../../pierrec/lz4/lz4.go:88: undefined: sync.Pool
# github.com/cihub/seelog
../../cihub/seelog/writers_rollingfilewriter.go:166: gr.Reset undefined (type *"github.com/cihub/seelog/archive/gzip".Reader has no field or method Reset)
root@arbok:/gopath/src/github.com/linkedin/burrow#

**Comment by daodennis** [comment]
Hi,

If you are new to golang and you have it already installed at least, this worked for me for building a binary based off of the master branch.
```
# Make a go directory in your home directory
$ mkdir $HOME/go/
$ cd $HOME/go # if you create this directory you don't need to set $GOPATH
$ go get github.com/linkedin/Burrow/
$ go build github.com/linkedin/Burrow
$ cp $HOME/go/src/github.com/linkedin/Burrow/config/burrow.cfg $HOME/go/bin/burrow.cfg 
# Below is where the Burrow utility lives
$ $HOME/go/bin/Burrow -config $HOME/go/bin/burrow.cfg

The configuration file will have to be edited for your Kafka environment though 
https://github.com/linkedin/Burrow/wiki for the version that is on the master branch.
There is a 1.0 of Burrow that is coming soon and the configuration changes slightly.

**Comment by arunsingh** [comment]
When I tried to go by your instruction, getting stuck here: See the output


puser@arbok:~$ mkdir $HOME/go/
puser@arbok:~$ cd $H
$HISTCMD         $HISTFILE        $HISTSIZE        $HOME            $HOSTTYPE        
$HISTCONTROL     $HISTFILESIZE    $HISTTIMEFORMAT  $HOSTNAME        
puser@arbok:~$ cd $HOME/go
puser@arbok:~/go$ go get https://github.com/linkedin/Burrow/
package https:/github.com/linkedin/Burrow: unrecognized import path "https:/github.com/linkedin/Burrow"
puser@arbok:~/go$ go get github.com/linkedin/Burrow/
package github.com/linkedin/Burrow: mkdir /usr/local/sbin/src: permission denied
puser@arbok:~/go$ sudo go get github.com/linkedin/Burrow/
[sudo] password for puser: 
package github.com/linkedin/Burrow: cannot download, $GOPATH not set. For more details see: go help gopath
puser@arbok:~/go$

**Comment by daodennis** [comment]
@arunsingh can you type `go env` and paste the results, maybe that will help us with why directory is involved? `mkdir /usr/local/sbin/src: permission denied`. This should have worked `go get github.com/linkedin/Burrow/`. I wonder if your GOPATH or some other variable is still set to that wacky `/go` or something else from that article you referenced.

**Comment by arunsingh** [comment]
@daodennis 

As root user : go env

`root@arbok:~# go env
GOARCH="amd64"
GOBIN=""
GOCHAR="6"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH=""
GORACE=""
GOROOT="/usr/lib/go"
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
TERM="dumb"
CC="gcc"
GOGCCFLAGS="-g -O2 -fPIC -m64 -pthread"
CXX="g++"
CGO_ENABLED="1"
root@arbok:~# env`

As non-root user:

`puser@arbok:~$ go env
GOARCH="amd64"
GOBIN=""
GOCHAR="6"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin:/usr/bin:/usr/local/go"
GORACE=""
GOROOT="/usr/lib/go"
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
TERM="dumb"
CC="gcc"
GOGCCFLAGS="-g -O2 -fPIC -m64 -pthread"
CXX="g++"
CGO_ENABLED="1"
`

**Comment by daodennis** [comment]
@arunsingh `GOPATH` is not like `PATH`. You only should set one directory and not a list of directories, though I suspect you might be able to. Here is how I would proceed: unset the `GOPATH` variable and make a directory inside your $HOME called `go`.  If you must set GOPATH at that point this would be the correct value `export GOPATH="$HOME/go"`

**Comment by daodennis** [comment]
Also, as a matter of practice I would avoid using `sudo` with the go toolchain, there could be unintended consequences.

**Comment by toddpalino** [comment]
There are now downloadable binary releases, so I'm going to close this out.

Please note @daodennis's comments here about not running as sudo, as well as your GOPATH.
