### ISSUE TITLE
Monitoring multiple Kafka clusters using HTTP Notifier

### ISSUE THREAD

**Issue by dineshsriram** [linkedin/Burrow#288]
While trying to monitor multiple Kafka clusters (4 in my case) using HTTP Notifier, I noticed that the kafka cluster name is not sent as part of every update. Sample output below:

```
2017/12/01 10:29:08 {"api_key":"","app":"burrow","block":false,"events":[{"id":"52ab9bcd-989d-4a5bb9ed-60580c527ecc",
"event":{"severity": "ERR","tier":"STG","group":"test-group","start":"Nov 30, 2017 17:58:40 UTC",
"complete":true,"partitions":[{"topic":"test-topic","partition":3,"status":"STALL","start:{"offset":568696,"timestamp":1512142136671,"lag":57888,"max_offset":568696},"end:{"offset":568696,"timestamp":1512142146673,"lag":57888,"max_offset":568696 }}]}}]} 
```
- Is there a way to send this information along to associate consumer groups with their clusters?
- If not, is it expected that we run multiple burrow instances?

**Comment by toddpalino** [comment]
You can include the cluster by changing the template to include `{{.Cluster}}` somewhere. You're just using the sample template right now.

**Comment by dineshsriram** [comment]
Thank you. I spoke too soon before looking at https://github.com/linkedin/Burrow/wiki/Templates

Looking forward to the 1.0 version!
