### ISSUE TITLE
What Kafka version is Burrow currently supported?

### ISSUE THREAD

**Issue by h-ngo** [linkedin/Burrow#298]
I tried to look up in the documentation, but it wasn't mentioned.

**Comment by toddpalino** [comment]
Burrow supports Kafka client versions through the 0.10 series right now. PR #297 is open to add 0.11, but it needs a tweak.

This should also get added to the docs under the client-profile section

**Comment by toddpalino** [comment]
Configuration doc has been updated. Note that it's been updated contingent on #297 getting pushed.
