### ISSUE TITLE
compiles but does not start

### ISSUE THREAD

**Issue by SnertSnert** [linkedin/Burrow#305]
master and rc1 branch compile , but no config file is found when Burrow is started with config file parametr.
`Reading configuration from /home/xxx/go/src/github.com/linkedin/Burrow/config/
Failed reading configuration: Config File "burrow" Not Found in "[/home/xxx/go/src/github.com/linkedin/Burrow/config]"
Burrow failed at December 8, 2017 at 9:27am (CET)`
and yes, there is a config file.

**Comment by SnertSnert** [comment]
`go version
go version go1.9.2 linux/amd64
`
` go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/mruppert/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build116348454=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
`

**Comment by SnertSnert** [comment]
`ll
total 36
-rw-rw-r-- 1  1671 Dec  8 08:40 burrow
-rw-rw-r-- 1  1503 Dec  8 09:18 burrow.cfg
-rw-rw-r-- 1   800 Dec  8 08:40 default-email.tmpl
-rw-rw-r-- 1   106 Dec  8 08:40 default-http-delete.tmpl
-rw-rw-r-- 1   388 Dec  8 08:40 default-http-post.tmpl
-rw-rw-r-- 1   386 Dec  8 08:40 default-slack-delete.tmpl
-rw-rw-r-- 1   382 Dec  8 08:40 default-slack-post.tmpl
`
`[mruppert@kilobond config]$ Burrow
Reading configuration from .
Failed reading configuration: Config File "burrow" Not Found in "[/home/mruppert/go/src/github.com/linkedin/Burrow/config]"
Burrow failed at December 8, 2017 at 9:45am (CET)`

**Comment by ejpearson** [comment]
@SnertSnert 

It took me a little while to figure out Burrow 1.0 no longer uses burrow.cfg but rather uses burrow.toml.  The current error message also didn't help me either.

The expected structure is different too, if you have an old burrow.cfg.  See the example in the config directory.  It wasn't too hard to modify my burrow.cfg to burrow.toml and get 1.0 running.

I hope this helps.

**Comment by toddpalino** [comment]
Yes, this is correct. You will need to convert the config to a TOML file (or another supported format like JSON). Please see the Configuration wiki page for more details: https://github.com/linkedin/Burrow/wiki/Configuration

**Comment by toddpalino** [comment]
Closing this out, as the change to config is the correct answer
