### ISSUE TITLE
Release binary is not statically-linked and does not run in Alpine

### ISSUE THREAD

**Issue by everesio** [linkedin/Burrow#307]
➜  ~ docker run -it toddpalino/burrow:1.0.0        
standard_init_linux.go:185: exec user process caused "no such file or directory"
➜  ~ docker run -it toddpalino/burrow:1.0.0 /bin/sh
/app # ldd burrow 
	/lib64/ld-linux-x86-64.so.2 (0x56248176e000)
	libpthread.so.0 => /lib64/ld-linux-x86-64.so.2 (0x56248176e000)
	libc.so.6 => /lib64/ld-linux-x86-64.so.2 (0x56248176e000)

**Comment by sorinescu** [comment]
👍

**Comment by abrugh** [comment]
`docker build -t <your tag> .` builds a properly working image now. Would be cool if that one ended up on an official docker hub instead of what's there now. But at least you can make one without installing Go locally.

**Comment by laymain** [comment]
A new docker image has been published on the docker hub but it has the same issue
https://hub.docker.com/r/toddpalino/burrow/tags/

**Comment by macropin** [comment]
This caught me out too. Why are the releases not statically linked?

**Comment by hoseyneil** [comment]
so is there one that works?

**Comment by bai** [comment]
I think I've fixed it in master, I'm looking for feedback at https://github.com/linkedin/Burrow/issues/568#issuecomment-574504257. If this is still relevant for you, please take a look 🙏

**Comment by bai** [comment]
This should have been resolved. Please reopen if you think otherwise 🙏
