### ISSUE TITLE
Why no results are returned for /v2/kafka/cluster_name/consumer?

### ISSUE THREAD

**Issue by DavidLiuXh** [linkedin/Burrow#31]
I do have a group，but return {"error":false,"message":"consumer list returned","consumers":[]} when get /v2/kafka/cluster_name/consumer

**Comment by DavidLiuXh** [comment]
I found cause of the problem：
1. need to set zookeeper-offsets=true under [kafka cluster-name] in the configuration file;
2. if set zookeeper-path=/ unser [kafka cluser-name] in the configuration file, then in zookeeper.go 
    consumerGroups, _, err := zkClient.conn.Children(zkClient.app.Config.Kafka[zkClient.cluster].ZookeeperPath + "/consumers")
   => consumerGroups,_,err := zkClient.conn.Children("//consumers"),

  The path “//consumers” of znode does not exist.

**Comment by toddpalino** [comment]
Thanks. The double slash issue has been fixed in master now.
