### ISSUE TITLE
log warning: failed to decode

### ISSUE THREAD

**Issue by sam-obeid** [linkedin/Burrow#313]
Any idea what's this warning is? `   "msg":"failed to decode", "reason":"consumer_protocol_version",`
I see about 2 warns/min similar this one:

```
{
   "level":"warn",
   "ts":1513803928.0648108,
   "msg":"failed to decode",
   "type":"burrow-web",
   "coordinator":"consumer",
   "class":"kafka",
   "name":"myconsumer",
   "offset_topic":"__consumer_offsets",
   "offset_partition":5,
   "offset_offset":4897430226,
   "message_type":"metadata",
   "group":"consumer_group_etl3",
   "protocol_type":"consumer",
   "generation":283366,
   "protocol":"range",
   "leader":"consumer_group_etl3-0661bc66-73aa-4243-a84e-239dc8a8d51b",
   "reason":"consumer_protocol_version",
   "stream":"stdout",
   "application":"kafka"
}
```

I am running burrow commit#: https://github.com/linkedin/Burrow/commit/3a4372f5c80ee8426dc85cf3edd1cea735dba119

burrow configuration:
```
[zookeeper]
servers=["zk-0:2181","zk-1:2181","zk-2:2181"]
timeout=6
root-path="/burrow/notifier"

[client-profile.myburrow_client]
kafka-version="0.11.0.1"
client-id="burrow_client"

[httpserver.mylistener]
address=":8000"
timeout=300

[storage.mystorage]
class-name="inmemory"

[cluster.cluster1]
class-name="kafka"
servers=["kafka-0:9092","kafka-1:9092","kafka-2:9092","kafka-3:9092","kafka-4:9092"]

[consumer.myconsumer]
class-name="kafka"
cluster="cluster1"
servers=["kafka-0:9092","kafka-1:9092","kafka-2:9092","kafka-3:9092","kafka-4:9092"]
client-profile="myburrow_client"
group-blacklist="^(console-consumer-).*$"

```

burrow is still working and reporting metrics but this warn is logged continuously as approx. 2 times/min

**Comment by toddpalino** [comment]
The `failed to decode` warning is because Burrow was not able to properly decode a message in the __consumer_offsets topic. The rest of those fields give you information about which message it was, and how far it got in decoding. So offset 4897430226 in __consumer_offsets:5 had a problem. That's a group metadata message, and the `reason` field indicates that the consumer_protocol_version either wasn't an int16, or it wasn't 0 (which is the only version that Burrow understands).

Now, as far as why, this could be a couple things (since you're seeing it repeatedly, and not as a one-off). There may be a new consumer_protocol version from open source Kafka that we haven't picked up yet. That will require writing some code and tests to detect it. Or it could be you have a consumer that's using something custom.

**Comment by thomaslee** [comment]
@toddpalino I ran into this using sarama-cluster, which reports "version 1" assignments. Have reason to believe this is a bug in their consumer, but that may not actually matter to Burrow right now: after some digging, came across this: https://github.com/apache/kafka/blob/14a3d69d9463b2aa26776329610f8fc5eddd0202/clients/src/main/java/org/apache/kafka/clients/consumer/internals/ConsumerProtocol.java#L141-L147

The comment there (present as of the latest tagged release) implies the official clients are assuming backward compatibility for any assignments where version >0. So at least for now Burrow _should_ be safe assuming that any changes to that data structure will be additive, right?

Separately, I'll be opening a bug against sarama-cluster to try and get clarification as to whether they're reporting assignments as "version 1" intentionally for reasons I don't understand.

**Comment by thomaslee** [comment]
JavaDoc comment on ConsumerProtocol.java seems to back my theory up:

```
 * The current implementation assumes that future versions will not break compatibility. When
 * it encounters a newer version, it parses it using the current format. This basically means
 * that new versions cannot remove or reorder any of the existing fields.
```

**Comment by thomaslee** [comment]
Opened a PR to attempt to address this since we had to make the change ourselves anyway -- expect it will fail tests, but wanted to get your thoughts on the approach (& the problem in general) before committing too much time to it.
