### ISSUE TITLE
Stuck on opening tunnel

### ISSUE THREAD

**Issue by Hax4us** [linkedin/Burrow#317]
After the run script , stuck on message "opening tunnel"

**Comment by toddpalino** [comment]
You're going to need to provide far more information than this for anyone to be able to help you. Log files and configuration, to start with.

**Comment by Hax4us** [comment]
Sorry dude .....I checked under your script and I saw there was ssh command... I had not openssh installed so..that was the prob...and bcz of dev/null error was not showed  in terminal...
Well thnx for this great tool

**Comment by parruda** [comment]
@Hax4us I think you were looking for help with [Burrow.io](https://burrow.io)?
This is LinkedIn's Kafka consumer project!

Anyways, if you still need help with Burrow.io, drop me a line!
