### ISSUE TITLE
Please supply a binary version for download please!

### ISSUE THREAD

**Issue by jiming** [linkedin/Burrow#324]
In China, golang.org is blocked by GFW. So it is hard to compile one from source.

Please kindly make a binary version of burrow, so we can download it directyly. Just like dep does.

https://github.com/golang/dep/releases

Thanks!

**Comment by daodennis** [comment]
I think they are here: https://github.com/linkedin/Burrow/releases

**Comment by toddpalino** [comment]
Yup, binaries are there as of the 1.0 release. Built automaticall.
