### ISSUE TITLE
How to delete a consumer group which name is empty string?

### ISSUE THREAD

**Issue by jiming** [linkedin/Burrow#349]
For some reason I am not aware of. My kafka has a consumer group which name is empty.

I am using kafka 1.0 and config of burrow is 

```
[client-profile.test]
client-id="burrow-test"
kafka-version="0.10.0"

```

```json
{
    "error": false,
    "message": "consumer list returned",
    "consumers": ["", "test-auto"],
    "request":
    {
        "url": "/v3/kafka/local/consumer",
        "host": "vm10-10-0-50.ksc.com"
    }
}
```

Is there any way for me to remove the empty consumer group?

Thanks a lot and have a nice day!
Jiming

**Comment by toddpalino** [comment]
Not outside of bouncing Burrow (and clearing whatever condition caused it to be picked up in the first place). The API endpoint won't let you do it.

**Comment by jiming** [comment]
Thanks. I'll try some other method!
