### ISSUE TITLE
How to make Burrow package (for distribution)?

### ISSUE THREAD

**Issue by MichaelScofield** [linkedin/Burrow#36]
I want to install Burrow in our production environment. The environment is under restrict network control, it's not possible to download source codes or dependencies from github or via "go get", gpm. So I have to pack up the whole files (including dependencies) and upload them to the machines.

I'm new to Go, so I'm wondering is there any ways to make a rich Burrow package that includes everything Burrow needed for running? 

Thanks in advance!

**Comment by DavidLiuXh** [comment]
go build can produced executable file, it not depend on golang environment.

**Comment by toddpalino** [comment]
@DavidLiuXh is correct. Golang compiles down to a single executable with no dependencies. You can then create a deployment artifact with this and just set up the config and logs directories.
