### ISSUE TITLE
Publish new image docker

### ISSUE THREAD

**Issue by BDeus** [linkedin/Burrow#373]
See https://github.com/linkedin/Burrow/issues/307
The dockerfile is correct now but in public repo the image has not been updated
Could it be possible to do it ?

**Comment by bai** [comment]
I think I've fixed it in master, I'm looking for feedback at https://github.com/linkedin/Burrow/issues/568#issuecomment-574504257. If this is still relevant for you, please take a look 🙏

**Comment by oxr463** [comment]
I think this has been resolved?

See: https://github.com/linkedin/Burrow/packages/104930?version=v1.3.4

**Comment by bai** [comment]
Good point, thanks.
