### ISSUE TITLE
Unable to connect to cluster with TLS

### ISSUE THREAD

**Issue by jackson-theisen** [linkedin/Burrow#374]
I am experiencing issues connecting to my brokers which have SSL client auth enabled. I have confirmed that I am able to produce/consume messages with both the console producer/consumer and this [python client](https://github.com/dpkp/kafka-python). When I configure Burrow using the exact same cert, key, and CA files, I get the following error in Burrow: 
```
{"level":"error","ts":1521577396.2937741,"msg":"failed to start client","type":"module","coordinator":"cluster","class":"kafka","name":"local","error":"kafka: client has run out of available brokers to talk to (Is your cluster reachable?)"}
```
I extracted the keys from the `kafka.client.keystore.jks` file using the following commands:
certfile:
```
keytool -exportcert -alias localhost -keystore kafka.client.keystore.jks \
        -rfc -file certificate.pem
```
keyfile:
```
keytool -v -importkeystore -srckeystore kafka.client.keystore.jks \
        -srcalias localhost -destkeystore cert_and_key.p12 -deststoretype PKCS12
openssl pkcs12 -in cert_and_key.p12 -nocerts -nodes -out key.pem
```
CAfile:
```
keytool -exportcert -alias CARoot -keystore kafka.client.keystore.jks -rfc -file CARoot.pem
```

I am wondering if there is a place that I can get a more descriptive log output or if there is more thorough documentation on how to configure Burrow with TLS than what is provided in the wiki. Here is what my config file looks like:

```
[general]
pidfile="burrow.pid"
stdout-logfile="burrow.out"

[logging]
filename="logs/burrow.log"
level="debug"
maxsize=100
maxbackups=30
maxage=10
use-localtime=false
use-compression=true

[zookeeper]
servers=[ "server1:2181" ]
timeout=6
root-path="/burrow"
client-profile="test"

[client-profile.test]
kafka-version="1.0.0"
client-id="burrow-lagchecker"
tls="mytlsprofile"

[tls.mytlsprofile]
certfile="/path/to/cert/certificate.pem"
keyfile="/path/to/key/test-cert/key.pem"
cafile="/path/to/cafile/CARoot.pem"
noverify=false

[cluster.local]
class-name="kafka"
servers=[ "server1:9093" ]
client-profile="test"
topic-refresh=120
offset-refresh=30

[consumer.local]
class-name="kafka"
cluster="local"
servers=[ "server1:9093" ]
client-profile="test"
group-blacklist="^(console-consumer-|python-kafka-consumer-|quick-).*$"
group-whitelist=""

[httpserver.default]
address=":8000"
timeout=300

[storage.default]
class-name="inmemory"
workers=20
intervals=15
expire-group=604800
min-distance=1

[notifier.default]
class-name="email"
interval=300
threshold=1 # StatusOK
timeout=5
send-close=false
template-open="config/default-email.tmpl"
server="xxxxx"
port=port
from="xxxxx"
to="xxxxx"
```

**Comment by tommyJimmy87** [comment]
+1

**Comment by opsj** [comment]
@toddpalino are you able to provide any insight on this?

**Comment by tommyJimmy87** [comment]
I resolved with :  
```noverify=true```

**Comment by opsj** [comment]
@tommyJimmy87 Any chance you'd be willing to share your configs with me? Also, what steps did you take to extract the cert and key in `.pem` format from the `.jks` files used in kafka?

**Comment by tommyJimmy87** [comment]
Actually you don't need the certificates, which are necessary just if you want configure the burrow API in SSL (If i've figure out well) . I have kafka my Kafka Cluster with SASL_SSL .

Here the config (This work well in my case) : 
````
[general]
        pidfile="burrow.pid"
        access-control-allow-origin="*"

        [logging]
        level="debug"
        maxsize=100
        maxbackups=30
        maxage=10
        use-localtime=false
        use-compression=true

        [zookeeper]
        servers=[ "{{.zkurl}}" ]
        timeout=6
        root-path="/{{.kafkaZNode}}"

        [client-profile.myclient]
        kafka-version="1.0.0"
        client-id="myclient"
        sasl="mysaslprofile"
        tls="mytlsprofile"

        [tls.mytlsprofile]
        noverify=true

        [sasl.mysaslprofile]
        username="{{.kafkauser}}"
        password="{{.kafkasecret}}"
        handshake-first=true

        [cluster.local]
        class-name="kafka"
        servers=[ "{{.kafkaurl}}" ]
        client-profile="myclient"
        topic-refresh=120
        offset-refresh=30

        [consumer.local]
        class-name="kafka"
        cluster="local"
        servers=[ "{{.kafkaurl}}" ]
        client-profile="myclient"
        group-blacklist="^(console-consumer-|python-kafka-consumer-|quick-).*$"
        group-whitelist=""

        [httpserver.default]
        address=":8000"
        timeout=300

        [storage.default]
        class-name="inmemory"
        workers=20
        intervals=15
        expire-group=10000000604800
        min-distance=1

````

**Comment by JackDavidson** [comment]
Here is a config that worked for me. I have kafka on a non-standard port, so you probably will want to change that:

[zookeeper]
servers=[ "kafka-4:2181" ]
timeout=6
root-path="/burrow"
client-profile="local"

[logging]
level="debug"
filename="/burrow.log"

[cluster.local]
class-name="kafka"
servers=[ "kafka-4:9093" ]
topic-refresh=60
offset-refresh=30
client-profile="local"

[consumer.local]
class-name="kafka"
cluster="local"
servers=[ "kafka-4:9093" ]
group-blacklist="^(console-consumer-|python-kafka-consumer-).*$"
group-whitelist=""
client-profile="local"

[consumer.local_zk]
class-name="kafka_zk"
cluster="local"
servers=[ "kafka-4:2181" ]
zookeeper-path="/local"
zookeeper-timeout=30
group-blacklist="^(console-consumer-|python-kafka-consumer-).*$"
group-whitelist=""
client-profile="local"

[httpserver.default]
address=":8000"

[client-profile.local]
kafka-version="1.1.0"
tls="tlsonly"

[tls.tlsonly]
certfile="/etc/burrow/client.crt"
keyfile="/etc/burrow/client.key"
cafile="/etc/burrow/ca-cert.crt"
noverify=true

**Comment by argeiger** [comment]
+1

**Comment by klsnreddy** [comment]
@JackDavidson  Do we need to extract crt files from jks file? if yes how do we do that?
