### ISSUE TITLE
Consumers of slow topics are marked as error

### ISSUE THREAD

**Issue by josselin-c** [linkedin/Burrow#38]
Hello,

I have some Kafka topics with very little traffic (a few messages per day if any) and consumer group consuming theses are marked as failing by the HTTP /lag endpoint. 
Maybe before marking the consumer group as ERR/STOP burrow should check the current topic offset to check if there is data to consume.

```
$ curl http://localhost/v2/kafka/dev/consumer/mygroup/lag
{
    "error": false, 
    "message": "consumer group status returned", 
    "status": {
        "cluster": "dev", 
        "complete": true, 
        "group": "mygroup", 
        "maxlag": null, 
        "partitions": [
            {
                "end": {
                    "lag": 0, 
                    "offset": 645853, 
                    "timestamp": 1450153877135
                }, 
                "partition": 0, 
                "start": {
                    "lag": 0, 
                    "offset": 645750, 
                    "timestamp": 1450142015472
                }, 
                "status": "STOP", 
                "topic": "slowtopic"
            }, 
            {
                "end": {
                    "lag": 0, 
                    "offset": 840126, 
                    "timestamp": 1450161779653
                }, 
                "partition": 1, 
                "start": {
                    "lag": 0, 
                    "offset": 840011, 
                    "timestamp": 1450161698730
                }, 
                "status": "STOP", 
                "topic": "slowtopic"
            }
        ], 
        "status": "ERR"
    }
}

$ curl http://localhost/v2/kafka/dev/topic/slowtopic
{
    "error": false, 
    "message": "broker topic offsets returned", 
    "offsets": [
        645854, 
        840127
    ]
}
```

**Comment by toddpalino** [comment]
This is related to #35. When the consumer commits offsets automatically to Kafka, it does it on a regular interval regardless of whether or not the offset has changed (messages have been consumed). When the consumer commits offsets to Zookeeper, it does not write to Zookeeper if the offset has not changed. This results in being unable to determine the difference between no data coming in and the consumer being stopped.

Adding an additional check for STOP to compare the last committed offset to the broker offset may work, at least mostly. It's still possible to end up in an error state if a new message has come in during the last minute (or whatever the consumer's offset commit interval is).

**Comment by toddpalino** [comment]
I've just added this check to master. Basically, if the evaluation routine is about to mark a partition as stopped, it will first check whether or not the consumer offset for the partition is equal to the broker offset. If it is, the partition is considered to be good instead. I've got this running internally now, and it seems to have eliminated some alert flapping on a slow topic with a ZK consumer that I set up. Let me know if it works for you.

**Comment by toddpalino** [comment]
After running this for a day, we're still seeing some false hits. I believe the reason is that the consumer in question is dealing with very bursty data, and it's doing manual offset commits. Even with this check, we are often hitting the timing issue that I mentioned.

I think a better solution is a combination of this and #35. That is, on every evaluation, we check if the broker offset is equal to the consumer offset. If it is, we insert an artificial offset commit at the present time. This continues to roll the offset ring forwards, which I believe gets us around the timing issue as the partition will never be detected as stopped (since the timestamp for the last commit continues to advance). It also has the benefit of getting a ZK consumer to "complete" faster for a slow topic without overly polluting the data.

**Comment by toddpalino** [comment]
Trunk now contains a number of fixes with regards to this issue. I'm going to close it out as complete, and I'll put a release together shortly as this is a pretty decent change
