### ISSUE TITLE
Godeps file does not exist Error on gpm install

### ISSUE THREAD

**Issue by ravindratcs** [linkedin/Burrow#381]
Downloaded the latest code and when tried to download and build the project it is throwing error

**[root@or1hdp584 Burrow]# pwd**
/workspace/go/src/github.com/linkedin/Burrow
**[root@or1hdp584 Burrow]# gpm install**
>> Godeps file does not exist.
>> All Done
**[root@or1hdp584 Burrow]# go install**
core/internal/storage/inmemory.go:20:2: cannot find package "github.com/OneOfOne/xxhash" in any of:
        /usr/local/go/src/github.com/OneOfOne/xxhash (from $GOROOT)
        /workspace/go/src/github.com/OneOfOne/xxhash (from $GOPATH)
core/internal/httpserver/config.go:16:2: cannot find package "github.com/julienschmidt/httprouter" in any of:
        /usr/local/go/src/github.com/julienschmidt/httprouter (from $GOROOT)
        /workspace/go/src/github.com/julienschmidt/httprouter (from $GOPATH)
core/internal/evaluator/caching.go:18:2: cannot find package "github.com/karrick/goswarm" in any of:
        /usr/local/go/src/github.com/karrick/goswarm (from $GOROOT)
        /workspace/go/src/github.com/karrick/goswarm (from $GOPATH)
core/internal/helpers/sarama.go:19:2: cannot find package "github.com/spf13/viper" in any of:
        /usr/local/go/src/github.com/spf13/viper (from $GOROOT)
        /workspace/go/src/github.com/spf13/viper (from $GOPATH)
core/internal/helpers/coordinators.go:21:2: cannot find package "github.com/stretchr/testify/mock" in any of:
        /usr/local/go/src/github.com/stretchr/testify/mock (from $GOROOT)
        /workspace/go/src/github.com/stretchr/testify/mock (from $GOPATH)
core/protocol/protocol.go:21:2: cannot find package "go.uber.org/zap" in any of:
        /usr/local/go/src/go.uber.org/zap (from $GOROOT)
        /workspace/go/src/go.uber.org/zap (from $GOPATH)
core/internal/httpserver/coordinator.go:32:2: cannot find package "go.uber.org/zap/zapcore" in any of:
        /usr/local/go/src/go.uber.org/zap/zapcore (from $GOROOT)
        /workspace/go/src/go.uber.org/zap/zapcore (from $GOPATH)
core/logger.go:25:2: cannot find package "gopkg.in/natefinch/lumberjack.v2" in any of:
        /usr/local/go/src/gopkg.in/natefinch/lumberjack.v2 (from $GOROOT)
        /workspace/go/src/gopkg.in/natefinch/lumberjack.v2 (from $GOPATH)

**Comment by dkoding** [comment]
I get the same:

Step 9/16 : RUN cd $SRCPATH/github.com/linkedin/Burrow && gpm install && go install
 ---> Running in a606b068b162
>> Godeps file does not exist.
>> All Done
core/internal/storage/inmemory.go:20:2: cannot find package "github.com/OneOfOne/xxhash" in any of:
        /usr/local/go/src/github.com/OneOfOne/xxhash (from $GOROOT)
        /go/src/github.com/OneOfOne/xxhash (from $GOPATH)
core/internal/cluster/kafka_cluster.go:17:2: cannot find package "github.com/Shopify/sarama" in any of:
        /usr/local/go/src/github.com/Shopify/sarama (from $GOROOT)
        /go/src/github.com/Shopify/sarama (from $GOPATH)
core/internal/httpserver/config.go:16:2: cannot find package "github.com/julienschmidt/httprouter" in any of:
        /usr/local/go/src/github.com/julienschmidt/httprouter (from $GOROOT)
        /go/src/github.com/julienschmidt/httprouter (from $GOPATH)
core/internal/evaluator/caching.go:18:2: cannot find package "github.com/karrick/goswarm" in any of:
        /usr/local/go/src/github.com/karrick/goswarm (from $GOROOT)
        /go/src/github.com/karrick/goswarm (from $GOPATH)
core/internal/notifier/coordinator.go:37:2: cannot find package "github.com/pborman/uuid" in any of:
        /usr/local/go/src/github.com/pborman/uuid (from $GOROOT)
        /go/src/github.com/pborman/uuid (from $GOPATH)
core/protocol/protocol.go:20:2: cannot find package "github.com/samuel/go-zookeeper/zk" in any of:
        /usr/local/go/src/github.com/samuel/go-zookeeper/zk (from $GOROOT)
        /go/src/github.com/samuel/go-zookeeper/zk (from $GOPATH)
core/internal/helpers/sarama.go:19:2: cannot find package "github.com/spf13/viper" in any of:
        /usr/local/go/src/github.com/spf13/viper (from $GOROOT)
        /go/src/github.com/spf13/viper (from $GOPATH)
core/internal/helpers/coordinators.go:21:2: cannot find package "github.com/stretchr/testify/mock" in any of:
        /usr/local/go/src/github.com/stretchr/testify/mock (from $GOROOT)
        /go/src/github.com/stretchr/testify/mock (from $GOPATH)
core/protocol/protocol.go:21:2: cannot find package "go.uber.org/zap" in any of:
        /usr/local/go/src/go.uber.org/zap (from $GOROOT)
        /go/src/go.uber.org/zap (from $GOPATH)
core/internal/httpserver/coordinator.go:32:2: cannot find package "go.uber.org/zap/zapcore" in any of:
        /usr/local/go/src/go.uber.org/zap/zapcore (from $GOROOT)
        /go/src/go.uber.org/zap/zapcore (from $GOPATH)
core/logger.go:25:2: cannot find package "gopkg.in/natefinch/lumberjack.v2" in any of:
        /usr/local/go/src/gopkg.in/natefinch/lumberjack.v2 (from $GOROOT)
        /go/src/gopkg.in/natefinch/lumberjack.v2 (from $GOPATH)
The command '/bin/sh -c cd $SRCPATH/github.com/linkedin/Burrow && gpm install && go install' returned a non-zero code: 1

**Comment by toddpalino** [comment]
Please refer to the project readme file. Burrow no longer uses GPM, it now uses dep.
