### ISSUE TITLE
New release/tag

### ISSUE THREAD

**Issue by charkost** [linkedin/Burrow#383]
Hello @toddpalino, 

It will be really useful for us to have a new tag. The master branch seems to contain ~10 commits 
with important bug fixes.

We intent to use the new tag to package burrow for debian. We have been working on packaging burrow's dependencies for quite a while and now all deps are ready. 

A new tag will help us give a pretty upstream version to the package instead of using some ugly combination of date + commit ID as a symbol pointing to the latest commit in master.

**Comment by toddpalino** [comment]
Absolutely agree. Look out for it shortly. There's a CI issue that's causing builds to fail that I need to investigate first.

**Comment by charkost** [comment]
Ready :) https://packages.debian.org/sid/burrow
