### ISSUE TITLE
Is it possible to send custom headers in http notifiers?

### ISSUE THREAD

**Issue by bwbarron** [linkedin/Burrow#385]
I need to pass an API key as a header to send events to New Relic Insights. I do not see any way to do this after digging around a bit. If this isn't supported yet, when will it be? I noticed there is a PR (#357) to add this.

**Comment by richardwalsh** [comment]
Looking to do the same thing and stumbled into the same issue. Can you share your post/delete templates that you are using to push the event into NewRelic?

**Comment by toddpalino** [comment]
Yeah, it's not supported right now. Once #357 has a test added to it, it can be merged in.

**Comment by bwbarron** [comment]
#357 merged

**Comment by deitch** [comment]
@bwbarron and @richardwalsh : did you manage to get the data pushed into NewRelic? Do you have a sample config (without your actual key, of course), that you could share? It would be very helpful.

**Comment by richardwalsh** [comment]
> @bwbarron and @richardwalsh : did you manage to get the data pushed into NewRelic? Do you have a sample config (without your actual key, of course), that you could share? It would be very helpful.

Wow, didn't see your message until just now. The following snippet is from the burrow.toml jinja2 template we use to build our burrow instances with:

```
[notifier.newrelic]
class-name="http"
# number of seconds to wait between sending notifications
interval={{ notifier_newrelic_interval | default(30) }}
# minimum threshold for a consumer group's state to warrant creating a NewRelic event
threshold={{ notifier_newrelic_threshold | default(2) }}
group-whitelist="{{ notifier_newrelic_allow_list | default('') }}"
group-blacklist="{{ notifier_newrelic_deny_list | default('') }}"
send-close=true
url-open="https://insights-collector.newrelic.com/v1/accounts/{{ notifier_newrelic_account_id }}/events"
template-open="{{ burrow_dir }}/config/notifier-newrelic-insights-open.tmpl"
url-close="https://insights-collector.newrelic.com/v1/accounts/{{ notifier_newrelic_account_id }}/events"
template-close="{{ burrow_dir }}/config/notifier-newrelic-insights-close.tmpl"
timeout={{ notifier_newrelic_timeout | default(15) }}
headers={X-Insert-Key="{{ notifier_newrelic_account_insert_key }}"}
```
