### ISSUE TITLE
The Email Notifier error message might cause misleading

### ISSUE THREAD

**Issue by adxhyt** [linkedin/Burrow#40]
Hello, I update the burrow into the lastest version. It solves the slow topics problem. but it still uses 
```
            thispart := &PartitionStatus{
                Topic:     topic,
                Partition: int32(partition),
                Status:    StatusOK,
                Start:     firstOffset,
                End:       lastOffset,
                Rule:      0,
            }
```
to output error msg like this:
```
----------------------------------------------------------------------
Cluster:  test
Group:    b7347d1e3d1958818cf95bced0b0855f
Status:   ERROR
Complete: true
Errors:   1 partitions have problems
          STOP risk_async:8 (1451379927170, 275814, 0) -> (1451381233774, 275829, 0) 
----------------------------------------------------------------------
```
In this case, email send error msg marked as stop because it violates the rule 4a.  maybe the error msg should point out the rule it violated and show clusterMap.broker[topic][partition].Offset instead of firstOffset. btw the config/default-email.tmpl file seems out of date or I use it in wrong condition.

**Comment by toddpalino** [comment]
So the error states map directly to rules, so I don't think there's a need for that sort of detail. In addition, you can just change the template to output whatever you want - the default template is just an example.
