### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by mmodenesi** [linkedin/Burrow#401]
When the quickstart suggests:

> Some test topics have already been created by default and Burrow can be accessed on port 8000 of your docker-machine. e.g. http://192.168.99.100:8000/v2/kafka

a newcomer eager to quiclky get a grasp of the project will be disappointed to receive
```json
{"error":true,"message":"invalid request type","result":{}}
```

Instead, it shoud say

> Some test topics have already been created by default and Burrow can be accessed on port 8000 of your docker-machine. e.g. http://192.168.99.100:8000/v3/kafka

or simply link to the [available endpoints](https://github.com/linkedin/Burrow/wiki/HTTP-Endpoint).

**Comment by ratishr** [comment]
Commited updated README.md
