### ISSUE TITLE
a state of consumer

### ISSUE THREAD

**Issue by heipacker** [linkedin/Burrow#41]
if offset.Timestamp-previousTimestamp < (storage.app.Config.Lagcheck.MinDistance * 1000) {
			clusterOffsets.consumerLock.Unlock()
			return
		}
here, is there need exclude the state when offset.Timestamp-previousTimestamp==0  ?
if consumer did not commit offset for a while,  and the ring is not full yet, then the evaluateGroup methd will not check out the true state of the consumer.

**Comment by toddpalino** [comment]
If the consumer has not committed offsets in a while and the ring is not full, then the state of the consumer is incomplete as far as Burrow is concerned and this is reflected in the response (with complete = false).

I'm working separately on some tuning for how ZK offsets are added to try and make slow committers who are caught up work better.

**Comment by heipacker** [comment]
in this way, you must alert when the ring is not completed, but when you application startup, it will alert for a while, but other ring is really uncompleted, so users may not distinct this stituation, thank you for your reply
