### ISSUE TITLE
Add option to trust self-signed SSL certificates for notifiers 

### ISSUE THREAD

**Issue by maxtuzz** [linkedin/Burrow#412]
For those behind a corporate proxy, extra certificates need to be added to trust the proxy otherwise both HTTP, and email notifications will not work. 

The error behind a corporate proxy when using a HTTP notifier: 

```
{
    "level": "error",
    "ts": 1529967533.3294523,
    "msg": "failed to send",
    "type": "module",
    "coordinator": "notifier",
    "class": "http",
    "name": "slack",
    "cluster": "MY_CLUSTER",
    "group": "MY_GROUP",
    "id": "de897056-3f0b-42a2-afe7-59386a1cb98f",
    "status": "ERR",
    "error": "Post https://hooks.slack.com/services/{WEBHOOK}: x509: certificate signed by unknown authority"
}
```

The error for SMTP related notifications:
```
{
    "level": "error",
    "ts": 1529967227.6587055,
    "msg": "failed to send",
    "type": "module",
    "coordinator": "notifier",
    "class": "email",
    "name": "email",
    "cluster": "MY_CLUSTER",
    "group": "multiTopicTestGroup",
    "id": "0c6a7e64-5464-4f8b-a46f-b7b595504456",
    "status": "ER\nR",
    "error": "x509: certificate signed by unknown authority"
}
```

and 

```
{
    "level": "debug",
    "ts": 1529964981.0797005,
    "msg": "ok",
    "type": "module",
    "coordinator": "storage",
    "class": "inmemory",
    "name": "email",
    "cluster": "MY_CLUSTER",
    "group": "multiTopicTestGroup",
    "id": "34a9e72e-980f-41c8-8ae8-2387f8dbcc77",
    "status": "ERR",
    "error": "x509: certificate is valid for xxx, xxx.aaa.com, not bbb.alias.aaa.com"
}
```

It would be ideal to have a configuration option for loading a certificate chain to be trusted by both notifiers.

**Comment by icearn** [comment]
@toddpalino could we load a tls profile in the notifier coordinator and check the tls setting in each notifiers?

**Comment by maxtuzz** [comment]
@icearn Loading a TLS profile could be good as that covers cafile, no verify etc. 

What I have done is added an 'extra-ca' property to the notifiers field. This is loaded into the module and will append the additional certs and add them as TLSClientConfig within http.Transport when setting up the client: 

```go
module.httpClient = &http.Client{
		..,,
		Transport: &http.Transport{
			..,
                         ..,
			TLSClientConfig: tlsConfig,
		},
	}
```

I guess an extra TLS profile could be set up and added to the notifiers property to achieve the same result and be more consistent than this solution. I can look into it after I've verified that it works.

**Comment by maxtuzz** [comment]
I can confirm `extra-ca` and `noverify` is working on my fork. 

I'll modify my solution to use an extra TLS profile. And then see what I can do to apply the same feature to the email notifier.

**Comment by maxtuzz** [comment]
Actually - since all the required TLS profile fields aren't actually required for this solution I'm unsure if it's the best solution.

**Comment by maxtuzz** [comment]
All working for both SMTP and Http notifier. Although I had to migrate to use the gomail library for SMTP as you cannot override TLS config easily using the sendmail func.

**Comment by jhr1972** [comment]
Hello,
I do not manage to get any emails sent out due to the cert validation error(see below) However, I do not want to use any SSL when sending emails. Consequently I also have not configured any SSL. Do you have any idea what may cause this ?

[notifier.tellme]
class-name="email"
interval=1
threshold=1
noverify=true
template-open="/tmp/burrow.tmpl"
auth-type="plain"
server="mail2.localnet.de"
port=25
from="x.y.z@anything.here"
to="x.y.z@anything.here"


{"level":"error","ts":1530708809.894899,"msg":"failed to send","type":"module","coordinator":"notifier","class":"email","name":"tellme","cluster":"debug","group":"cons1","id":"e52ed3bb-b921-4ebb-a011-071f355b9d38","status":"ERR","error":"x509: certificate signed by unknown authority"}

**Comment by maxtuzz** [comment]
If the TLS enabled SMTP server is trusted then it should work. However, if it is secured using an internally signed certificate then the `extra-ca` config will need to be added for the certificate to be loaded into the truststore for Burrow. 

The `noverify` option can be added if you wish to skip trust verification checks and just go ahead and use any smtp endpoint.
