### ISSUE TITLE
Tag a new release with kafka 1.1.0 support

### ISSUE THREAD

**Issue by mrueg** [linkedin/Burrow#432]
Would it be possible to get a new release with kafka-1.1.0 support? Thanks!

**Comment by mrueg** [comment]
@toddpalino friendly ping :)

**Comment by cyang16** [comment]
last release is on May 15. Have monthly or quarterly release will be helpful

**Comment by mrueg** [comment]
since you merged https://github.com/linkedin/Burrow/pull/447,  possible to tag a new relase @bai?

**Comment by bai** [comment]
@mrueg Yep, just doing a bit more tests.

**Comment by thoralf-gutierrez** [comment]
Hey @bai - Thanks for your work, burrow has been very useful to us! We're now trying to figure out how we should approach monitoring our more recent kafka cluster.

Do you have an idea on when that next release (with kafka > 1.0 support) could come? If not anytime soon, do you work off of master or a particular commit in production?

**Comment by bai** [comment]
Hey @thoralf-gutierrez! You can build current `master` that supports Kafka up to 2.1.0 (most recent version). I haven't had a chance to test it extensively on 2.1.0 just yet, but it's been battle-tested on 2.0.0—I don't expect 2.1.0 to have issues either.

**Comment by bai** [comment]
I'll probably tag a proper release release after holidays—just being little too cautious about this.

**Comment by cricket007** [comment]
> I don't expect 2.1.0 to have issues either

Maybe #470 points out one issue?

**Comment by mrueg** [comment]
Any chance to see a new release soon? :)

**Comment by bai** [comment]
_Finally_, here we go: https://github.com/linkedin/Burrow/releases/tag/v1.2.0.
