### ISSUE TITLE
kafka 2.0 support

### ISSUE THREAD

**Issue by golonzovsky** [linkedin/Burrow#440]
Currently Burrow reports growing lags for kafka 2.0 brokers, while `kafka-consumer-groups` reports zero lag.

Just to mention, from kafka 2.0 [KIP-222](https://cwiki.apache.org/confluence/display/KAFKA/KIP-222+-+Add+Consumer+Group+operations+to+Admin+API) ConsumerGroup operations of AdminClient could be used to get groups and offsets..

**Comment by hejiaji** [comment]
Any plan for support kafka 2.0?????

**Comment by lukaalex** [comment]
I think there is an issue with Kafka 2.0. I believe it is related to this library that burrow uses https://github.com/Shopify/sarama

**Comment by ericfgarcia** [comment]
Same question as hejiaji had above.  We are looking to upgrade Kafka, but love burrow.

**Comment by sfrooster** [comment]
We just ran into this today after upgrading to 2.0....

**Comment by pikrzysztof** [comment]
Sarama supports kafka 2.0 as of release 1.18.0

https://github.com/Shopify/sarama/releases/tag/v1.18.0

**Comment by haeuserd** [comment]
See #447

**Comment by bai** [comment]
https://github.com/linkedin/Burrow/pull/447 was merged.

**Comment by golonzovsky** [comment]
@bai :+1: 
maybe not the best place to ask, but are there plans for releasing `1.2` any time soon? or its better to go with own build from master so far?

**Comment by gabrielfsousa** [comment]
i would luv kafka 2.0 support !!!
