### ISSUE TITLE
Error Recv loop terminated while brining up Burrow

### ISSUE THREAD

**Issue by pradeepkusingh** [linkedin/Burrow#441]
I can see in logs that we successfully grab the data for topics but at the end getting this error and server stopped.

{"level":"info","ts":1533917522.548949,"msg":"stopping","type":"module","coordinator":"evaluator","class":"caching","name":"default"}
{"level":"info","ts":1533917522.5489688,"msg":"stopping","type":"coordinator","name":"storage"}
{"level":"info","ts":1533917522.5490043,"msg":"stopping","type":"module","coordinator":"storage","class":"inmemory","name":"default"}
{"level":"info","ts":1533917522.5490804,"msg":"stopping","type":"coordinator","name":"zookeeper"}
{"level":"info","ts":1533917522.6038673,"msg":"Recv loop terminated: err=EOF","type":"coordinator","name":"zookeeper"}
{"level":"info","ts":1533917522.604006,"msg":"Send loop terminated: err=<nil>","type":"coordinator","name":"zookeeper"}

**Comment by pradeepkusingh** [comment]
I gave wrong file location.

**Comment by sunboy** [comment]
@pradeepkusingh I'm currently dealing with the same problem, can you help me with the resolution to this problem? What incorrect file location were you referring to in your comment?

**Comment by erkexzcx** [comment]
+1 how to solve this issue?
