### ISSUE TITLE
Add some request parameters to json response

### ISSUE THREAD

**Issue by panda87** [linkedin/Burrow#45]
Hi

I think that adding 3 parameters to the json response for "Consumer Topic Detail" query will be great.
The parameters are the following
1. Cluster name
2. Consumer group
3. topic name

The params are already exists in the server url, and this will be great if they will be printed in the response.

Thanks 
D.

**Comment by toddpalino** [comment]
Something like this sounds like a good idea to have for all responses. At the very least, we can include the request URL which encodes all the information. I will try to work on this soon, if someone else doesn't submit a PR first. As long as we're just adding things to the JSON response, it's not a major API change.

**Comment by panda87** [comment]
Thanks @toddpalino!

**Comment by panda87** [comment]
Hi @toddpalino any progress on that?

**Comment by nhproject** [comment]
+1

**Comment by toddpalino** [comment]
Fixed now in trunk
