### ISSUE TITLE
burrow compatibility with Kafka 0.11.0.0 

### ISSUE THREAD

**Issue by mmshaikh88** [linkedin/Burrow#457]
We are trying to connect burrow with kafka (2.11-0.11.0.0) version where 0.11.0.0 is the kafka version. 
We are seeing issues while the burrow is trying to connect to kafka cluster

See the excerpt from the burrow.log, the IP address showing up is also not the kafka broker ip instead it shows the dns ip.

{"level":"error","ts":1540579320.2375278,"msg":"failed to fetch offsets from broker","type":"module","coordinator":"cluster","class":"kafka","name":"tt-yl-kafka-01","sarama_error":"dial tcp: lookup ifrs-worker-7 on 10.254.0.10:53: no such host","broker":7}

Any idea, how can we use burrow with 0.11.0.0 version of kafka?

**Comment by bai** [comment]
👋Burrow supports kafka 0.8 and up. This looks like networking issue to me.
