### ISSUE TITLE
how to configure e-mail alarm config-file?

### ISSUE THREAD

**Issue by kevinsingapore** [linkedin/Burrow#463]
i don't know how to config email alarm? so please give a guide, thank u!

**Comment by bai** [comment]
Actually, Wiki has [documentation and examples](https://github.com/linkedin/Burrow/wiki/Notifier-Email) on how to set up email notifications.

**Comment by kevinsingapore** [comment]
> 
> 
> Actually, Wiki has [documentation and examples](https://github.com/linkedin/Burrow/wiki/Notifier-Email) on how to set up email notifications.

thank u for help!
and where can i put my monitor email-address. 
or in which config-file？

**Comment by kevinsingapore** [comment]
> 
> 
> Actually, Wiki has [documentation and examples](https://github.com/linkedin/Burrow/wiki/Notifier-Email) on how to set up email notifications.

thank u for help!
i got it.

**Comment by kevinsingapore** [comment]
> 
> 
> Actually, Wiki has [documentation and examples](https://github.com/linkedin/Burrow/wiki/Notifier-Email) on how to set up email notifications.


and would u show me a full-simple config-file?
thank u！
