### ISSUE TITLE
Burrow crashes in the presence of groups with protocol_type != 'consumer' (example: schema-registry)

### ISSUE THREAD

**Issue by mlongob** [linkedin/Burrow#475]
Per [KIP-40](https://cwiki.apache.org/confluence/display/KAFKA/KIP-40%3A+ListGroups+and+DescribeGroup):

```
The protocolType specifies what kind of group it is and how metadata/assignments should be decoded. For consumer-specific tooling, any groups which do not have a "consumer" protocol type can be ignored.
```

The [schema-registry](https://github.com/confluentinc/schema-registry) creates groups with `protocol_type=sr` with payloads that Burrow can't parse properly.
As a result, Burrow crashes at this line: https://github.com/linkedin/Burrow/blob/6f0e4909844c2840c835ed56b63ddc81b54f4042/core/internal/consumer/kafka_client.go#L565
when it tries to allocate a map with a very high value of `numTopics`.

I am working on a patch that will ignore all groups with `protocol_type` not equal to `consumer`.

**Comment by toddpalino** [comment]
Looks like a good change. I added one comment on the PR, requesting an additional test case
