### ISSUE TITLE
Cannot get consumer group list for cluster <name>: zk: node does not exist

### ISSUE THREAD

**Issue by TimurFayruzov** [linkedin/Burrow#49]
Hello,

I have a mix of consumers that track offsets in Kafka and in Zookeeper. I successfully set up Burrow to track Kafka-stored offsets, however I have trouble tracking offsets that are stored in Zookeeper. When I set
```
zookeeper-offsets=true
``` 
Burrow starts up, but log contains the following message:
```
[Error] Cannot get consumer group list for cluster <my_cluster_name>: zk: node does not exist
```
I can retrieve Kafka-stored offsets fine, but it can't find consumer groups that are tracked in Zookeeper.

I have added a log before [this](https://github.com/linkedin/Burrow/blob/a2537caaf5ac219fa2616af128044f87c29a47f9/zookeeper.go#L77) line to show the path where offsets are looked up, and it shows correct path. I can verify in Exhibitor that consumer group nodes exist under that path.

I think my Zookeeper is set up correctly (otherwise I won't be able even to discover Kafka cluster at all).

Any ideas on resolution or further investigation are appreciated.

**Comment by toddpalino** [comment]
It sounds like your configuration in Burrow for Zookeeper is not correct. Burrow does not use the Zookeeper information to discover the Kafka cluster, it uses the defined broker list to do that.

Please post your configuration section for the cluster.

**Comment by TimurFayruzov** [comment]
Hello Todd, here's my configuration:

```
[zookeeper]
hostname=zookeeper0
hostname=zookeeper1
hostname=zookeeper2
hostname=zookeeper3
hostname=zookeeper4
port=2181
timeout=6
lock-path=/burrow/notifier

[kafka "prod"]
broker=kafka0
broker=kafka1
broker=kafka2
broker-port=6667
zookeeper=zookeeper1
zookeeper=zookeeper2
zookeeper=zookeeper3
zookeeper=zookeeper4
zookeeper=zookeeper5
zookeeper-port=2181
zookeeper-offsets=true
zookeeper-path=/util/kafka-logging
```

I can ping zookeeper* hosts from my machine and can telnet to port 2181.

**Comment by toddpalino** [comment]
So that error is generated when Burrow is unable to get child znodes for /util/kafka-logging/consumers Can you check that that znode exists on your ensemble with that exact path?

**Comment by TimurFayruzov** [comment]
Yes, I have verified in Zookeeper Exhibitor that this path exists. Moreover (I failed to mention this before)
```
kafka-consumer-offset-checker.sh --zookeeper zookeeper0:2181/util/kafka_logging --group scu17
```
works and returns proper lags and offsets. That's why I had a suspicion that something is up with Burrow.

**Comment by toddpalino** [comment]
Your offset checker command does not match the Zookeeper path you specified in your config. Your config shows /util/kafka-logging. Your command has /util/kafka_logging

**Comment by TimurFayruzov** [comment]
Doh, this is embarrassing! I stared at this config for too long. This was indeed an issue. Thanks, Todd!
