### ISSUE TITLE
No consumer groups

### ISSUE THREAD

**Issue by ceeeekay** [linkedin/Burrow#496]
Since upgrading Kafka to 2.12-2.10 I can no longer list consumer groups in my prod environment. Dev is running the same version of Kafka with the same config, and has no issues. I've tried using the latest Burrow code on prod, and get the same empty list. Dev is still rocking on with a much older burrow install and is displaying the consumer list just fine.

From the prod Burrow logs: `[WARN] Failed to decode __consumer_offsets:49 offset 172116: valver 3`

The only reference I can find to this error is #53 but I can't find anything in there that will help me. As far as I can tell I'm committing offsets to Kafka.

I have spent many hours on this, and I'm probably more confused now than when I started. I have even gone so far as to shut down my pipeline and purge and reinstall Kafka, in case there were some old topic settings that caused this, but no luck.

Clients for both environments are all Logstash 6.6.0 (not sure if this is relevant), and they all have the same consumer config.

What's my next step to get this figured out?

**Comment by toddpalino** [comment]
You're running a 0.x version of Burrow. You're going to need to update to latest and provide the logs from that.

From the log message you did provide, it's failing to decode the message because it's using schema version 3 for the message value. That was added back in 10d4dc39ebe33fbacd9f96879b4019b8d473ea0f

**Comment by ceeeekay** [comment]
@toddpalino all good, got Burrow upgraded to the latest and I can now query the API. Thanks.

**Comment by msalmanST** [comment]
Hey,

I also faced the same issue just after upgrading my kafka to version 2.1.1, so I follow the above guidelines and now I move to burrow v1.2.2, but now when I try to run the burrow via docker compose it exit with below logs.

> burrow | Reading configuration from /etc/burrow
> burrow | Burrow failed at March 27, 2019 at 3:10pm (UTC)
> burrow | Existing process running on PID 1. Exiting burrow exited with code 1

What other changes do i suppose to do apart from upgrading to burrow version v1.2.2. I appreciate you r help in this regard.
