### ISSUE TITLE
Binary release for 1.2.0 is missing

### ISSUE THREAD

**Issue by jrpilat** [linkedin/Burrow#498]
Per #489 / #490, a fix was put in place such that the binaries would once again be goreleased for new Burrow releases, but it looks like the 1.2.0 release wasn't regenerated in the process.

Would someone with the correct permissions to the TravisCI instance please re-kick-off the build in order to generate the binary (if I am properly understanding the workflow)?

Thanks!

**Comment by bai** [comment]
Looks like I'm going to need to tag v1.2.1 for this to work. I'm going to cut in tonight.

**Comment by jrpilat** [comment]
Sounds great, thanks again!

**Comment by nerijus** [comment]
Still no binary release for 1.2.1

**Comment by bai** [comment]
Here we go: https://github.com/linkedin/Burrow/releases/tag/v1.2.2 — apologies for delay, it took some time to fix binary release process.
