### ISSUE TITLE
The latest version of burrow does not send email

### ISSUE THREAD

**Issue by lianfulei** [linkedin/Burrow#517]
The latest version of burrow send email ERROR

What is the reason?

{"level":"error","ts":1555379958.7183263,"msg":"failed to send","type":"module","coordinator":"notifier","class":"email","name":"gemail","cluster":"kafkathree","group":"test-consumer-group","id":"5cc9b3bb-943c-473d-aaca-404c2c223364","status":"ERR","error":"EOF"}

**Comment by lianfulei** [comment]
i have solve！

**Comment by Prakash-droid** [comment]
I am facing the same error.Could you please explain how you solved it?
