### ISSUE TITLE
"Complete" always shows "false"

### ISSUE THREAD

**Issue by haimari** [linkedin/Burrow#54]
Even after a few hours "Complete" never gets to "true"
Anyway to debug this ?

http://our-burrow.com/v2/kafka/our-cluster/consumer/our-group/status

```
{
error: false,
message: "consumer group status returned",
status: {
cluster: "our-cluster",
group: "our-group",
status: "OK",
complete: false,
partitions: [ ],
partition_count: 1100,
maxlag: null
}
}
```

**Comment by toddpalino** [comment]
The status should be shown as incomplete until the offset ring is full for all partitions that the consumer has. The ring has however many positions you have configured with the `interval` parameter in the `[lagcheck]` section of the config. This defaults to 10, which means that there must be 10 offset commits for every partition before it will be considered complete. If your consumer is committing offsets slowly, or not at all, it could take a long time to fill up the ring.

**Comment by toddpalino** [comment]
Closing old issue. Please reopen with more detail if it is still a problem on the latest release

**Comment by gustavosoares** [comment]
@toddpalino your comment here is much clear than what is in the wiki page. It helped me understand why I was getting complete `false` all the time. You should consider updating the wiki. 😃
