### ISSUE TITLE
Hyphens are not valid environment variable identifiers

### ISSUE THREAD

**Issue by kylekthompson** [linkedin/Burrow#546]
In #363, support for configuring Burrow with environment variables was added.

For most situations, this works really well. I ran into an issue with `client-profile.name.kafka-version`; the environment variable name for its options would be something like `BURROW_CLIENT-PROFILE_MAIN_KAFKA-VERSION`.

Unfortunately, it looks like environment variable names [can only contain alphanumeric characters and underscores](https://pubs.opengroup.org/onlinepubs/009695399/basedefs/xbd_chap08.html).

In the original PR, some configuration was used to substitute `.` for `_`. Would you be open to substituting `-` for `__` or something similar? If so, I'd be more than happy to open a PR.

**Comment by dellalu** [comment]
Hi I had the same issue and tried a PR, it's already been merged now 
[b93356f](https://github.com/linkedin/Burrow/commit/b93356fc7acedd24b91ad340e6b751d533e92430).
