### ISSUE TITLE
Burrow fails to decode group metadata for Kafka brokers at version 2.3.0

### ISSUE THREAD

**Issue by shaaimin** [linkedin/Burrow#560]
{"level":"warn","ts":1566894189.3171144,"msg":"failed to decode","type":"module","coordinator":"consumer","class":"kafka","name":"consumer_kafka","offset_topic":"__consumer_offsets","offset_partition":13,"offset_offset":85,"message_type":"metadata","group":"connect-cluster","reason":"value version","version":3}
{"level":"warn","ts":1566894192.066904,"msg":"failed to decode","type":"module","coordinator":"consumer","class":"kafka","name":"consumer_kafka","offset_topic":"__consumer_offsets","offset_partition":20,"offset_offset":1447,"message_type":"metadata","group":"connect-connector-consumer-processedstores","reason":"value version","version":3}

**Comment by superbool** [comment]
Same as above. Master branch.

**Comment by ftardif** [comment]
any ETA for 2.3 support?

**Comment by daniilyar** [comment]
Thу fix in this PR worked for us also for Kafka 2.2 :) Hope that helps you when merging
