### ISSUE TITLE
Burrow Docker image build is failing

### ISSUE THREAD

**Issue by bhasvij** [linkedin/Burrow#565]
Trying to build latest burrow docker image and getting the below issue. Kindly help and we can leverage this great tool int our production

Step 5/12 : WORKDIR $BURROW_SRC
 ---> Running in 83c95511f2d7
Removing intermediate container 83c95511f2d7
 ---> c31eee5c4002
Step 6/12 : RUN go mod tidy && go build -o /tmp/burrow .
 ---> Running in 75d2c8399823
**### go: cannot find main module; see 'go help modules'**
The command '/bin/sh -c go mod tidy && go build -o /tmp/burrow .' returned a non-zero code: 1

**Comment by bhasvij** [comment]
Hi, this may be silly issue, can you please provide the solution?

**Comment by mlamothe** [comment]
Make sure you clone the entire repo before running docker build.

**Comment by bai** [comment]
I think the issue has been since fixed in master.

**Comment by mlamothe** [comment]
Okay. I came here because I ran into the same issue today (I had just grabbed the Dockerfile instead of cloning the repo).

**Comment by bhasvij** [comment]
Off late i found the same reason last month. Thanks for the reply

Regards
Bhaskar

**Comment by palmerabollo** [comment]
It works on my machine. I'd close this issue.

**Comment by bai** [comment]
This one should have been resolved indeed.

**Comment by palmerabollo** [comment]
Thanks @bai. As a side note, it would be great to have this docker image published in Docker Hub, so we don't need to build it and republish to our own docker registries multiple times.
https://hub.docker.com/u/linkedin looks like a good place to me.

**Comment by bai** [comment]
Note that there's "official" docker image on GitHub Registry: https://github.com/linkedin/Burrow/packages/104930 — released automatically when we push a new tag.
