### ISSUE TITLE
Kafka 2.3.0 support release

### ISSUE THREAD

**Issue by pmbuko** [linkedin/Burrow#568]
I see that kafka 2.3.0 support exists in the master branch (https://github.com/linkedin/Burrow/commit/d485b3a48a3d80c5084295cb01d4e700bdb8a57b). Can you tag a release with this?

**Comment by bsnyder788** [comment]
would love to see a release cut for this as well!

**Comment by spmason** [comment]
We're also after a version that support 2.3.0 - it looks like @bai usually does them..

**Comment by bai** [comment]
👋Thanks for highlighting me here. I've pushed https://github.com/linkedin/Burrow/releases/tag/v1.3.0 with support for both Kafka 2.3.0 and 2.4.0.

**Comment by spmason** [comment]
Thanks @bai - that only seems to include the source tars though and I was hoping for the built binaries themselves. Is there any chance of getting those added to the release too?

**Comment by bai** [comment]
So GoReleaser should have picked that up and attached bins but it didn't — looks like some of the options were removed from `.goreleaser.yml` and it's due for some housekeeping. I'm looking into that now and will post an update once bins are attached.

**Comment by bai** [comment]
Alright, I think I finally managed to fix it. Could you please take a look and do a quick sanity check from your side:

* [Official Burrow docker image on GitHub Package Registry](https://github.com/linkedin/Burrow/packages/104930)
* [Binaries are attached to release tags](https://github.com/linkedin/Burrow/releases/tag/v1.3.2-alpha0)
* [CI and Release processes migrated from Travis CI to GitHub Actions](https://github.com/linkedin/Burrow/actions)

One thing that's kinda annoying — binary archive filenames start with uppercase "Burrow", while docker image and binary itself are lowercase "burrow". I'm thinking about just converting everything to lowercase. Do you think it makes sense, or should I convert it to "Burrow" instead, or keep as is?

Let me know what you think 🙏

**Comment by spmason** [comment]
Thanks!  It looks like the binary release works great - the docker image sounds cool but we're not at the point where we use Burrow in docker yet

Kudos on the Travis -> GitHub Actions migration too, though it sounds like that made this a bit of a pain to do

I don't mind too much about the archive filenames, at the moment they're at least consistent with previous releases but I agree the inconsistency is a bit annoying - lowercase everywhere is kinda what people expect I think

**Comment by oxr463** [comment]
> One thing that's kinda annoying — binary archive filenames start with uppercase "Burrow", while docker image and binary itself are lowercase "burrow". I'm thinking about just converting everything to lowercase. Do you think it makes sense, or should I convert it to "Burrow" instead, or keep as is?
> 
> Let me know what you think 🙏

Agreed, I think it should be all lowercase.
