### ISSUE TITLE
burrow consumer keeps dying

### ISSUE THREAD

**Issue by bputt** [linkedin/Burrow#569]
Burrow's consumer keeps erroring out with nothing in the logs and the lag keeps increasing for the burrow-<cluster> group until I restart burrow.

We're running burrow in docker and it's based off the master branch as of yesterday.

Using kafka 2.3.0

When curling ```/v3/kafka/mycluster/consumer/burrow-mycluster/status``` I get back something like:
```{"error": false, "message": "consumer status returned", "status": { "cluster": "mycluster", "group": "burrow-mycluster", "status": "ERR" }}```

When bumping the logs to debug, I get the following message:
```
{ msg: "evauliation result", type: "module", coordinator: "evaluator", class"caching", name: "default", cluster: "mycluster", consumer: "burrow-mycluster", status: "ERR" }
```

**Comment by boxuan666** [comment]
hi do u reslove this problem?

**Comment by bputt** [comment]
@boxuan666 yea, we used https://github.com/lightbend/kafka-lag-exporter instead

**Comment by boxuan666** [comment]
@bputt thx, so you no longer use burrow to monitor kafka?

**Comment by bputt** [comment]
@boxuan666 correct, we use lightbend's exporter instead

**Comment by boxuan666** [comment]
@bputt how about consumer_lag alert in u prometheusrules? using number of lag the as trigger ?
Can you refer me to your alert rules for kafka ?

**Comment by bputt** [comment]
@boxuan666 we don't have alerts set up yet, but the charts we had previously that worked with burrow work with lightbend (yes, different label), but we achieved the same goal of being able to monitor topic lag
