### ISSUE TITLE
Logging under runit

### ISSUE THREAD

**Issue by rphillips** [linkedin/Burrow#57]
Would be nice if all stdout/stderr could be routed to the console logger in seelog. Looks like Burrow only logs to files, which breaks the runit logger and potentially the systemd logger.

**Comment by toddpalino** [comment]
I'm not sure I'm understanding your concern here. Seelog configuration is fairly robust, and you can send the logging output wherever you need it. Burrow does not execute applications that are separately sending output to stdout/stderr.

**Comment by porcupie** [comment]
I'm also having this issue - though my use-case is Docker container.  I am running inside a container and I can setup seelog to use the `<console/>` output, but then in `main.go` you open separately the "burrow.out" logfile for stdout/stderr.  

I want stderr/stdout to actually go to stderr/stdout and not to `burrow.out` if possible?

**Comment by porcupie** [comment]
Another solution would be if I can specify a filename myself and I can send to `/dev/stdout` for example.

**Comment by rphillips** [comment]
Thanks @porcupie. The racker@ commit is mine. @toddpalino: The burrow.out logs always get created, but the runit and (looks like) the docker logger expect stdout/stderr to go to the console.

**Comment by msaffitz** [comment]
Bump on this-- I'm trying to get debug output to the console, and regardless of the configuration I use within seelog (i.e. adding `<console />` to outputs)  it doesn't seem to send anything to STDOUT.  Is a fork (i.e. what @porcupie linked to) the preferred way to fix this, or is there some Seelog voodoo to get it to work?

**Comment by tomaszganski** [comment]
Hi, this issue is  really troublesome when you want to use Burrow with docker as docker logging driver reads log events directly from the container’s stdout and stderr output. Because of this we can't gather logs from Burrow in consistence way as our other docker containers.

To start working with Burrow I need to remove the line mentioned above
https://github.com/linkedin/Burrow/blob/master/main.go#L64

It would be great if we could just control this behaviour via configuration like `disable.stdout`

**Comment by murphyslaw** [comment]
👍

**Comment by CVTJNII** [comment]
> It would be great if we could just control this behaviour via configuration like disable.stdout

:+1: for this suggestion.  I'm attempting to use Burrow and was immediately tripped by this.  Assuming the user will always want logs to go to logfiles is false, I need my logs on stdout/stderr.
