### ISSUE TITLE
Where do the kafka cluster name comes from?

### ISSUE THREAD

**Issue by geoffroya** [linkedin/Burrow#59]
Hello

My burrow works fine, but I have a question that may be out of scope: where the cluster name given by the ```v2/kafka``` request comes from? I can't find a param in kafka doc to set it

Here's what I get from burrow/v2/kafka:

```
{
  "error":false,
  "message":"cluster list returned",
  "clusters":[
    "local"
  ]
}
```

If somesone can tell me how to change "local".

Best regards

Geoff

**Comment by toddpalino** [comment]
Cluster names are defined in the burrow configuration, in the header for the config section that defines the cluster. That is, if you have a header `[kafka local]`, then the cluster name in Burrow will be local. If you want it to be something else, just change "local" to something else in the header.

**Comment by geoffroya** [comment]
Thank you, it was the only place I didn't look for!
