### ISSUE TITLE
Offset on newly created topic

### ISSUE THREAD

**Issue by omartell** [linkedin/Burrow#60]
What should the offset be for a new topic with no messages in it when hitting the cluster topic detail endpoint v2/kafka/local/topic/topic-name? The kafka client returns -1, but the endpoint shows 0.

Or is it the case that the endpoint returns the number of messages in the topic?

**Comment by jsvisa** [comment]
@omartell which Kafka client are you using? I'm use the default client, it shows the offset is 0:

```
[root@NEW-STORE-00 kafka]# bin/kafka-run-class.sh kafka.tools.GetOffsetShell --topic newcreate --time -2 --broker-list 127.0.0.1:9092
newcreate:0:0
```

**Comment by omartell** [comment]
@jsvisa I was using the Clojure client. It looks like it returns -1 when where are no messages in the topic for some reason. So, Burrow is right and it's consistent with other Confluent command line tools by showing 0.
