### ISSUE TITLE
Extended Response Structure

### ISSUE THREAD

**Issue by nhproject** [linkedin/Burrow#64]
Is it possible to add the topic name and the consumer group name to the response of the queries?
(for example, **GET /v2/kafka/(cluster)/consumer/(group)/topic/(topic)** )
It will be very helpful 👍 

Thanks in advance!

**Comment by jsvisa** [comment]
What response are you expected? The lag of topic under the specified `group`, I think so

**Comment by nhproject** [comment]
I'm not sure I understood you, but anyway, I simply asking for this kind of repsponse (for the above GET request):

{
  "error": false,
  "message": "consumer topic offsets returned",
  "offsets": [
    2290903,
    2898892,
    3902933,
    2328823
  ]
  group: (group),
  topic: (topic)
}

Is it possible?

**Comment by jsvisa** [comment]
Seems you want a simple version of the lag API.
            在2016年04月20日 20:36，nhproject 写道:I'm not sure I understood you, but anyway, I simply asking for this kind of repsponse (for the above GET request):

{
  "error": false,
  "message": "consumer topic offsets returned",
  "offsets": [
    2290903,
    2898892,
    3902933,
    2328823
  ]
  group: (group),
  topic: (topic)
}

Is it possible?

**Comment by nhproject** [comment]
oh now I remember what you're talking about :)
We don't need the lag API. 
We only use this one:
https://github.com/linkedin/Burrow/wiki/http-request-consumer-topic-detail
(from several reasons)
It will be great to have those fields (topic, group) in this response too.

**Comment by toddpalino** [comment]
Fixed now in trunk
