### ISSUE TITLE
New release with kafka 2.6.0 support

### ISSUE THREAD

**Issue by carlsim0n** [linkedin/Burrow#669]
### Hi!

Thanks for providing a great way of monitoring consumer lag. 

Any idea when there will be a new release with [kafka 2.6.0 support](https://github.com/linkedin/Burrow/commit/2d28a4ba3ac334f67ee0d4ab04ac402bb8498b2f)?

Regards
Simon

**Comment by erkexzcx** [comment]
+1

**Comment by bai** [comment]
Just released Burrow with support for both Kafka 2.6.0 and 2.7.0.
