### ISSUE TITLE
Prometheus end point not emitting all metrics

### ISSUE THREAD

**Issue by saritago** [linkedin/Burrow#672]
Hi, facing issue with prometheus metrics. We are just getting burrow_kafka_topic_partition_offset metrics and no other metrics, where as ideally we should have got all of these "burrow_kafka_consumer_partition_lag", "burrow_kafka_consumer_current_offset", "burrow_kafka_consumer_status".

Any configurations that needs to be updated to get all the metrics.
We are using kafka version 0.11.0.3. and its a secured kafka cluster.

**Comment by HagaiBarel** [comment]
You should give a bit to run and collect the metrics, in our case it takes up to 10 minutes to see `burrow_kafka_consumer_current_offset` and `burrow_kafka_consumer_partition_lag`, running kafka 2.5.0 clusters

**Comment by saritago** [comment]
Thanks @HagaiBarel, yes as you mentioned we ran producer consumer for a while and created an artificial lag post which we were able to see all above metrics. Thank you. Am closing this issue from my end.
