### ISSUE TITLE
Plans for kafka 2.7.0 support?

### ISSUE THREAD

**Issue by dsr2149** [linkedin/Burrow#676]
Hello, are there any plans to provide support for kafka 2.7.0 in the near future? Is there something that can be done to allow for older releases of burrow to work with newer versions of kafka, or is this dependent on an updated sarama release that specifically supports these newer versions?

**Comment by bai** [comment]
Hey! This is unfortunately dependent on Sarama release. I've just released both Sarama and Burrow to support 2.7.0 officially.
