### ISSUE TITLE
SSL Support?

### ISSUE THREAD

**Issue by j0sh3rs** [linkedin/Burrow#68]
Does burrow support SSL-enabled kafka cluster(s)? Looking through the documentation, I can't find anywhere specifically where I'd have to change the burrow config to allow for monitoring of Kafka endpoints that only serve SSL

**Comment by WanliTian** [comment]
it does.
burrow uses sarama to consume kafka messages, and sarama does support ssl.

**Comment by j0sh3rs** [comment]
Is there any configuration needed, such as providing the keystore used in kafka to Burrow? With my kafka cluster up and running using SSL (and only SSL), I am receiving the following in my burrow.out:

```
Started Burrow at April 27, 2016 at 1:27pm (MDT)
2016/04/27 13:27:47 Connected to 172.16.173.99:2181
2016/04/27 13:27:47 Connected to 172.16.173.99:2181
2016/04/27 13:27:47 Authenticated: id=95555382589981222, timeout=6000
2016/04/27 13:27:47 Authenticated: id=95555382589981223, timeout=6000
Burrow failed at April 27, 2016 at 1:27pm (MDT)
F
2016/04/27 13:27:47 Send loop terminated: err=<nil>
```

I've got burrow working against servers not advertising SSL, and requiring ssl for interbroker communication.  But as soon as I turn on SSL as the primary means, burrow fails to start.

burrow.err doesn't provide me anything outside of:
```
Reading configuration from /usr/local/burrow/burrow.cfg
```

Running go 1.6 on ubuntu 12.04.5

**Comment by toddpalino** [comment]
While sarama supports TLS, the version that Burrow is set to use with Godeps does not, and I'm loathe to ever update it because they constantly change the interfaces.

We're going to have to pull a new version to test with and see what else will have to be updated alongside it. Right now, I need to go through some of the other code changes and lock a release. Then we'll test TLS and lock a release for that separately.

**Comment by j0sh3rs** [comment]
I figured out my problem.  As a workaround, I tried to set Kafka to listen on both SSL and Plaintext, and point Burrow only at the plaintext endpoint. Something akin to:
```
listeners=SSL://ip:9092,PLAINTEXT://ip:9093
advertised.listeners=SSL://ip:9092
```
This didn't work. Even though Kafka was listening on 9093, and my burrow config pointed there, Burrow still failed.  I'm not sure if this is a Burrow problem or not (I suspect it is -- somehow Burrow is prioritizing Zookeeper's port/ip combo over what's in its own configuration file).

Trying several different iterations of this, including plaintext on the Advertised Listeners port, also failed. It wasn't until I switched the order of my listeners to put plaintext first was burrow able to connect.

```
listeners=PLAINTEXT://ip:9093,SSL://ip:9092
advertised.listeners=SSL://ip:9092
```

The hard lesson: Put Plaintext first, SSL second.

**Comment by jojijohn** [comment]
@toddpalino - what's the time frame we should be looking at for the SSL support? Our broker currently supports only SSL connections, so I guess we will have to support PLAINTEXT as well for the time being to allow Burrow to connect to the brokers

**Comment by toddpalino** [comment]
It should be pretty quick. I've already done some basic testing with the latest version of Sarama and it didn't break things. We need to add some configuration parameters for setting up SSL and pass them through, however

**Comment by toddpalino** [comment]
OK, the master version now has support for TLS. You'll need to add a section like this to your config:
```
[clientprofile "tlsonly"]
client-id=burrow-lagchecker
tls=true
tls-noverify=true
```

And then you'll need to add `client-profile=tlsonly` to the Kafka cluster definition part of the config. Set the `tls-noverify` appropriately: setting it to true means that you want to skip host certificate validation (which is bad).

The intention here is to eventually have all the client authentication bits in the clientprofile structure as well, but we're not there yet. We can also add more TLS configuration settings (I just added the one I needed) when we get there to allow client certs, special CA bundles, etc.. We'll need to come up with a good way to read all of that, however.

Please test and validate that this works for you. I've tested it locally and it appears fine.

**Comment by lucrussell** [comment]
Hi,
I had trouble starting burrow after this change. I'm not using TLS and the problem seems related to a missing section in config. The error was:

```
$ ./Burrow --config /Users/lrussell/Dev/Burrow/burrow.cfg
Reading configuration from /Users/lrussell/Dev/Burrow/burrow.cfg
panic: assignment to entry in nil map

goroutine 1 [running]:
main.ValidateConfig(0xc8200dc400, 0x0, 0x0)
	/Users/lrussell/Dev/Burrow/src/github.com/lucrussell/Burrow/config.go:183 +0x47e
main.burrowMain(0x0)
	/Users/lrussell/Dev/Burrow/src/github.com/lucrussell/Burrow/main.go:114 +0x2b9
main.main()
	/Users/lrussell/Dev/Burrow/src/github.com/lucrussell/Burrow/main.go:222 +0x43
```

I added this section to my burrow.cfg and it starts up ok now:

```
[clientprofile "default"]
client-id=burrow-lagchecker
tls=false
tls-noverify=false
```

**Comment by toddpalino** [comment]
This is resolved with the bugfix in #69

**Comment by lucrussell** [comment]
Nice! Thanks for the update. Great work with this project.

**Comment by standingb** [comment]
Is there any additional work being done to get SSL support in Burrow? Unless Kafka is configured with "ssl.client.auth = none" or "ssl.client.auth = requested" it does not work with this work around?

**Comment by vas78** [comment]
@standingb 
We have a similar issue in our project with ssl.client.auth = requested set in Kafka. I`ve filed a PR that makes it possible to add cert/key/CA to Burrow config, see https://github.com/linkedin/Burrow/pull/160

**Comment by vas78** [comment]
Correction: I meant "ssl.client.author = required" of course :) Works perfectly fine now with pem certs in place.
