### ISSUE TITLE
No consumers found

### ISSUE THREAD

**Issue by pfischermx** [linkedin/Burrow#7]
Howdy,

Not sure if this is a bug or I'm missing something. Basically we have a very simple kafka setup, 10 brokers and 3 zookeeper hosts.

Today burrow is able to find the available topics, but it can't find any consumer. We have a consumer and a producer running, I can confirm this because we also have kafka-offsetmonitor running and on that tool we can see the consumer.

$ curl -s -D /dev/null -o - http://localhost:8081/v2/kafka/main/topic | json_xs 
{
   "topics" : [
      "dark",
      "__consumer_offsets"
   ],
   "error" : false,
   "message" : "broker topic list returned"
}

$ curl -s -D /dev/null -o - http://localhost:8081/v2/kafka/main/consumer | json_xs 
{
   "consumers" : [],
   "error" : false,
   "message" : "consumer list returned"
}

Am I'm missing something? Not sure if burrow is suppose to work out of the box or if we need to do something additional with the consumers. Relevant config is:

client-id=burrow-lagchecker
[tickers]
broker-offsets=60

[lagcheck]
intervals=10
expire-group=604800

We don't have any blacklists.

From the logs I can see:
1434495090171073998 [Info] Starting Kafka client for cluster main
1434495090186517134 [Info] Starting consumers for 50 partitions of __consumer_offsets in cluster main
1434495106251738523 [Info] Acquired Zookeeper notifier lock

Thanks!

**Comment by toddpalino** [comment]
Burrow should work out of the box once your clusters are configured, which they appear to be. Are your consumers committing offsets to Kafka, or Zookeeper? This means that the offsets.storage configuration parameter on your consumers must be set to "kafka". Currently, Burrow only supports consumers that are committing offsets to Kafka. I'm looking into ways to efficiently support Zookeeper offsets, but I haven't started any work on it yet.

**Comment by pfischermx** [comment]
Ah, that possibly explains it. Our developer mentioned we commit to ZK but he will take a look to doing it via kafka.

Thanks!

**Comment by toddpalino** [comment]
There is a two-step process for moving from ZK to Kafka offsets. You need to set dual commit to true and offsets storage to zookeeper and bounce your consumer. Then change dual commit to false and bounce again. Joel Koshy covered this in a recent talk - http://www.slideshare.net/jjkoshy/offset-management-in-kafka

The big benefit, besides Burrow working, is that you reduce the load on Zookeeper and you can have your consumers commit offsets more often.

**Comment by TomiSite** [comment]
my burrow only get a part of consumers:
"error":false,"message":"consumer list returned","consumers":["UserDynamic","RecClick","ShowDecay","OrderCnt"] 

but can't get other consumers my-group	ZK	pykafka: (100% coverage, 0 lag) 
appuplogs: (0% coverage, Lag unavailable lag) 
pykafka2: (100% coverage, 0 lag) 
pykafkaaa: (100% coverage, 0 lag) 
OrderCnt	ZK	order-analytics: (0% coverage, Lag unavailable lag) 
RecClick	ZK	infoMatch_tradesupply_log: (0% coverage, Lag unavailable lag) 
RECTESSSSSSST	ZK	infoMatch_tradesupply_log: (0% coverage, Lag unavailable lag) 
RECTEsT	ZK	infoMatch_tradesupply_log: (0% coverage, Lag unavailable lag) 
RECTET2	ZK	infoMatch_tradesupply_log: (0% coverage, Lag unavailable lag)
