### ISSUE TITLE
Action following Error/Warn trigger from Burrow

### ISSUE THREAD

**Issue by raseshdesaiexp** [linkedin/Burrow#78]
Hi,
I have a general question on what should be the plan of action in case Burrow triggers an alert that one of your "consumer group" is in Warn (slowing down) or Error (stopped reading message for one or more partitions)? 

The "consumer group" in most cases would consist of "multiple consumers" to distribute load - so restarting all of them definitely is not the best solution.

Just trying to pick on your brain on what is your reaction to any such alerts...?

Thanks,
Rasesh

**Comment by toddpalino** [comment]
In general, a warning often means that there is some sort of capacity problem with the consumer. It could be that there are not enough consumers for the level of traffic in the topic. It could also be something more broker-related, such as not having enough partitions for the topic (such that there is too much traffic through a single partition). Or the brokers themselves could be overloaded and not delivering messages fast enough. When the consumer is stopped, it typically indicates that the consumer has failed in some way and is stuck. This may be temporary, such as when there is a particularly long consumer rebalance going on.

In either case, I will normally use a consumer offset checker (you can use the one that ships with Kafka. We have a web-based version that we use internally that is a little easier, but unfortunately not currently open-sourceable) to check the group and topic that is having problems. This will show if it is a problem across the board with all consumers (more typical of capacity issues), or a problem with a specific consumer instance (which is usually what causes a stop).
