### ISSUE TITLE
Burrow force GOMAXPROCS to be equal to `runtime.NumCPU()`

### ISSUE THREAD

**Issue by dethi** [linkedin/Burrow#782]
When running Burrow on Kubernetes, we see a lot of CPU throttling during the initial startup. This happens because of the CPU limit we set on the container.

Two way to fix this:
1. manually setting `GOMAXPROCS` environment variable to match the CPU limit
2. auto-adjustment by looking at the cgroups. The most popular package to do that is: https://github.com/uber-go/automaxprocs

Unfortunately, Burrow force GOMAXPROCS to be equal to the number of CPU cores [main.go#L71](https://github.com/linkedin/Burrow/blob/master/main.go#L71) (which in a container, is equal to the number of CPU cores of the host, not the container), so I can't set `GOMAXPROCS` manually.

- Would you consider a PR that use automaxprocs? 
- Or at minimum a PR that add a configuration to disable [main.go#L71](https://github.com/linkedin/Burrow/blob/master/main.go#L71)?

**Comment by dethi** [comment]
@bai any thought?

**Comment by joseronierison** [comment]
👍 

Currently we are setting the GOMAXPROCS manually, but it would be better to have a automatic configuration for that using the automaxprocs .
