### ISSUE TITLE
Consumer lag via burrow api is consistently 0

### ISSUE THREAD

**Issue by puraniprasanna** [linkedin/Burrow#79]
There is a topic that exists with 6 partitions and 3 replication factors. When I call burrow api to get the consumer lag information, it is 0 for most of the times. At the same time debug log provides the lag value as ‘-1’.  But kafka binaries provides correct offset lag values.

How to get correct lag values via burrow api rather than 0?
How to print partitions start & end offset values in debug logs?  

I tried broker offset values 60s,10s and lagcheck interval 2s,10s. But still the lag value remains the same.
[tickers]
broker-offsets=10
[lagcheck]
intervals=10

**Comment by toddpalino** [comment]
Can you show the complete output from the API call? As well as the debug log?

**Comment by karthimohan** [comment]
I am facing similar issue.  I always get the lag when i use burrow api. I always get lag as 0 and the status as OK even though there is clearly a lag when i use kafka offset checker.

{"error":false,"message":"consumer group status returned","status":{"cluster":"dev","group":"xxxx","status":"OK","complete":false,"partitions":[],"partition_count":2,"maxlag":null,"totallag":0},"request":{"url":"/v2/kafka/dev/consumer/xxx/lag","host":"xxxx","cluster":"dev","group":"xxxxx","topic":""}}


[2016-07-27 17:25:09,264] WARN WARNING: ConsumerOffsetChecker is deprecated and will be dropped in releases following 0.9.0. Use ConsumerGroupCommand instead. (kafka.tools.ConsumerOffsetChecker$)
Group           Topic                          Pid Offset          logSize         Lag             Owner
xxx aaaaa              0   5661036         5661179         143             none
xxx bbbb       0   451             1727            1276            none

FYI I am using Zk offset zookeeper-offsets=true

Can you help me with this. Also do you have any plans to support Prometheus integration?

**Comment by toddpalino** [comment]
@karthimohan, you are getting this because the consumer is not actively committing offsets. The consumer is detected because it's in Zookeeper, but as there are no offset commits happening, Burrow cannot get enough offsets to reliably calculate status (defined by the `intervals` configuration). Because of this, it marks the consumer as good until it has a complete view, and sets the `complete` flag in the response to `false`.
