### ISSUE TITLE
ansible playbook for burrow

### ISSUE THREAD

**Issue by slb350** [linkedin/Burrow#8]
We are starting to deploy burrow to our environments, so I created a playbook for Burrow. You can find it [here](https://github.com/slb350/ansible-burrow).

You can also just install it via galaxy:

`ansible-galaxy install slb350.Ansible-Burrow`  

Thanks! Let me know if you have any suggestions. We use ubuntu/trusty, and so far no issue.

**Comment by toddpalino** [comment]
Thanks @slb350! I've added an "Associated Projects" page to the wiki and linked it there.
