### ISSUE TITLE
Zookeeper Offsets Checking requires a base path other than '/'

### ISSUE THREAD

**Issue by jranson** [linkedin/Burrow#80]
Some of our consumers are currently using the 0.8 kafka client (and thus storing their offsets in zookeeper). We have a zookeeper cluster per kafka cluster, and so we keep our base path as '/'.

When I access http://{burrow_fqdn}:port/v2/kafka/{cluster}/consumer, the consumer list shows as consumers":[].

Looking at zookeeper.go, you are constructing the path as ZookeeperPath + "/consumers", which means your zookeeper client would look for a non-existent path of "//consumers" with 2 slashes at the front when zookeeper-path=/

When I remove the zookeeper-path config line from my burrow.cfg, the application crashes. Likewise, when I try to set it to an empty string (e.g., zookeeper-path=, or zookeeper-path='') the application also crashes.

This means that there is currently no known way to support zookeeper offset checking unless a chroot is used and supplied in the zookeeper-path configuration.

You should support a config of "zookeeper-path=/". This can easily be done (and will fix a lot of other potential user-created issues) by stripping any trailing slashes from ZookeeperPath supplied in zookeeper.cfg (so "/" would become an empty string), prior to concatenating ZookeeperPath + "/consumers" (line 70, zookeeper.go) to initiate the offset checking query.

**Comment by toddpalino** [comment]
This is already taken care of in config.go:

```go
    switch cfg.ZookeeperPath {
    case "":
      errs = append(errs, fmt.Sprintf("Zookeeper path is not specified for cluster %s", cluster))
    case "/":
      // If we're using the root path, instead of chroot, set it blank here so we don't get double slashes
      cfg.ZookeeperPath = ""
    default:
      if !validateZookeeperPath(cfg.ZookeeperPath) {
        errs = append(errs, fmt.Sprintf("Zookeeper path is not valid for cluster %s", cluster))
      }
    }
```

That was fixed back in November with https://github.com/linkedin/Burrow/commit/559cab16e26ac8ab4c07bd42266a6326de9b5f1d
