### ISSUE TITLE
Is burrow compatible with kafka 0.10.0.0 ? 

### ISSUE THREAD

**Issue by b13n1u** [linkedin/Burrow#81]
Short question, is burrow compatible with the new kafka version 0.10.0.0 ? If not are there any plans to make it compatible ? :)  We would like to upgrade kafka from 0.9.0.1 to 0.10  but I don't want to loose burrow :)

**Comment by nj20** [comment]
I am currently using burrow with Kafka 0.10.

**Comment by toddpalino** [comment]
Yes, there should be no problem with using 0.10. We're moving over to it internally without any issues with Burrow.

**Comment by b13n1u** [comment]
Thx!
