### ISSUE TITLE
Consumer commiting offsets but not getting listed through /v2/kafka/(cluster)/consumer

### ISSUE THREAD

**Issue by abhimanyunagrath** [linkedin/Burrow#85]
I set up a burrow install and pointed to my Kafka server.(1 Broker and 1 zookeeper).When I call /v2/kafka/kafka1/consumer , I get the response, no consumers. i.e {"error": false,"message": "consumer list returned","consumers": [],"request": {"url": "/v2/kafka/local/consumer/","host": "<burrow server IP>", "cluster": "local","group": "","topic": ""}} 
My offset.storage = kafka.
I know that  cluster  is connected to a consumer and in processing messages.All other endpoints, not at the consumer level, appear to work fine.
 My burrow.cfg is shown as
[general]
logdir=burrowlogs
logconfig=config/logging.cfg
pidfile=burrow.pid
client-id=burrow-lagchecker
group-blacklist=^(console-consumer-|python-kafka-consumer-).*$

[zookeeper]
hostname=<ZookeeperIp>
port=2181
timeout=6
lock-path=/burrow/notifier

[kafka "local"]
broker=<KafkaIp>
broker-port=9092
zookeeper=<ZookeeperIp>
zookeeper-port=2181
zookeeper-path=/
offsets-topic=__consumer_offsets

[storm "local"]
#zookeeper=zkhost01.example.com
#zookeeper=zkhost02.example.com
#zookeeper=zkhost03.example.com
#zookeeper-port=2181
#zookeeper-path=/kafka-cluster/stormconsumers

[tickers]
broker-offsets=60

[lagcheck]
intervals=10
expire-group=604800

[httpserver]
server=on
port=8080

[smtp]
server=mailserver.example.com
port=25
from=burrow-noreply@example.com
template=config/default-email.tmpl

[email "bofh@example.com"]
group=local,critical-consumer-group
group=local,other-consumer-group
interval=60

[httpnotifier]
url=http://notification.server.example.com:9000/v1/alert
interval=60
extra=app=burrow
extra=tier=STG
template-post=config/default-http-post.tmpl
template-delete=config/default-http-delete.tmpl
timeout=5
keepalive=30 

My burrow.out is 

Started Burrow at June 30, 2016 at 3:07pm (UTC)
2016/06/30 15:10:27 http: multiple response.WriteHeader calls
2016/06/30 15:10:29 http: multiple response.WriteHeader calls
2016/06/30 15:10:38 http: multiple response.WriteHeader calls
2016/06/30 15:10:39 http: multiple response.WriteHeader calls
2016/06/30 15:10:40 http: multiple response.WriteHeader calls
2016/06/30 15:10:41 http: multiple response.WriteHeader calls
2016/06/30 15:10:42 http: multiple response.WriteHeader calls
2016/06/30 15:10:44 http: multiple response.WriteHeader calls
2016/06/30 15:10:45 http: multiple response.WriteHeader calls
2016/06/30 15:10:45 http: multiple response.WriteHeader calls
2016/06/30 15:10:47 http: multiple response.WriteHeader calls

I am using Kafka version  0.10.0.

**Comment by toddpalino** [comment]
It appears from #80 that there is a bug with non-chroot Zookeeper environments. I haven't had a chance to look at it to create a PR for it, however.

**Comment by toddpalino** [comment]
OK, #80 isn't actually a problem at all in current versions of Burrow. However, it doesn't look like you've enabled Zookeeper offset checking for your cluster. You need to add the config `zookeeper-enable=true` to the `[kafka "local"]` section of your config to do this.

**Comment by abhimanyunagrath** [comment]
@toddpalino I am getting the following error while adding zookeeper-enable= true in my burrow.cfg 
**Error**:Failed to parse gcfg data: invalid variable: section "kafka" subsection "local" variable "zookeeper-enable"

**burrow.cfg**
[general]
logdir=burrowlogs
logconfig=config/logging.cfg
pidfile=burrow.pid
client-id=burrow-lagchecker
group-blacklist=^(console-consumer-|python-kafka-consumer-).*$

[zookeeper]
hostname=10.165.116.90
port=2181
timeout=6
lock-path=/burrow/notifier

[kafka "local"]
broker=10.165.116.90
broker-port=9092
zookeeper=10.165.116.90
zookeeper-port=2181
zookeeper-path=/
offsets-topic=__consumer_offsets
zookeeper-enable = true

[storm "local"]
#zookeeper=zkhost01.example.com
#zookeeper=zkhost02.example.com
#zookeeper=zkhost03.example.com
#zookeeper-port=2181
#zookeeper-path=/kafka-cluster/stormconsumers

[tickers]
broker-offsets=60

[lagcheck]
intervals=10
expire-group=604800

[httpserver]
server=on
port=8080

[smtp]
server=mailserver.example.com
port=25
from=burrow-noreply@example.com
template=config/default-email.tmpl

[email "bofh@example.com"]
group=local,critical-consumer-group
group=local,other-consumer-group
interval=60

[httpnotifier]
url=http://notification.server.example.com:9000/v1/alert
interval=60
extra=app=burrow
extra=tier=STG
template-post=config/default-http-post.tmpl
template-delete=config/default-http-delete.tmpl
timeout=5
keepalive=30

**Comment by toddpalino** [comment]
Sorry, my mistake. I wrote the config and I keep mistyping it. It's `zookeeper-offsets`

**Comment by abhimanyunagrath** [comment]
Thanks @toddpalino issue is resolved. I am having one more query that is it possible through burrow that I can get information containing "ConsumerId","offset","Lag","Topic","PartitionId".

**Comment by toddpalino** [comment]
By using the `/lag` endpoint for the consumer group, you can get a full listing of the partitions consumed by the group with the start and end committed offsets that Burrow has.
