### ISSUE TITLE
Inconsistent Consumer list

### ISSUE THREAD

**Issue by nj20** [linkedin/Burrow#86]
Hey,

First of all, I think that burrow is a great tool and thank you very much for releasing this software. However, I am having one problem with the consumer list being very inconsistent when calling the endpoint multiple times. Sometimes there are 10 consumers and other times there are 50 consumers even though the actual number of consumers in Kafka are the same. Would you have any idea over why this happens?

Thanks,
Naman

**Comment by toddpalino** [comment]
That doesn't sound right, as Burrow doesn't have any way to remove a consumer group, unless there's an explicit call to the delete endpoint. Can you please provide your configuration information, as well as the log output and the specific API calls you're making?

**Comment by nj20** [comment]
Hey, sorry for the really late reply. I can let you know that we were running 3 instances of burrow (behind a load balancer) over a cluster of 3 nodes of Kafka and 3 nodes of zookeeper. When we shut down two instances of burrow, the results were consistent. I am sorry but I can't provide you with the log files yet. I know that we are not calling any deleting end points.

**Comment by pavansai8** [comment]
Unable to retrieve consumers groups list. Throwing below error while sending HTTP request.

error": false
"message": "consumer list returned"
"consumers": [0]
"request": {
"url": "/v2/kafka/DevCluster/consumer"
"host": "nj09mhf5527.mhf.mhc"
"cluster": "DevCluster"
"group": ""
"topic": ""

But we have already few consumer groups present on our kafka cluster.

console-consumer-26402
samplegroup
KafkaManagerOffsetCache
console-consumer-78572
console-consumer-6043
Can someone help me

This is my request http://nj09mhf5527.mhf.mhc:8000/v2/kafka/DevCluster/consumer

**Comment by toddpalino** [comment]
On the consistency issue, it sound like your instances of burrow were running differing configs, or otherwise having an issue between them. For example, if you had a consumer that stopped between the time you started up instances of Burrow, then the new instances would not know about it.

On the second issue, please post your configuration, as well as the exact output from the request. What you've posted is not a response from Burrow, as the `consumers` key is a list of strings. It can't have an integer 0 as a single entry.

**Comment by pavansai8** [comment]
[general]
logdir=/home/pbhaskaruni
logconfig=/home/pbhaskaruni/work/go/src/github.com/linkedin/burrow/config/logging.cfg
pidfile=burrow.pid
client-id=burrow-lagchecker
group-blacklist=^(console-consumer-|python-kafka-consumer-).*$

[zookeeper]
hostname=nj09mhf5527.mhf.mhc
hostname=nj09mhf5528.mhf.mhc
hostname=nj09mhf5529.mhf.mhc
port=2181
timeout=6
lock-path=/burrow/notifier

[kafka "DevCluster"]
broker=nj09mhf5527.mhf.mhc
broker=nj09mhf5528.mhf.mhc
broker=nj09mhf5529.mhf.mhc
#broker=kafka04.example.com
#broker=kafka05.example.com
broker-port=9092
zookeeper=nj09mhf5527.mhf.mhc
zookeeper=nj09mhf5528.mhf.mhc
zookeeper=nj09mhf5529.mhf.mhc
zookeeper-port=2181
zookeeper-path=/
offsets-topic=__consumer_offsets

#[storm "DevCluster"]
#zookeeper=nj09mhf5527.mhf.mhc
#zookeeper=nj09mhf5528.mhf.mhc
#zookeeper=nj09mhf5529.mhf.mhc
#zookeeper-port=2181
#zookeeper-path=/kafka-cluster/stormconsumers

[tickers]
broker-offsets=60

[lagcheck]
intervals=10
expire-group=604800

[httpserver]
server=on
port=8000

[smtp]
server=mail03-m.edmz.mcgraw-hill.com
port=25
username=pbhaskaruni@spglobal.com
password=P@ssw0rd8
from=burrow-noreply@example.com
template=/home/pbhaskaruni/work/go/src/github.com/linkedin/burrow/config/default-email.tmpl

[email "pbhaskaruni@spglobal.com"]
group=DevCluster,critical-consumer-group
group=DevCluster,other-consumer-group
interval=60

[httpnotifier]
url=http://http://nj09mhf5528.mhf.mhc:8000/v2/kafka/DevCluster/consumer
interval=60
extra=app=burrow
extra=tier=STG
template-post=/home/pbhaskaruni/work/go/src/github.com/linkedin/burrow/config/default-http-post.tmpl
template-delete=/home/pbhaskaruni/work/go/src/github.com/linkedin/burrow/config/default-http-delete.tmpl
timeout=5
keepalive=30

Also could you please tell me how to configure E-mail alerts from burrow.

**Comment by pavansai8** [comment]
Hi,

I have stopped my consumer. And send some number of messages.
And I could not see max lag value is increasing. It is always showing null.

"error": false
"message": "consumer group status returned"
"status": {
"cluster": "DevCluster"
"group": "testgroup12349"
"status": "OK"
"complete": true
"partitions": [1]
0:  {
"topic": "devtopic4"
"partition": 0
"status": "OK"
"start": {
"offset": 5
"timestamp": 1470996314365
"lag": 0
}-
"end": {
"offset": 31
"timestamp": 1470996766000
"lag": 0
}-
}-
-
"partition_count": 1
"maxlag": null
"totallag": 0
}-
"request": {"url": "/v2/kafka/DevCluster/consumer/testgroup12349/lag"
"host": "nj09mhf5527.mhf.mhc"
"cluster": "DevCluster"
"group": "testgroup12349"
"topic": ""

**Comment by toddpalino** [comment]
Closing out this issue. @nj20, if you get more information, feel free to reopen.
