### ISSUE TITLE
Question: Support for kafka 0.10.0

### ISSUE THREAD

**Issue by krimodeb** [linkedin/Burrow#87]
Hi,

Do you plan to support kafka 0.10.0? I saw that sarama already support kafka 0.10.0 (some fixes were added in the master since the 1.9.0 release).

Regards,

**Comment by b13n1u** [comment]
Burrow works fine with kafka 0.10 :) See issue: https://github.com/linkedin/Burrow/issues/81

**Comment by toddpalino** [comment]
Yeah, Burrow works just fine with 0.10. Right now, there's no support for authentication, but master does support TLS.

If you run into a problem, please open an issue for that with examples.
