### ISSUE TITLE
Visualize lag

### ISSUE THREAD

**Issue by nealbh** [linkedin/Burrow#92]
Is there a UI to visualize the data returned from the REST calls?

**Comment by nealbh** [comment]
within my burrow.cfg I have
[httpserver]
server=on
port=8000

yet, I cannot hit https://localhost:8000/burrow/admin.

**Comment by cgosiak** [comment]
Burrow does not have a GUI associated with it. I use [kafka-manager](https://github.com/yahoo/kafka-manager) which has a pretty intuitive useful GUI

**Comment by nealbh** [comment]
I'm familiar with kafka-manager, but I was looking for a visualization that works with burrow to show how laggy each partition is and alert me when a partition is not in a good state.

**Comment by toddpalino** [comment]
Currently, Burrow can notify in 3 ways - email, callout to another web service, or Slack. Right now, there's no UI in Burrow itself, though I would like to add at least a basic one. However, this isn't a high priority at the moment, so someone else is welcome to work on it and submit a PR.

**Comment by jsvisa** [comment]
@nealbh You can fetch the lag information throw [HTTP Endpoint · linkedin/Burrow Wiki](https://github.com/linkedin/Burrow/wiki/HTTP-Endpoint) , then send those lags to [influxdata/influxdb: Scalable datastore for metrics, events, and real-time analytics](https://github.com/influxdata/influxdb/) or other DBs , visualize it by [grafana/grafana: Gorgeous metric viz, dashboards & editors for Graphite, InfluxDB & OpenTSDB](https://github.com/grafana/grafana) or tools.

**Comment by tulios** [comment]
@nealbh I wrote a front-end for burrow, you can try it out https://github.com/tulios/burrow-stats

**Comment by jsvisa** [comment]
@tulios  Sounds great 👍 , but just wonder where you store the history lag.

**Comment by tulios** [comment]
@jsvisa It's saved locally in the browser (localstorage), you can configured the size of the window (the default is 5min).
