### ISSUE TITLE
simply running burrow as a docker container with existing kafka / zk containers (kafka_2.11-0.10.0.0) with host networking

### ISSUE THREAD

**Issue by petergdoyle** [linkedin/Burrow#93]
**wow**: very hopeful to get this running as it seems extremely valuable effort. spending much more time getting this going than planned. any help much appreciated. 

**goal**: leave my existing single-node kafka broker (latest version: kafka_2.11-0.10.0.0) and zk instances running in docker in "host networking" mode and monitor consumers with burrow without changes to those running containers (i.e. no docker network to have to link or bridge into) and kafka-zk is running on default 2181 and kafka-broker is running on default 9092 - all plain vanilla setup and configuration. Network stat from the Docker Machine (a vagrant virtualized CentOS7 vm 'estreaming.vbx'):
```
[vagrant@estreaming ~]$ sudo netstat -tulpn
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 127.0.0.1:27017         0.0.0.0:*               LISTEN      1316/mongod         
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      994/sshd            
tcp        0      0 127.0.0.1:25            0.0.0.0:*               LISTEN      2020/master         
tcp6       0      0 :::22                   :::*                    LISTEN      994/sshd            
tcp6       0      0 ::1:25                  :::*                    LISTEN      2020/master         
--> tcp6       0      0 :::9092                :::*                    LISTEN      16423/java          
--> tcp6       0      0 :::2181                 :::*                    LISTEN      16005/java          
tcp6       0      0 :::34597                :::*                    LISTEN      16005/java          
tcp6       0      0 :::43782                :::*                    LISTEN      16423/java          
udp        0      0 0.0.0.0:61146           0.0.0.0:*                           12738/dhclient      
udp        0      0 0.0.0.0:68              0.0.0.0:*                           12738/dhclient      
udp        0      0 127.0.0.1:323           0.0.0.0:*                           678/chronyd         
udp6       0      0 ::1:323                 :::*                                678/chronyd         
udp6       0      0 :::61021                :::*                                12738/dhclient      
```

**approach**: 
1) clone the burrow git repo and build the image with a modified ```Burrow/docker-config/burrow.cfg```:

```
[general]
logconfig=/etc/burrow/logging.cfg
group-blacklist=^(console-consumer-|python-kafka-consumer-).*$

[zookeeper]
-->hostname=localhost
port=2181
timeout=6
lock-path=/burrow/notifier

[kafka "local"]
-->broker=localhost
broker-port=9092
offsets-topic=__consumer_offsets
zookeeper=zookeeper
zookeeper-path=/local
zookeeper-offsets=true
offsets-topic=__consumer_offsets

[tickers]
broker-offsets=60

[lagcheck]
intervals=10
expire-group=604800

[httpserver]
server=on
port=8000
```

2) Build the image: 
```
[vagrant@estreaming.vbx burrow]$ docker build -t="estreaming/burrow" Burrow/
```

3) Run the container (overriding the CMD ["/go/bin/burrow", "--config", "/etc/burrow/burrow.cfg"] with a bash shell so that burrow command can be run manually or the container just stops because it fails) with host networking enabled so that port 8000 will be exposed on the docker host machine and no container linking is required:
```
[vagrant@estreaming.vbx burrow]$ docker run --rm -ti --net host estreaming/burrow /bin/bash
```

4) Run the burrow command from the running container:
```
bash-4.3# /go/bin/burrow --config /etc/burrow/burrow.cfg
```

**Problem**: it fails because it cannot because it cannot find neither kafka-zk nor kafka-broker - doesn't seem to be able to find the the zk or broker with host networking?

The burrow log from the running container:
```
bash-4.3# cat /var/tmp/burrow/burrow.log.2016-07-14 
2016-07-14 12:40:05 [INFO] Starting Zookeeper client
2016-07-14 12:40:05 [INFO] Starting Offsets Storage module
2016-07-14 12:40:05 [INFO] Starting HTTP server
2016-07-14 12:40:05 [INFO] Starting Zookeeper client for cluster local
2016-07-14 12:40:05 [ERROR] Cannot get consumer group list for cluster local: zk: could not connect to a server
2016-07-14 12:40:05 [INFO] Starting Kafka client for cluster local
2016-07-14 12:40:05 [ERROR] Cannot fetch offsets from broker 0: dial tcp: lookup estreaming.vbx on 10.0.2.3:53: no such host
2016-07-14 12:40:05 [INFO] Starting consumers for 50 partitions of __consumer_offsets in cluster local
2016-07-14 12:40:05 [CRITICAL] Cannot start Kafka client for cluster local: dial tcp: lookup estreaming.vbx on 10.0.2.3:53: no such host
bash-4.3# 
```
The netstat view from the running container:
```
bash-4.3# netstat -tulpn
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 127.0.0.1:27017         0.0.0.0:*               LISTEN      -                   
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      -                   
tcp        0      0 127.0.0.1:25            0.0.0.0:*               LISTEN      -                   
tcp6       0      0 :::22                   :::*                    LISTEN      -                   
tcp6       0      0 ::1:25                  :::*                    LISTEN      -                   
tcp6       0      0 :::9092                 :::*                    LISTEN      -                   
tcp6       0      0 :::2181                 :::*                    LISTEN      -                   
tcp6       0      0 :::34597                :::*                    LISTEN      -                   
tcp6       0      0 :::43782                :::*                    LISTEN      -                   
udp        0      0 0.0.0.0:61146           0.0.0.0:*                           -                   
udp        0      0 0.0.0.0:68              0.0.0.0:*                           -                   
udp        0      0 127.0.0.1:323           0.0.0.0:*                           -                   
udp6       0      0 ::1:323                 :::*                                -                   
udp6       0      0 :::61021                :::*                                -           
```

**Comment by lueliu** [comment]
@petergdoyle  same to me. you should config a DNS server for your hostname ( estreaming.vbx ) . you need a FQDN hostname for your broker and zookeeper servers.

**Comment by petergdoyle** [comment]
Thanks @lueliu. I can get burrow to execute by manually adding the hostname (estreaming.vbx) to the running container which is not optimal. I can (and do) specify in the kafka-broker/zk configs _localhost_ when running the kaka-broker and its associated zk container so this requirement (of a FQDN) seems to forced by burrow or one of its dependent libraries (go-zookeeper?). 
So if I try to add the $HOSTNAME using the ```--add-host``` directive on the ```docker run``` command it will not take it with host networking enabled ```--net host```.  Using the golang image for example: 
```
[vagrant@estreaming burrow]$ docker run --rm -it --net host --add-host $HOSTNAME:127.0.0.1 golang cat /etc/hosts
docker: Error response from daemon: Conflicting options: custom host-to-IP mapping and the network mode.
See '/usr/bin/docker-current run --help'.
```
So i can add _$HOSTNAME_ using docker internal networking (without the ```--net host```) but that puts me back to using a docker networking mode that i was not wanting 
```
[vagrant@estreaming burrow]$ docker run --rm -it --add-host $HOSTNAME:127.0.0.1 golang cat /etc/hosts
127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
ff00::0	ip6-mcastprefix
ff02::1	ip6-allnodes
ff02::2	ip6-allrouters
127.0.0.1	estreaming.vbx
172.17.0.2	1ba344f3e988
```
And using a terrible hack (before docker supported the ```--add-host``` directive, we can see that /etc/hosts is protected: 
```
[vagrant@estreaming burrow]$ docker run --rm -it --net host golang echo $HOSTNAME 127.0.0.1 >/etc/hosts; cat /etc/hosts
-bash: /etc/hosts: Permission denied
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
```

Is there some reason why (burrow or one of its dependent libraries) is forcing FQDN?

**Comment by lueliu** [comment]
@petergdoyle  Look in the log, it needs to be resolved by DNS. ( port 53 )
```
2016-07-14 12:40:05 [CRITICAL] Cannot start Kafka client for cluster local: dial tcp: lookup estreaming.vbx on 10.0.2.3:53: no such host
bash-4.3# 
```
So, I don't know why, except that have to do.

**Comment by petergdoyle** [comment]
okay ```127.0.0.1``` instead of ```localhost``` works!
```
[zookeeper]
hostname=127.0.0.1
port=2181
timeout=6
lock-path=/burrow/notifier

[kafka "local"]
broker=127.0.0.1
broker-port=9092
offsets-topic=__consumer_offsets
zookeeper=zookeeper
zookeeper-path=/local
zookeeper-offsets=true
offsets-topic=__consumer_offsets
```

**Comment by petergdoyle** [comment]
nope my mistake does not work with above configuration. still requires an entry in /etc/hosts to resolve the docker machine name (streamworks.vbx in my case).

does not work with host networking without manual configuration of the /etc/hosts file to include the docker machine name that the container is running in.

**Comment by toddpalino** [comment]
Burrow doesn't required FQDN, and in fact specifically allows both IPv4 and IPv6 addresses. In addition, as you're getting errors from both Zookeeper and Kafka, which are two completely different downstream libraries, I suspect a networking issue here, and not an application issue. The error showing in your logs is a DNS lookup failure, not an actual error connecting to either Zookeeper or Kafka. Burrow has no way to get that hostname unless you configure it (it's not doing some sort of lookup to find a hostname that you didn't configure). So I don't think that the configuration file you provided and the log match up to the same run.

Your netstat output appears to show that both Zookeeper and Kafka are only listening to IPv6:
```
tcp6       0      0 :::9092                 :::*                    LISTEN      -                   
tcp6       0      0 :::2181                 :::*                    LISTEN      -                   
```

Have you tried setting the hostname in the Burrow configuration to be localhost6 instead of just localhost?

**Comment by petergdoyle** [comment]
Hey thanks for getting back to me...
After reading some of your other posts and responses on (for lack of a better phrase) 

> "not getting consumers to show up as consuming off a topic"

related to` advertised.host.name`, I resolved a problem I had with a python-kafka script not being able to find the broker. But then wondered if that was the Burrow problem as well? And yes it was. So adding `advertised.host.name=127.0.0.1` to the kafka server.properties resolved issues with seemingly any non-java kafka apis (go, python, at least) in finding the broker.

so i am not sure the order of host name resolution but someone stated that advertised.host.name is deprecated now. so maybe this is just a temporary fix?

you seem to be pretty familiar with this issue. would you mind providing comment on the issue and associated options to resolve as i fear my solution works but might be an issue down the road when support for that kafka server-property drops off (as i understand it would being deprecated)

thanks again for your help!

**Comment by blublinsky** [comment]
How do you build docker image from the current repository?
docker build -t lightbend/fdp-burrow:latest .
does not work
