### ISSUE TITLE
Burrow Email Notifier

### ISSUE THREAD

**Issue by cgosiak** [linkedin/Burrow#99]
Hello, 

I am currently experiencing some issues when setting up a notifier for a consumer with a name that contains periods. (ex. ImportantConsumer.V2) I was curious if there was a way around this; hopefully without changing all of my consumer groups. 

On a side note, is it possible to set up alerts for all consumer groups with a wildcard or something of that nature? I am looking for a way to be alerted on all topics without hard coding these names in the config files. And in the future not having to restart burrow when a new notifier is added in the configs.

There is some great work going in to Burrow, and I thank the whole team for all of the continued support to it! Definitely appreciated!

**Comment by toddpalino** [comment]
It looks like the period issue is resolved by PR #95, which is merged now.

Currently, there's no support for a wildcard in the email notifier, though it should be able to be added with relatively little effort given the new multi-notifier code that has been merged under PR #67. I don't have time to work on this right now, but someone else could create a PR for it.
